-- +goose Up
CREATE TABLE meters (
    meter text PRIMARY KEY,
    unit text NOT NULL,
    description text NOT NULL
);

INSERT INTO meters (meter, unit, description) VALUES
    ('input_tokens', 'token', 'Input tokens billed at the standard rate.'),
    ('cached_input_tokens', 'token', 'Input tokens read from the provider prompt cache.'),
    ('cache_write_input_tokens', 'token', 'Input tokens written to the provider prompt cache.'),
    ('output_tokens', 'token', 'Tokens generated by the model.'),
    ('reasoning_tokens', 'token', 'Reasoning tokens, where a provider prices them apart from output tokens.'),
    ('input_audio_tokens', 'token', 'Audio input tokens.'),
    ('output_audio_tokens', 'token', 'Audio tokens generated by the model.'),
    ('input_seconds', 'second', 'Seconds of input audio or video.'),
    ('output_seconds', 'second', 'Seconds of generated audio or video.'),
    ('gpu_seconds', 'second', 'Seconds of GPU time.'),
    ('characters', 'character', 'Characters of input or output text.'),
    ('images', 'image', 'Images generated or edited.'),
    ('megapixels', 'megapixel', 'Megapixels of images generated or edited.'),
    ('audio_minutes', 'minute', 'Minutes of audio processed or generated.'),
    ('requests', 'request', 'Requests priced at a fixed fee each.'),
    ('search_requests', 'request', 'Web search requests the model makes.');

CREATE TABLE pricing_rules (
    pricing_rule_id uuid PRIMARY KEY,
    provider text NOT NULL,
    model text NOT NULL,
    meter text NOT NULL REFERENCES meters (meter),
    conditions jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(conditions) = 'object'),
    unit_price_nanos bigint NOT NULL CHECK (unit_price_nanos >= 0),
    unit_quantity bigint NOT NULL CHECK (unit_quantity > 0),
    minimum_charge_nanos bigint NULL CHECK (minimum_charge_nanos >= 0),
    billing_increment_micros bigint NULL CHECK (billing_increment_micros > 0),
    effective_from timestamptz NOT NULL,
    effective_to timestamptz NULL,
    status text NOT NULL CHECK (status IN ('active', 'deprecated')),
    source text NOT NULL CHECK (source IN ('curated', 'litellm')),
    source_key text NOT NULL,
    source_url text NULL,
    imported_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pricing_rules_effective_period_check CHECK (effective_to > effective_from),
    CONSTRAINT pricing_rules_source_source_key_effective_from_key UNIQUE (source, source_key, effective_from)
);

CREATE INDEX pricing_rules_provider_model_meter_index ON pricing_rules (provider, model, meter);

CREATE TABLE provider_model_aliases (
    provider text NOT NULL,
    alias text NOT NULL,
    model text NOT NULL,
    PRIMARY KEY (provider, alias)
);

CREATE TABLE pricing_overrides (
    pricing_override_id uuid PRIMARY KEY,
    environment environment NOT NULL,
    provider text NOT NULL,
    model text NOT NULL,
    meter text NOT NULL REFERENCES meters (meter),
    conditions jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(conditions) = 'object'),
    unit_price_nanos bigint NOT NULL CHECK (unit_price_nanos >= 0),
    unit_quantity bigint NOT NULL CHECK (unit_quantity > 0),
    native_unit text NULL,
    native_unit_price_nanos bigint NULL CHECK (native_unit_price_nanos >= 0),
    minimum_charge_nanos bigint NULL CHECK (minimum_charge_nanos >= 0),
    billing_increment_micros bigint NULL CHECK (billing_increment_micros > 0),
    effective_from timestamptz NOT NULL,
    effective_to timestamptz NULL,
    import_id uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT pricing_overrides_effective_period_check CHECK (effective_to >= effective_from),
    CONSTRAINT pricing_overrides_native_unit_check CHECK ((native_unit IS NULL) = (native_unit_price_nanos IS NULL))
);

CREATE TABLE plans (
    plan_id uuid PRIMARY KEY,
    environment environment NOT NULL,
    name text NOT NULL,
    target_margin_basis_points integer NOT NULL CHECK (target_margin_basis_points BETWEEN 0 AND 9999),
    allowance_nanos bigint NULL CHECK (allowance_nanos >= 0),
    hold_times jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(hold_times) = 'object'),
    status record_status NOT NULL,
    import_id uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT plans_environment_name_key UNIQUE (environment, name)
);

CREATE TABLE customers (
    customer_id uuid PRIMARY KEY,
    environment environment NOT NULL,
    external_id text NOT NULL,
    display_name text NULL,
    plan_id uuid NULL REFERENCES plans (plan_id),
    stripe_customer_id text NULL,
    metadata jsonb NOT NULL DEFAULT '{}' CHECK (jsonb_typeof(metadata) = 'object'),
    status record_status NOT NULL,
    import_id uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customers_environment_external_id_key UNIQUE (environment, external_id),
    CONSTRAINT customers_environment_stripe_customer_id_key UNIQUE (environment, stripe_customer_id)
);

CREATE INDEX customers_environment_created_at_index ON customers (environment, created_at DESC);

-- text_pattern_ops lets LIKE 'prefix%' use this index under a non-C database collation.
CREATE INDEX customers_environment_lower_external_id_index ON customers (environment, lower(external_id) text_pattern_ops);

CREATE TABLE customer_users (
    customer_user_id uuid PRIMARY KEY,
    environment environment NOT NULL,
    customer_id uuid NOT NULL REFERENCES customers (customer_id),
    external_id text NOT NULL,
    import_id uuid NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT customer_users_environment_customer_id_external_id_key UNIQUE (environment, customer_id, external_id)
);

ALTER TABLE environment_settings
    ADD CONSTRAINT environment_settings_default_plan_id_fkey FOREIGN KEY (default_plan_id) REFERENCES plans (plan_id);

-- +goose Down
ALTER TABLE environment_settings DROP CONSTRAINT environment_settings_default_plan_id_fkey;

DROP TABLE customer_users;

DROP TABLE customers;

DROP TABLE plans;

DROP TABLE pricing_overrides;

DROP TABLE provider_model_aliases;

DROP TABLE pricing_rules;

DROP TABLE meters;
