// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeMemberLink = `-- name: ConsumeMemberLink :exec
UPDATE member_links
SET consumed_at = $1::timestamptz
WHERE member_link_id = $2
`

type ConsumeMemberLinkParams struct {
	ConsumedAt   time.Time
	MemberLinkID uuid.UUID
}

func (q *Queries) ConsumeMemberLink(ctx context.Context, arg ConsumeMemberLinkParams) error {
	_, err := q.db.Exec(ctx, consumeMemberLink, arg.ConsumedAt, arg.MemberLinkID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM member_sessions
WHERE session_token_hash IN (
    SELECT expired_sessions.session_token_hash
    FROM member_sessions AS expired_sessions
    WHERE expired_sessions.expires_at <= $1
    LIMIT $2::bigint
)
`

type DeleteExpiredSessionsParams struct {
	Now       time.Time
	BatchSize int64
}

func (q *Queries) DeleteExpiredSessions(ctx context.Context, arg DeleteExpiredSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, arg.Now, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldMemberLinks = `-- name: DeleteOldMemberLinks :execrows
DELETE FROM member_links
WHERE member_link_id IN (
    SELECT old_links.member_link_id
    FROM member_links AS old_links
    WHERE old_links.expires_at < $1 OR old_links.consumed_at < $1
    LIMIT $2::bigint
)
`

type DeleteOldMemberLinksParams struct {
	Cutoff    time.Time
	BatchSize int64
}

func (q *Queries) DeleteOldMemberLinks(ctx context.Context, arg DeleteOldMemberLinksParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldMemberLinks, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionsForMember = `-- name: DeleteSessionsForMember :exec
DELETE FROM member_sessions
WHERE member_id = $1
`

func (q *Queries) DeleteSessionsForMember(ctx context.Context, memberID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionsForMember, memberID)
	return err
}

const expireUnconsumedMemberLinks = `-- name: ExpireUnconsumedMemberLinks :exec
UPDATE member_links
SET expires_at = $1
WHERE member_id = $2
    AND consumed_at IS NULL
    AND expires_at > $1
`

type ExpireUnconsumedMemberLinksParams struct {
	Now      time.Time
	MemberID uuid.UUID
}

func (q *Queries) ExpireUnconsumedMemberLinks(ctx context.Context, arg ExpireUnconsumedMemberLinksParams) error {
	_, err := q.db.Exec(ctx, expireUnconsumedMemberLinks, arg.Now, arg.MemberID)
	return err
}

const insertMemberLink = `-- name: InsertMemberLink :exec
INSERT INTO member_links (member_link_id, member_id, purpose, token_hash, expires_at, created_by_member_id, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertMemberLinkParams struct {
	MemberLinkID      uuid.UUID
	MemberID          uuid.UUID
	Purpose           string
	TokenHash         []byte
	ExpiresAt         time.Time
	CreatedByMemberID *uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) InsertMemberLink(ctx context.Context, arg InsertMemberLinkParams) error {
	_, err := q.db.Exec(ctx, insertMemberLink,
		arg.MemberLinkID,
		arg.MemberID,
		arg.Purpose,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedByMemberID,
		arg.CreatedAt,
	)
	return err
}

const listMembers = `-- name: ListMembers :many
SELECT member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
FROM members
WHERE $1::timestamptz IS NULL
    OR (created_at, member_id) > ($1::timestamptz, $2::uuid)
ORDER BY created_at, member_id
LIMIT $3::bigint
`

type ListMembersParams struct {
	AfterCreatedAt *time.Time
	AfterMemberID  *uuid.UUID
	RowLimit       int64
}

func (q *Queries) ListMembers(ctx context.Context, arg ListMembersParams) ([]Member, error) {
	rows, err := q.db.Query(ctx, listMembers, arg.AfterCreatedAt, arg.AfterMemberID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.MemberID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Status,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockActiveMembers = `-- name: LockActiveMembers :one
SELECT
    count(*) FILTER (WHERE active_members.password_hash IS NOT NULL) AS password_member_count,
    count(*) FILTER (WHERE active_members.member_id = $1::uuid) = 1 AS actor_active
FROM (
    SELECT member_id, password_hash
    FROM members
    WHERE status = 'active'
    ORDER BY member_id
    FOR UPDATE
) AS active_members
`

type LockActiveMembersRow struct {
	PasswordMemberCount int64
	ActorActive         bool
}

func (q *Queries) LockActiveMembers(ctx context.Context, actorMemberID uuid.UUID) (LockActiveMembersRow, error) {
	row := q.db.QueryRow(ctx, lockActiveMembers, actorMemberID)
	var i LockActiveMembersRow
	err := row.Scan(&i.PasswordMemberCount, &i.ActorActive)
	return i, err
}

const selectMemberLinkForUpdate = `-- name: SelectMemberLinkForUpdate :one
SELECT member_link_id, member_id, purpose, token_hash, expires_at, consumed_at, created_by_member_id, created_at
FROM member_links
WHERE member_link_id = $1
FOR UPDATE
`

func (q *Queries) SelectMemberLinkForUpdate(ctx context.Context, memberLinkID uuid.UUID) (MemberLink, error) {
	row := q.db.QueryRow(ctx, selectMemberLinkForUpdate, memberLinkID)
	var i MemberLink
	err := row.Scan(
		&i.MemberLinkID,
		&i.MemberID,
		&i.Purpose,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
	)
	return i, err
}

const selectMemberLinkWithMember = `-- name: SelectMemberLinkWithMember :one
SELECT member_links.member_link_id, member_links.member_id, member_links.purpose, member_links.token_hash, member_links.expires_at, member_links.consumed_at, member_links.created_by_member_id, member_links.created_at, members.member_id, members.email, members.display_name, members.password_hash, members.status, members.last_login_at, members.created_at, members.updated_at
FROM member_links
JOIN members ON members.member_id = member_links.member_id
WHERE member_links.token_hash = $1
`

type SelectMemberLinkWithMemberRow struct {
	MemberLink MemberLink
	Member     Member
}

func (q *Queries) SelectMemberLinkWithMember(ctx context.Context, tokenHash []byte) (SelectMemberLinkWithMemberRow, error) {
	row := q.db.QueryRow(ctx, selectMemberLinkWithMember, tokenHash)
	var i SelectMemberLinkWithMemberRow
	err := row.Scan(
		&i.MemberLink.MemberLinkID,
		&i.MemberLink.MemberID,
		&i.MemberLink.Purpose,
		&i.MemberLink.TokenHash,
		&i.MemberLink.ExpiresAt,
		&i.MemberLink.ConsumedAt,
		&i.MemberLink.CreatedByMemberID,
		&i.MemberLink.CreatedAt,
		&i.Member.MemberID,
		&i.Member.Email,
		&i.Member.DisplayName,
		&i.Member.PasswordHash,
		&i.Member.Status,
		&i.Member.LastLoginAt,
		&i.Member.CreatedAt,
		&i.Member.UpdatedAt,
	)
	return i, err
}

const updateMemberStatus = `-- name: UpdateMemberStatus :exec
UPDATE members
SET status = $1, updated_at = $2
WHERE member_id = $3
`

type UpdateMemberStatusParams struct {
	Status    RecordStatus
	UpdatedAt time.Time
	MemberID  uuid.UUID
}

func (q *Queries) UpdateMemberStatus(ctx context.Context, arg UpdateMemberStatusParams) error {
	_, err := q.db.Exec(ctx, updateMemberStatus, arg.Status, arg.UpdatedAt, arg.MemberID)
	return err
}
