// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertMember = `-- name: InsertMember :one
INSERT INTO members (member_id, email, display_name, password_hash, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'active', $5, $5)
ON CONFLICT (email) DO NOTHING
RETURNING member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
`

type InsertMemberParams struct {
	MemberID     uuid.UUID
	Email        string
	DisplayName  string
	PasswordHash *string
	CreatedAt    time.Time
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, insertMember,
		arg.MemberID,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.CreatedAt,
	)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMemberByEmail = `-- name: SelectMemberByEmail :one
SELECT member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
FROM members
WHERE email = $1
`

func (q *Queries) SelectMemberByEmail(ctx context.Context, email string) (Member, error) {
	row := q.db.QueryRow(ctx, selectMemberByEmail, email)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMemberByID = `-- name: SelectMemberByID :one
SELECT member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
FROM members
WHERE member_id = $1
`

func (q *Queries) SelectMemberByID(ctx context.Context, memberID uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, selectMemberByID, memberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectMemberByIDForUpdate = `-- name: SelectMemberByIDForUpdate :one
SELECT member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
FROM members
WHERE member_id = $1
FOR UPDATE
`

func (q *Queries) SelectMemberByIDForUpdate(ctx context.Context, memberID uuid.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, selectMemberByIDForUpdate, memberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectSignInMemberForUpdate = `-- name: SelectSignInMemberForUpdate :one
SELECT member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
FROM members
WHERE member_id = $1
    AND password_hash = $2
    AND status = 'active'
FOR UPDATE
`

type SelectSignInMemberForUpdateParams struct {
	MemberID     uuid.UUID
	PasswordHash *string
}

func (q *Queries) SelectSignInMemberForUpdate(ctx context.Context, arg SelectSignInMemberForUpdateParams) (Member, error) {
	row := q.db.QueryRow(ctx, selectSignInMemberForUpdate, arg.MemberID, arg.PasswordHash)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberDisplayName = `-- name: UpdateMemberDisplayName :one
UPDATE members
SET display_name = $1, updated_at = $2
WHERE member_id = $3
RETURNING member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
`

type UpdateMemberDisplayNameParams struct {
	DisplayName string
	UpdatedAt   time.Time
	MemberID    uuid.UUID
}

func (q *Queries) UpdateMemberDisplayName(ctx context.Context, arg UpdateMemberDisplayNameParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberDisplayName, arg.DisplayName, arg.UpdatedAt, arg.MemberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberLastLogin = `-- name: UpdateMemberLastLogin :one
UPDATE members
SET last_login_at = $1
WHERE member_id = $2
RETURNING member_id, email, display_name, password_hash, status, last_login_at, created_at, updated_at
`

type UpdateMemberLastLoginParams struct {
	LastLoginAt *time.Time
	MemberID    uuid.UUID
}

func (q *Queries) UpdateMemberLastLogin(ctx context.Context, arg UpdateMemberLastLoginParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberLastLogin, arg.LastLoginAt, arg.MemberID)
	var i Member
	err := row.Scan(
		&i.MemberID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMemberPasswordHash = `-- name: UpdateMemberPasswordHash :exec
UPDATE members
SET password_hash = $1, updated_at = $2
WHERE member_id = $3
`

type UpdateMemberPasswordHashParams struct {
	PasswordHash *string
	UpdatedAt    time.Time
	MemberID     uuid.UUID
}

func (q *Queries) UpdateMemberPasswordHash(ctx context.Context, arg UpdateMemberPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateMemberPasswordHash, arg.PasswordHash, arg.UpdatedAt, arg.MemberID)
	return err
}
