// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type RecordStatus string

const (
	RecordStatusActive   RecordStatus = "active"
	RecordStatusDisabled RecordStatus = "disabled"
	RecordStatusArchived RecordStatus = "archived"
)

func (e *RecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordStatus(s)
	case string:
		*e = RecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordStatus: %T", src)
	}
	return nil
}

type NullRecordStatus struct {
	RecordStatus RecordStatus
	Valid        bool // Valid is true if RecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordStatus), nil
}

type Member struct {
	MemberID     uuid.UUID
	Email        string
	DisplayName  string
	PasswordHash *string
	Status       RecordStatus
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MemberLink struct {
	MemberLinkID      uuid.UUID
	MemberID          uuid.UUID
	Purpose           string
	TokenHash         []byte
	ExpiresAt         time.Time
	ConsumedAt        *time.Time
	CreatedByMemberID *uuid.UUID
	CreatedAt         time.Time
}
