// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package queries

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM member_sessions
WHERE session_token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionTokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionTokenHash)
	return err
}

const deleteSessionsForMemberExcept = `-- name: DeleteSessionsForMemberExcept :exec
DELETE FROM member_sessions
WHERE member_id = $1
    AND session_token_hash <> $2
`

type DeleteSessionsForMemberExceptParams struct {
	MemberID             uuid.UUID
	KeepSessionTokenHash []byte
}

func (q *Queries) DeleteSessionsForMemberExcept(ctx context.Context, arg DeleteSessionsForMemberExceptParams) error {
	_, err := q.db.Exec(ctx, deleteSessionsForMemberExcept, arg.MemberID, arg.KeepSessionTokenHash)
	return err
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO member_sessions (session_token_hash, member_id, expires_at, last_seen_at, user_agent, ip_address, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertSessionParams struct {
	SessionTokenHash []byte
	MemberID         uuid.UUID
	ExpiresAt        time.Time
	LastSeenAt       time.Time
	UserAgent        string
	IpAddress        netip.Addr
	CreatedAt        time.Time
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.SessionTokenHash,
		arg.MemberID,
		arg.ExpiresAt,
		arg.LastSeenAt,
		arg.UserAgent,
		arg.IpAddress,
		arg.CreatedAt,
	)
	return err
}

const selectSessionWithMember = `-- name: SelectSessionWithMember :one
SELECT members.member_id, members.email, members.display_name, members.password_hash, members.status, members.last_login_at, members.created_at, members.updated_at, member_sessions.last_seen_at
FROM member_sessions
JOIN members ON members.member_id = member_sessions.member_id
WHERE member_sessions.session_token_hash = $1
    AND member_sessions.expires_at > $2
    AND members.status = 'active'
`

type SelectSessionWithMemberParams struct {
	SessionTokenHash []byte
	Now              time.Time
}

type SelectSessionWithMemberRow struct {
	Member     Member
	LastSeenAt time.Time
}

func (q *Queries) SelectSessionWithMember(ctx context.Context, arg SelectSessionWithMemberParams) (SelectSessionWithMemberRow, error) {
	row := q.db.QueryRow(ctx, selectSessionWithMember, arg.SessionTokenHash, arg.Now)
	var i SelectSessionWithMemberRow
	err := row.Scan(
		&i.Member.MemberID,
		&i.Member.Email,
		&i.Member.DisplayName,
		&i.Member.PasswordHash,
		&i.Member.Status,
		&i.Member.LastLoginAt,
		&i.Member.CreatedAt,
		&i.Member.UpdatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE member_sessions
SET last_seen_at = $1, expires_at = $2
WHERE session_token_hash = $3
`

type TouchSessionParams struct {
	LastSeenAt       time.Time
	ExpiresAt        time.Time
	SessionTokenHash []byte
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.LastSeenAt, arg.ExpiresAt, arg.SessionTokenHash)
	return err
}
