// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package queries

import (
	"context"
	"time"
)

const catalogRuleExists = `-- name: CatalogRuleExists :one
SELECT EXISTS (
    SELECT 1
    FROM pricing_rules
    WHERE provider = $1
        AND model = $2
        AND meter = $3
        AND conditions = $4
        AND effective_to IS NULL
)
`

type CatalogRuleExistsParams struct {
	Provider   string
	Model      string
	Meter      string
	Conditions []byte
}

func (q *Queries) CatalogRuleExists(ctx context.Context, arg CatalogRuleExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, catalogRuleExists,
		arg.Provider,
		arg.Model,
		arg.Meter,
		arg.Conditions,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listMeters = `-- name: ListMeters :many
SELECT meter, unit, description
FROM meters
ORDER BY meter COLLATE "C"
`

func (q *Queries) ListMeters(ctx context.Context) ([]Meter, error) {
	rows, err := q.db.Query(ctx, listMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meter
	for rows.Next() {
		var i Meter
		if err := rows.Scan(&i.Meter, &i.Unit, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModels = `-- name: ListModels :many
WITH model_prices AS (
    SELECT provider, model, meter, effective_to IS NULL AS in_effect
    FROM pricing_rules
    UNION ALL
    SELECT provider, model, meter, effective_to IS NULL OR effective_to > $10::timestamptz AS in_effect
    FROM pricing_overrides
    WHERE environment = $11
)
SELECT provider, model, coalesce(bool_or(in_effect), false)::boolean AS has_price_in_effect
FROM model_prices
WHERE ($1::text IS NULL OR provider = $1::text)
    AND (
        $2::text IS NULL
        OR strpos(lower(model), lower($2::text)) > 0
        OR (provider, model) IN (
            SELECT unnest($3::text[]), unnest($4::text[])
        )
    )
    AND (
        $5::text IS NULL
        OR (provider COLLATE "C", model COLLATE "C") > ($5::text COLLATE "C", $6::text COLLATE "C")
    )
GROUP BY provider, model
HAVING ($7::text IS NULL OR bool_or(meter = $7::text))
    AND ($8::boolean OR bool_or(in_effect))
ORDER BY provider COLLATE "C", model COLLATE "C"
LIMIT $9::bigint
`

type ListModelsParams struct {
	Provider             *string
	Search               *string
	DisplayNameProviders []string
	DisplayNameModels    []string
	AfterProvider        *string
	AfterModel           *string
	Meter                *string
	IncludeDeprecated    bool
	RowLimit             int64
	At                   time.Time
	Environment          Environment
}

type ListModelsRow struct {
	Provider         string
	Model            string
	HasPriceInEffect bool
}

func (q *Queries) ListModels(ctx context.Context, arg ListModelsParams) ([]ListModelsRow, error) {
	rows, err := q.db.Query(ctx, listModels,
		arg.Provider,
		arg.Search,
		arg.DisplayNameProviders,
		arg.DisplayNameModels,
		arg.AfterProvider,
		arg.AfterModel,
		arg.Meter,
		arg.IncludeDeprecated,
		arg.RowLimit,
		arg.At,
		arg.Environment,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListModelsRow
	for rows.Next() {
		var i ListModelsRow
		if err := rows.Scan(&i.Provider, &i.Model, &i.HasPriceInEffect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenOverrideConditions = `-- name: ListOpenOverrideConditions :many
SELECT DISTINCT conditions
FROM pricing_overrides
WHERE environment = $1
    AND provider = $2
    AND model = $3
    AND (effective_to IS NULL OR effective_to > $4::timestamptz)
ORDER BY conditions
`

type ListOpenOverrideConditionsParams struct {
	Environment Environment
	Provider    string
	Model       string
	At          time.Time
}

func (q *Queries) ListOpenOverrideConditions(ctx context.Context, arg ListOpenOverrideConditionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listOpenOverrideConditions,
		arg.Environment,
		arg.Provider,
		arg.Model,
		arg.At,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var conditions []byte
		if err := rows.Scan(&conditions); err != nil {
			return nil, err
		}
		items = append(items, conditions)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenRuleConditions = `-- name: ListOpenRuleConditions :many
SELECT DISTINCT conditions
FROM pricing_rules
WHERE provider = $1
    AND model = $2
    AND effective_to IS NULL
ORDER BY conditions
`

type ListOpenRuleConditionsParams struct {
	Provider string
	Model    string
}

func (q *Queries) ListOpenRuleConditions(ctx context.Context, arg ListOpenRuleConditionsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listOpenRuleConditions, arg.Provider, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var conditions []byte
		if err := rows.Scan(&conditions); err != nil {
			return nil, err
		}
		items = append(items, conditions)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAliasedModel = `-- name: SelectAliasedModel :one
SELECT model
FROM provider_model_aliases
WHERE provider = $1
    AND alias = $2
`

type SelectAliasedModelParams struct {
	Provider string
	Alias    string
}

func (q *Queries) SelectAliasedModel(ctx context.Context, arg SelectAliasedModelParams) (string, error) {
	row := q.db.QueryRow(ctx, selectAliasedModel, arg.Provider, arg.Alias)
	var model string
	err := row.Scan(&model)
	return model, err
}
