// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: import.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const closePricingRule = `-- name: ClosePricingRule :exec
UPDATE pricing_rules
SET effective_to = $1::timestamptz, status = $2, imported_at = $3
WHERE pricing_rule_id = $4
`

type ClosePricingRuleParams struct {
	EffectiveTo   time.Time
	Status        string
	ImportedAt    time.Time
	PricingRuleID uuid.UUID
}

func (q *Queries) ClosePricingRule(ctx context.Context, arg ClosePricingRuleParams) error {
	_, err := q.db.Exec(ctx, closePricingRule,
		arg.EffectiveTo,
		arg.Status,
		arg.ImportedAt,
		arg.PricingRuleID,
	)
	return err
}

const deleteProviderModelAliases = `-- name: DeleteProviderModelAliases :exec
DELETE FROM provider_model_aliases
`

func (q *Queries) DeleteProviderModelAliases(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteProviderModelAliases)
	return err
}

const insertProviderModelAlias = `-- name: InsertProviderModelAlias :exec
INSERT INTO provider_model_aliases (provider, alias, model)
VALUES ($1, $2, $3)
`

type InsertProviderModelAliasParams struct {
	Provider string
	Alias    string
	Model    string
}

func (q *Queries) InsertProviderModelAlias(ctx context.Context, arg InsertProviderModelAliasParams) error {
	_, err := q.db.Exec(ctx, insertProviderModelAlias, arg.Provider, arg.Alias, arg.Model)
	return err
}

const selectLatestImportedAt = `-- name: SelectLatestImportedAt :one
SELECT imported_at
FROM pricing_rules
WHERE source = $1
ORDER BY imported_at DESC
LIMIT 1
`

func (q *Queries) SelectLatestImportedAt(ctx context.Context, source string) (time.Time, error) {
	row := q.db.QueryRow(ctx, selectLatestImportedAt, source)
	var imported_at time.Time
	err := row.Scan(&imported_at)
	return imported_at, err
}

const selectOpenPricingRules = `-- name: SelectOpenPricingRules :many
SELECT pricing_rule_id, source_key, unit_price_nanos, unit_quantity, minimum_charge_nanos, billing_increment_micros, effective_from, source_url
FROM pricing_rules
WHERE source = $1
    AND effective_to IS NULL
`

type SelectOpenPricingRulesRow struct {
	PricingRuleID          uuid.UUID
	SourceKey              string
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	EffectiveFrom          time.Time
	SourceURL              *string
}

func (q *Queries) SelectOpenPricingRules(ctx context.Context, source string) ([]SelectOpenPricingRulesRow, error) {
	rows, err := q.db.Query(ctx, selectOpenPricingRules, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SelectOpenPricingRulesRow
	for rows.Next() {
		var i SelectOpenPricingRulesRow
		if err := rows.Scan(
			&i.PricingRuleID,
			&i.SourceKey,
			&i.UnitPriceNanos,
			&i.UnitQuantity,
			&i.MinimumChargeNanos,
			&i.BillingIncrementMicros,
			&i.EffectiveFrom,
			&i.SourceURL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPricingRule = `-- name: UpsertPricingRule :exec
INSERT INTO pricing_rules (
    pricing_rule_id, provider, model, meter, conditions, unit_price_nanos, unit_quantity, minimum_charge_nanos,
    billing_increment_micros, effective_from, status, source, source_key, source_url, imported_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, 'active', $11, $12, $13, $14
)
ON CONFLICT (source, source_key, effective_from) DO UPDATE
SET unit_price_nanos = EXCLUDED.unit_price_nanos,
    unit_quantity = EXCLUDED.unit_quantity,
    minimum_charge_nanos = EXCLUDED.minimum_charge_nanos,
    billing_increment_micros = EXCLUDED.billing_increment_micros,
    source_url = EXCLUDED.source_url,
    imported_at = EXCLUDED.imported_at
`

type UpsertPricingRuleParams struct {
	PricingRuleID          uuid.UUID
	Provider               string
	Model                  string
	Meter                  string
	Conditions             []byte
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	EffectiveFrom          time.Time
	Source                 string
	SourceKey              string
	SourceURL              *string
	ImportedAt             time.Time
}

func (q *Queries) UpsertPricingRule(ctx context.Context, arg UpsertPricingRuleParams) error {
	_, err := q.db.Exec(ctx, upsertPricingRule,
		arg.PricingRuleID,
		arg.Provider,
		arg.Model,
		arg.Meter,
		arg.Conditions,
		arg.UnitPriceNanos,
		arg.UnitQuantity,
		arg.MinimumChargeNanos,
		arg.BillingIncrementMicros,
		arg.EffectiveFrom,
		arg.Source,
		arg.SourceKey,
		arg.SourceURL,
		arg.ImportedAt,
	)
	return err
}
