// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

type Environment string

const (
	EnvironmentTest Environment = "test"
	EnvironmentLive Environment = "live"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type Meter struct {
	Meter       string
	Unit        string
	Description string
}

type PricingOverride struct {
	PricingOverrideID      uuid.UUID
	Environment            Environment
	Provider               string
	Model                  string
	Meter                  string
	Conditions             []byte
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	NativeUnit             *string
	NativeUnitPriceNanos   *money.Amount
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	EffectiveFrom          time.Time
	EffectiveTo            *time.Time
	ImportID               *uuid.UUID
	CreatedAt              time.Time
	UpdatedAt              time.Time
}

type ProviderModelAlias struct {
	Provider string
	Alias    string
	Model    string
}
