// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overrides.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const insertPricingOverride = `-- name: InsertPricingOverride :one
INSERT INTO pricing_overrides (
    pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14::timestamptz,
    $13, $13
)
RETURNING pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
`

type InsertPricingOverrideParams struct {
	PricingOverrideID      uuid.UUID
	Environment            Environment
	Provider               string
	Model                  string
	Meter                  string
	Conditions             []byte
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	NativeUnit             *string
	NativeUnitPriceNanos   *money.Amount
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	CreatedAt              time.Time
	EffectiveTo            *time.Time
}

func (q *Queries) InsertPricingOverride(ctx context.Context, arg InsertPricingOverrideParams) (PricingOverride, error) {
	row := q.db.QueryRow(ctx, insertPricingOverride,
		arg.PricingOverrideID,
		arg.Environment,
		arg.Provider,
		arg.Model,
		arg.Meter,
		arg.Conditions,
		arg.UnitPriceNanos,
		arg.UnitQuantity,
		arg.NativeUnit,
		arg.NativeUnitPriceNanos,
		arg.MinimumChargeNanos,
		arg.BillingIncrementMicros,
		arg.CreatedAt,
		arg.EffectiveTo,
	)
	var i PricingOverride
	err := row.Scan(
		&i.PricingOverrideID,
		&i.Environment,
		&i.Provider,
		&i.Model,
		&i.Meter,
		&i.Conditions,
		&i.UnitPriceNanos,
		&i.UnitQuantity,
		&i.NativeUnit,
		&i.NativeUnitPriceNanos,
		&i.MinimumChargeNanos,
		&i.BillingIncrementMicros,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdjustmentOverrideIDs = `-- name: ListAdjustmentOverrideIDs :many
SELECT pricing_overrides.pricing_override_id
FROM pricing_overrides
WHERE pricing_overrides.pricing_override_id = ANY ($1::uuid[])
    AND EXISTS (
        SELECT 1
        FROM pricing_rules
        WHERE pricing_rules.provider = pricing_overrides.provider
            AND pricing_rules.model = pricing_overrides.model
            AND pricing_rules.meter = pricing_overrides.meter
            AND pricing_rules.conditions = pricing_overrides.conditions
            AND pricing_rules.effective_to IS NULL
    )
`

func (q *Queries) ListAdjustmentOverrideIDs(ctx context.Context, pricingOverrideIds []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAdjustmentOverrideIDs, pricingOverrideIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var pricing_override_id uuid.UUID
		if err := rows.Scan(&pricing_override_id); err != nil {
			return nil, err
		}
		items = append(items, pricing_override_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPricingOverrides = `-- name: ListPricingOverrides :many
SELECT pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
FROM pricing_overrides
WHERE environment = $1
    AND ($2::boolean OR effective_to IS NULL OR effective_to > $3::timestamptz)
    AND (
        $4::timestamptz IS NULL
        OR (created_at, pricing_override_id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY created_at DESC, pricing_override_id DESC
LIMIT $6::bigint
`

type ListPricingOverridesParams struct {
	Environment            Environment
	IncludeEnded           bool
	At                     time.Time
	AfterCreatedAt         *time.Time
	AfterPricingOverrideID *uuid.UUID
	RowLimit               int64
}

func (q *Queries) ListPricingOverrides(ctx context.Context, arg ListPricingOverridesParams) ([]PricingOverride, error) {
	rows, err := q.db.Query(ctx, listPricingOverrides,
		arg.Environment,
		arg.IncludeEnded,
		arg.At,
		arg.AfterCreatedAt,
		arg.AfterPricingOverrideID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PricingOverride
	for rows.Next() {
		var i PricingOverride
		if err := rows.Scan(
			&i.PricingOverrideID,
			&i.Environment,
			&i.Provider,
			&i.Model,
			&i.Meter,
			&i.Conditions,
			&i.UnitPriceNanos,
			&i.UnitQuantity,
			&i.NativeUnit,
			&i.NativeUnitPriceNanos,
			&i.MinimumChargeNanos,
			&i.BillingIncrementMicros,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPricingOverride = `-- name: SelectPricingOverride :one
SELECT pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
FROM pricing_overrides
WHERE environment = $1
    AND pricing_override_id = $2
`

type SelectPricingOverrideParams struct {
	Environment       Environment
	PricingOverrideID uuid.UUID
}

func (q *Queries) SelectPricingOverride(ctx context.Context, arg SelectPricingOverrideParams) (PricingOverride, error) {
	row := q.db.QueryRow(ctx, selectPricingOverride, arg.Environment, arg.PricingOverrideID)
	var i PricingOverride
	err := row.Scan(
		&i.PricingOverrideID,
		&i.Environment,
		&i.Provider,
		&i.Model,
		&i.Meter,
		&i.Conditions,
		&i.UnitPriceNanos,
		&i.UnitQuantity,
		&i.NativeUnit,
		&i.NativeUnitPriceNanos,
		&i.MinimumChargeNanos,
		&i.BillingIncrementMicros,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectPricingOverrideForUpdate = `-- name: SelectPricingOverrideForUpdate :one
SELECT pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
FROM pricing_overrides
WHERE environment = $1
    AND pricing_override_id = $2
FOR UPDATE
`

type SelectPricingOverrideForUpdateParams struct {
	Environment       Environment
	PricingOverrideID uuid.UUID
}

func (q *Queries) SelectPricingOverrideForUpdate(ctx context.Context, arg SelectPricingOverrideForUpdateParams) (PricingOverride, error) {
	row := q.db.QueryRow(ctx, selectPricingOverrideForUpdate, arg.Environment, arg.PricingOverrideID)
	var i PricingOverride
	err := row.Scan(
		&i.PricingOverrideID,
		&i.Environment,
		&i.Provider,
		&i.Model,
		&i.Meter,
		&i.Conditions,
		&i.UnitPriceNanos,
		&i.UnitQuantity,
		&i.NativeUnit,
		&i.NativeUnitPriceNanos,
		&i.MinimumChargeNanos,
		&i.BillingIncrementMicros,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePricingOverride = `-- name: UpdatePricingOverride :one
UPDATE pricing_overrides
SET unit_price_nanos = $1,
    unit_quantity = $2,
    native_unit = $3,
    native_unit_price_nanos = $4,
    minimum_charge_nanos = $5,
    billing_increment_micros = $6,
    effective_to = $7,
    updated_at = $8
WHERE pricing_override_id = $9
RETURNING pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
`

type UpdatePricingOverrideParams struct {
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	NativeUnit             *string
	NativeUnitPriceNanos   *money.Amount
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	EffectiveTo            *time.Time
	UpdatedAt              time.Time
	PricingOverrideID      uuid.UUID
}

func (q *Queries) UpdatePricingOverride(ctx context.Context, arg UpdatePricingOverrideParams) (PricingOverride, error) {
	row := q.db.QueryRow(ctx, updatePricingOverride,
		arg.UnitPriceNanos,
		arg.UnitQuantity,
		arg.NativeUnit,
		arg.NativeUnitPriceNanos,
		arg.MinimumChargeNanos,
		arg.BillingIncrementMicros,
		arg.EffectiveTo,
		arg.UpdatedAt,
		arg.PricingOverrideID,
	)
	var i PricingOverride
	err := row.Scan(
		&i.PricingOverrideID,
		&i.Environment,
		&i.Provider,
		&i.Model,
		&i.Meter,
		&i.Conditions,
		&i.UnitPriceNanos,
		&i.UnitQuantity,
		&i.NativeUnit,
		&i.NativeUnitPriceNanos,
		&i.MinimumChargeNanos,
		&i.BillingIncrementMicros,
		&i.EffectiveFrom,
		&i.EffectiveTo,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
