// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rule_sets.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listProviderModelAliases = `-- name: ListProviderModelAliases :many
SELECT provider, alias, model
FROM provider_model_aliases
`

func (q *Queries) ListProviderModelAliases(ctx context.Context) ([]ProviderModelAlias, error) {
	rows, err := q.db.Query(ctx, listProviderModelAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderModelAlias
	for rows.Next() {
		var i ProviderModelAlias
		if err := rows.Scan(&i.Provider, &i.Alias, &i.Model); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingOverrides = `-- name: ListRatingOverrides :many
SELECT pricing_override_id, environment, provider, model, meter, conditions, unit_price_nanos, unit_quantity, native_unit,
    native_unit_price_nanos, minimum_charge_nanos, billing_increment_micros, effective_from, effective_to, import_id,
    created_at, updated_at
FROM pricing_overrides
WHERE environment = $1
    AND (effective_to IS NULL OR effective_to > $2::timestamptz)
`

type ListRatingOverridesParams struct {
	Environment Environment
	Since       time.Time
}

func (q *Queries) ListRatingOverrides(ctx context.Context, arg ListRatingOverridesParams) ([]PricingOverride, error) {
	rows, err := q.db.Query(ctx, listRatingOverrides, arg.Environment, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PricingOverride
	for rows.Next() {
		var i PricingOverride
		if err := rows.Scan(
			&i.PricingOverrideID,
			&i.Environment,
			&i.Provider,
			&i.Model,
			&i.Meter,
			&i.Conditions,
			&i.UnitPriceNanos,
			&i.UnitQuantity,
			&i.NativeUnit,
			&i.NativeUnitPriceNanos,
			&i.MinimumChargeNanos,
			&i.BillingIncrementMicros,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingRules = `-- name: ListRatingRules :many
SELECT pricing_rule_id, provider, model, meter, conditions, unit_price_nanos, unit_quantity, minimum_charge_nanos,
    billing_increment_micros, effective_from, effective_to, status, source
FROM pricing_rules
WHERE effective_to IS NULL OR effective_to > $1::timestamptz
`

type ListRatingRulesRow struct {
	PricingRuleID          uuid.UUID
	Provider               string
	Model                  string
	Meter                  string
	Conditions             []byte
	UnitPriceNanos         money.Amount
	UnitQuantity           int64
	MinimumChargeNanos     *money.Amount
	BillingIncrementMicros *money.Quantity
	EffectiveFrom          time.Time
	EffectiveTo            *time.Time
	Status                 string
	Source                 string
}

func (q *Queries) ListRatingRules(ctx context.Context, since time.Time) ([]ListRatingRulesRow, error) {
	rows, err := q.db.Query(ctx, listRatingRules, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatingRulesRow
	for rows.Next() {
		var i ListRatingRulesRow
		if err := rows.Scan(
			&i.PricingRuleID,
			&i.Provider,
			&i.Model,
			&i.Meter,
			&i.Conditions,
			&i.UnitPriceNanos,
			&i.UnitQuantity,
			&i.MinimumChargeNanos,
			&i.BillingIncrementMicros,
			&i.EffectiveFrom,
			&i.EffectiveTo,
			&i.Status,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
