// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uncosted.sql

package queries

import (
	"context"
	"time"
)

const listUncostedUsage = `-- name: ListUncostedUsage :many
WITH missing_meters AS (
    SELECT ledger_entries.provider,
        ledger_entries.model,
        cost_lines.line ->> 'meter' AS meter,
        ledger_entries.occurred_at
    FROM ledger_entries
    CROSS JOIN LATERAL jsonb_array_elements(ledger_entries.cost_breakdown -> 'lines') AS cost_lines (line)
    WHERE ledger_entries.environment = $5
        AND ledger_entries.cost_status = 'uncosted'
        AND ledger_entries.occurred_at >= $6::timestamptz
        AND (cost_lines.line ->> 'missing')::boolean
        AND NOT EXISTS (
            SELECT 1
            FROM ledger_entries AS corrections
            WHERE corrections.environment = ledger_entries.environment
                AND corrections.idempotency_key = 'correction:' || ledger_entries.ledger_entry_id::text
        )
)
SELECT missing_meters.provider,
    missing_meters.model,
    missing_meters.meter::text AS meter,
    count(*) AS request_count,
    max(missing_meters.occurred_at)::timestamptz AS last_seen_at
FROM missing_meters
WHERE $1::text IS NULL
    OR (missing_meters.provider COLLATE "C", missing_meters.model COLLATE "C", missing_meters.meter COLLATE "C") > (
        $1::text COLLATE "C",
        $2::text COLLATE "C",
        $3::text COLLATE "C"
    )
GROUP BY missing_meters.provider, missing_meters.model, missing_meters.meter
ORDER BY missing_meters.provider COLLATE "C", missing_meters.model COLLATE "C", missing_meters.meter COLLATE "C"
LIMIT $4::bigint
`

type ListUncostedUsageParams struct {
	AfterProvider *string
	AfterModel    *string
	AfterMeter    *string
	RowLimit      int64
	Environment   Environment
	OccurredSince time.Time
}

type ListUncostedUsageRow struct {
	Provider     string
	Model        string
	Meter        string
	RequestCount int64
	LastSeenAt   time.Time
}

func (q *Queries) ListUncostedUsage(ctx context.Context, arg ListUncostedUsageParams) ([]ListUncostedUsageRow, error) {
	rows, err := q.db.Query(ctx, listUncostedUsage,
		arg.AfterProvider,
		arg.AfterModel,
		arg.AfterMeter,
		arg.RowLimit,
		arg.Environment,
		arg.OccurredSince,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUncostedUsageRow
	for rows.Next() {
		var i ListUncostedUsageRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.Meter,
			&i.RequestCount,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectPricingOverrideDigest = `-- name: SelectPricingOverrideDigest :one
SELECT md5(coalesce(string_agg(row_to_json(pricing_overrides)::text, ',' ORDER BY pricing_override_id), ''))::text AS digest
FROM pricing_overrides
WHERE environment = $1
`

func (q *Queries) SelectPricingOverrideDigest(ctx context.Context, environment Environment) (string, error) {
	row := q.db.QueryRow(ctx, selectPricingOverrideDigest, environment)
	var digest string
	err := row.Scan(&digest)
	return digest, err
}
