// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_state.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listActiveCustomerPlans = `-- name: ListActiveCustomerPlans :many
SELECT customers.customer_id,
    plans.plan_id,
    plans.target_margin_basis_points,
    plans.allowance_nanos,
    coalesce(plans.hold_times, '{}') AS hold_times
FROM customers
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
WHERE customers.environment = $1
    AND customers.status = 'active'
ORDER BY customers.customer_id
`

type ListActiveCustomerPlansRow struct {
	CustomerID              uuid.UUID
	PlanID                  *uuid.UUID
	TargetMarginBasisPoints *money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
}

func (q *Queries) ListActiveCustomerPlans(ctx context.Context, environment Environment) ([]ListActiveCustomerPlansRow, error) {
	rows, err := q.db.Query(ctx, listActiveCustomerPlans, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCustomerPlansRow
	for rows.Next() {
		var i ListActiveCustomerPlansRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.PlanID,
			&i.TargetMarginBasisPoints,
			&i.AllowanceNanos,
			&i.HoldTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerPlans = `-- name: ListCustomerPlans :many
SELECT customers.customer_id,
    plans.plan_id,
    plans.target_margin_basis_points,
    plans.allowance_nanos,
    coalesce(plans.hold_times, '{}') AS hold_times
FROM customers
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
WHERE customers.environment = $1
    AND customers.customer_id = ANY ($2::uuid[])
ORDER BY customers.customer_id
`

type ListCustomerPlansParams struct {
	Environment Environment
	CustomerIds []uuid.UUID
}

type ListCustomerPlansRow struct {
	CustomerID              uuid.UUID
	PlanID                  *uuid.UUID
	TargetMarginBasisPoints *money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
}

func (q *Queries) ListCustomerPlans(ctx context.Context, arg ListCustomerPlansParams) ([]ListCustomerPlansRow, error) {
	rows, err := q.db.Query(ctx, listCustomerPlans, arg.Environment, arg.CustomerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerPlansRow
	for rows.Next() {
		var i ListCustomerPlansRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.PlanID,
			&i.TargetMarginBasisPoints,
			&i.AllowanceNanos,
			&i.HoldTimes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeriodRevenues = `-- name: ListPeriodRevenues :many
SELECT period_rollups.customer_id, period_rollups.period_start, period_rollups.revenue_net_nanos
FROM period_rollups
WHERE period_rollups.environment = $1
    AND (period_rollups.customer_id, period_rollups.period_start) IN (
        SELECT unnest($2::uuid[]), unnest($3::timestamptz[])
    )
`

type ListPeriodRevenuesParams struct {
	Environment  Environment
	CustomerIds  []uuid.UUID
	PeriodStarts []time.Time
}

type ListPeriodRevenuesRow struct {
	CustomerID      uuid.UUID
	PeriodStart     time.Time
	RevenueNetNanos money.Amount
}

func (q *Queries) ListPeriodRevenues(ctx context.Context, arg ListPeriodRevenuesParams) ([]ListPeriodRevenuesRow, error) {
	rows, err := q.db.Query(ctx, listPeriodRevenues, arg.Environment, arg.CustomerIds, arg.PeriodStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeriodRevenuesRow
	for rows.Next() {
		var i ListPeriodRevenuesRow
		if err := rows.Scan(&i.CustomerID, &i.PeriodStart, &i.RevenueNetNanos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionRevenuePeriods = `-- name: ListSubscriptionRevenuePeriods :many
SELECT DISTINCT ON (customer_id) customer_id, period_start, period_end
FROM revenue_entries
WHERE environment = $1
    AND customer_id = ANY ($2::uuid[])
    AND kind = 'subscription'
    AND period_start <= $3
    AND period_end > $3
ORDER BY customer_id, period_start DESC, period_end DESC
`

type ListSubscriptionRevenuePeriodsParams struct {
	Environment Environment
	CustomerIds []uuid.UUID
	Now         time.Time
}

type ListSubscriptionRevenuePeriodsRow struct {
	CustomerID  uuid.UUID
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) ListSubscriptionRevenuePeriods(ctx context.Context, arg ListSubscriptionRevenuePeriodsParams) ([]ListSubscriptionRevenuePeriodsRow, error) {
	rows, err := q.db.Query(ctx, listSubscriptionRevenuePeriods, arg.Environment, arg.CustomerIds, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSubscriptionRevenuePeriodsRow
	for rows.Next() {
		var i ListSubscriptionRevenuePeriodsRow
		if err := rows.Scan(&i.CustomerID, &i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCustomerPlan = `-- name: SelectCustomerPlan :one
SELECT customers.customer_id,
    plans.plan_id,
    plans.target_margin_basis_points,
    plans.allowance_nanos,
    coalesce(plans.hold_times, '{}') AS hold_times
FROM customers
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
WHERE customers.environment = $1
    AND customers.customer_id = $2
`

type SelectCustomerPlanParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

type SelectCustomerPlanRow struct {
	CustomerID              uuid.UUID
	PlanID                  *uuid.UUID
	TargetMarginBasisPoints *money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
}

func (q *Queries) SelectCustomerPlan(ctx context.Context, arg SelectCustomerPlanParams) (SelectCustomerPlanRow, error) {
	row := q.db.QueryRow(ctx, selectCustomerPlan, arg.Environment, arg.CustomerID)
	var i SelectCustomerPlanRow
	err := row.Scan(
		&i.CustomerID,
		&i.PlanID,
		&i.TargetMarginBasisPoints,
		&i.AllowanceNanos,
		&i.HoldTimes,
	)
	return i, err
}

const selectPeriodRevenue = `-- name: SelectPeriodRevenue :one
SELECT revenue_net_nanos
FROM period_rollups
WHERE environment = $1
    AND customer_id = $2
    AND period_start = $3
`

type SelectPeriodRevenueParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	PeriodStart time.Time
}

func (q *Queries) SelectPeriodRevenue(ctx context.Context, arg SelectPeriodRevenueParams) (money.Amount, error) {
	row := q.db.QueryRow(ctx, selectPeriodRevenue, arg.Environment, arg.CustomerID, arg.PeriodStart)
	var revenue_net_nanos money.Amount
	err := row.Scan(&revenue_net_nanos)
	return revenue_net_nanos, err
}

const selectSubscriptionRevenuePeriod = `-- name: SelectSubscriptionRevenuePeriod :one
SELECT period_start, period_end
FROM revenue_entries
WHERE environment = $1
    AND customer_id = $2
    AND kind = 'subscription'
    AND period_start <= $3
    AND period_end > $3
ORDER BY period_start DESC, period_end DESC
LIMIT 1
`

type SelectSubscriptionRevenuePeriodParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	Now         time.Time
}

type SelectSubscriptionRevenuePeriodRow struct {
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) SelectSubscriptionRevenuePeriod(ctx context.Context, arg SelectSubscriptionRevenuePeriodParams) (SelectSubscriptionRevenuePeriodRow, error) {
	row := q.db.QueryRow(ctx, selectSubscriptionRevenuePeriod, arg.Environment, arg.CustomerID, arg.Now)
	var i SelectSubscriptionRevenuePeriodRow
	err := row.Scan(&i.PeriodStart, &i.PeriodEnd)
	return i, err
}
