// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: entries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (
    ledger_entry_id,
    environment,
    customer_id,
    customer_user_id,
    decision_id,
    idempotency_key,
    feature,
    provider,
    model,
    attributes,
    usage,
    cost_nanos,
    cost_breakdown,
    cost_status,
    decision_source,
    period_start,
    period_end,
    correction_of,
    occurred_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
)
ON CONFLICT (environment, idempotency_key) DO NOTHING
RETURNING ledger_entry_id, environment, customer_id, customer_user_id, decision_id, idempotency_key, feature, provider, model,
    attributes, usage, cost_nanos, cost_breakdown, cost_status, decision_source, period_start, period_end, correction_of,
    occurred_at, import_id, created_at
`

type InsertLedgerEntryParams struct {
	LedgerEntryID  uuid.UUID
	Environment    Environment
	CustomerID     uuid.UUID
	CustomerUserID *uuid.UUID
	DecisionID     *uuid.UUID
	IdempotencyKey string
	Feature        string
	Provider       string
	Model          string
	Attributes     []byte
	Usage          []byte
	CostNanos      *int64
	CostBreakdown  []byte
	CostStatus     string
	DecisionSource string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	CorrectionOf   *uuid.UUID
	OccurredAt     time.Time
	CreatedAt      time.Time
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.LedgerEntryID,
		arg.Environment,
		arg.CustomerID,
		arg.CustomerUserID,
		arg.DecisionID,
		arg.IdempotencyKey,
		arg.Feature,
		arg.Provider,
		arg.Model,
		arg.Attributes,
		arg.Usage,
		arg.CostNanos,
		arg.CostBreakdown,
		arg.CostStatus,
		arg.DecisionSource,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.CorrectionOf,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.LedgerEntryID,
		&i.Environment,
		&i.CustomerID,
		&i.CustomerUserID,
		&i.DecisionID,
		&i.IdempotencyKey,
		&i.Feature,
		&i.Provider,
		&i.Model,
		&i.Attributes,
		&i.Usage,
		&i.CostNanos,
		&i.CostBreakdown,
		&i.CostStatus,
		&i.DecisionSource,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CorrectionOf,
		&i.OccurredAt,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}

const selectLedgerEntryByIdempotencyKey = `-- name: SelectLedgerEntryByIdempotencyKey :one
SELECT ledger_entry_id, environment, customer_id, customer_user_id, decision_id, idempotency_key, feature, provider, model,
    attributes, usage, cost_nanos, cost_breakdown, cost_status, decision_source, period_start, period_end, correction_of,
    occurred_at, import_id, created_at
FROM ledger_entries
WHERE environment = $1
    AND idempotency_key = $2
`

type SelectLedgerEntryByIdempotencyKeyParams struct {
	Environment    Environment
	IdempotencyKey string
}

func (q *Queries) SelectLedgerEntryByIdempotencyKey(ctx context.Context, arg SelectLedgerEntryByIdempotencyKeyParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, selectLedgerEntryByIdempotencyKey, arg.Environment, arg.IdempotencyKey)
	var i LedgerEntry
	err := row.Scan(
		&i.LedgerEntryID,
		&i.Environment,
		&i.CustomerID,
		&i.CustomerUserID,
		&i.DecisionID,
		&i.IdempotencyKey,
		&i.Feature,
		&i.Provider,
		&i.Model,
		&i.Attributes,
		&i.Usage,
		&i.CostNanos,
		&i.CostBreakdown,
		&i.CostStatus,
		&i.DecisionSource,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.CorrectionOf,
		&i.OccurredAt,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}
