// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: estimates.sql

package queries

import (
	"context"
	"time"
)

const deleteUsageEstimates = `-- name: DeleteUsageEstimates :exec
DELETE FROM usage_estimates
WHERE environment = $1
`

func (q *Queries) DeleteUsageEstimates(ctx context.Context, environment Environment) error {
	_, err := q.db.Exec(ctx, deleteUsageEstimates, environment)
	return err
}

const insertUsageEstimates = `-- name: InsertUsageEstimates :exec
INSERT INTO usage_estimates (environment, feature, provider, model, meter, p95_quantity_micros, sample_count, refreshed_at)
SELECT ledger_entries.environment,
    ledger_entries.feature,
    ledger_entries.provider,
    ledger_entries.model,
    usage_quantities.meter,
    ceil(percentile_cont(0.95) WITHIN GROUP (ORDER BY usage_quantities.quantity_micros::bigint::double precision))::bigint,
    count(*)::integer,
    $1::timestamptz
FROM ledger_entries
CROSS JOIN LATERAL jsonb_each_text(ledger_entries.usage) AS usage_quantities (meter, quantity_micros)
WHERE ledger_entries.environment = $2
    AND ledger_entries.occurred_at >= $3::timestamptz
    AND ledger_entries.correction_of IS NULL
GROUP BY ledger_entries.environment, ledger_entries.feature, ledger_entries.provider, ledger_entries.model, usage_quantities.meter
HAVING count(*) >= $4::integer
`

type InsertUsageEstimatesParams struct {
	RefreshedAt        time.Time
	Environment        Environment
	Since              time.Time
	MinimumSampleCount int32
}

func (q *Queries) InsertUsageEstimates(ctx context.Context, arg InsertUsageEstimatesParams) error {
	_, err := q.db.Exec(ctx, insertUsageEstimates,
		arg.RefreshedAt,
		arg.Environment,
		arg.Since,
		arg.MinimumSampleCount,
	)
	return err
}
