// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Environment string

const (
	EnvironmentTest Environment = "test"
	EnvironmentLive Environment = "live"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type LedgerEntry struct {
	LedgerEntryID  uuid.UUID
	Environment    Environment
	CustomerID     uuid.UUID
	CustomerUserID *uuid.UUID
	DecisionID     *uuid.UUID
	IdempotencyKey string
	Feature        string
	Provider       string
	Model          string
	Attributes     []byte
	Usage          []byte
	CostNanos      *int64
	CostBreakdown  []byte
	CostStatus     string
	DecisionSource string
	PeriodStart    time.Time
	PeriodEnd      time.Time
	CorrectionOf   *uuid.UUID
	OccurredAt     time.Time
	ImportID       *uuid.UUID
	CreatedAt      time.Time
}
