// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rerate.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listUncorrectedUncostedEntries = `-- name: ListUncorrectedUncostedEntries :many
SELECT ledger_entries.ledger_entry_id, ledger_entries.environment, ledger_entries.customer_id, ledger_entries.customer_user_id, ledger_entries.decision_id, ledger_entries.idempotency_key, ledger_entries.feature, ledger_entries.provider, ledger_entries.model, ledger_entries.attributes, ledger_entries.usage, ledger_entries.cost_nanos, ledger_entries.cost_breakdown, ledger_entries.cost_status, ledger_entries.decision_source, ledger_entries.period_start, ledger_entries.period_end, ledger_entries.correction_of, ledger_entries.occurred_at, ledger_entries.import_id, ledger_entries.created_at
FROM ledger_entries
WHERE ledger_entries.environment = $1
    AND ledger_entries.cost_status = 'uncosted'
    AND ledger_entries.occurred_at >= $2::timestamptz
    AND ledger_entries.ledger_entry_id > $3::uuid
    AND NOT EXISTS (
        SELECT 1
        FROM ledger_entries AS corrections
        WHERE corrections.environment = ledger_entries.environment
            AND corrections.idempotency_key = 'correction:' || ledger_entries.ledger_entry_id::text
    )
ORDER BY ledger_entries.ledger_entry_id
LIMIT $4::bigint
`

type ListUncorrectedUncostedEntriesParams struct {
	Environment        Environment
	OccurredSince      time.Time
	AfterLedgerEntryID uuid.UUID
	BatchSize          int64
}

type ListUncorrectedUncostedEntriesRow struct {
	LedgerEntry LedgerEntry
}

func (q *Queries) ListUncorrectedUncostedEntries(ctx context.Context, arg ListUncorrectedUncostedEntriesParams) ([]ListUncorrectedUncostedEntriesRow, error) {
	rows, err := q.db.Query(ctx, listUncorrectedUncostedEntries,
		arg.Environment,
		arg.OccurredSince,
		arg.AfterLedgerEntryID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUncorrectedUncostedEntriesRow
	for rows.Next() {
		var i ListUncorrectedUncostedEntriesRow
		if err := rows.Scan(
			&i.LedgerEntry.LedgerEntryID,
			&i.LedgerEntry.Environment,
			&i.LedgerEntry.CustomerID,
			&i.LedgerEntry.CustomerUserID,
			&i.LedgerEntry.DecisionID,
			&i.LedgerEntry.IdempotencyKey,
			&i.LedgerEntry.Feature,
			&i.LedgerEntry.Provider,
			&i.LedgerEntry.Model,
			&i.LedgerEntry.Attributes,
			&i.LedgerEntry.Usage,
			&i.LedgerEntry.CostNanos,
			&i.LedgerEntry.CostBreakdown,
			&i.LedgerEntry.CostStatus,
			&i.LedgerEntry.DecisionSource,
			&i.LedgerEntry.PeriodStart,
			&i.LedgerEntry.PeriodEnd,
			&i.LedgerEntry.CorrectionOf,
			&i.LedgerEntry.OccurredAt,
			&i.LedgerEntry.ImportID,
			&i.LedgerEntry.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
