// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rollups.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const countDecisionsByPeriod = `-- name: CountDecisionsByPeriod :many
SELECT period_start,
    max(period_end)::timestamptz AS period_end,
    count(*) FILTER (WHERE outcome = 'allow') AS allow_count,
    count(*) FILTER (WHERE outcome = 'route') AS route_count,
    count(*) FILTER (WHERE outcome = 'cap') AS cap_count,
    count(*) FILTER (WHERE outcome = 'deny') AS deny_count
FROM decisions
WHERE environment = $1
    AND customer_id = $2
    AND period_start = ANY ($3::timestamptz[])
GROUP BY period_start
`

type CountDecisionsByPeriodParams struct {
	Environment  Environment
	CustomerID   uuid.UUID
	PeriodStarts []time.Time
}

type CountDecisionsByPeriodRow struct {
	PeriodStart time.Time
	PeriodEnd   time.Time
	AllowCount  int64
	RouteCount  int64
	CapCount    int64
	DenyCount   int64
}

func (q *Queries) CountDecisionsByPeriod(ctx context.Context, arg CountDecisionsByPeriodParams) ([]CountDecisionsByPeriodRow, error) {
	rows, err := q.db.Query(ctx, countDecisionsByPeriod, arg.Environment, arg.CustomerID, arg.PeriodStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountDecisionsByPeriodRow
	for rows.Next() {
		var i CountDecisionsByPeriodRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.AllowCount,
			&i.RouteCount,
			&i.CapCount,
			&i.DenyCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordedBillingPeriods = `-- name: ListRecordedBillingPeriods :many
SELECT recorded_periods.period_start, max(recorded_periods.period_end)::timestamptz AS period_end
FROM (
    SELECT revenue_entries.period_start, revenue_entries.period_end
    FROM revenue_entries
    WHERE revenue_entries.environment = $1
        AND revenue_entries.customer_id = $2
        AND revenue_entries.kind = 'subscription'
        AND revenue_entries.period_end > revenue_entries.period_start
    UNION ALL
    SELECT period_rollups.period_start, period_rollups.period_end
    FROM period_rollups
    WHERE period_rollups.environment = $1
        AND period_rollups.customer_id = $2
) AS recorded_periods
GROUP BY recorded_periods.period_start
`

type ListRecordedBillingPeriodsParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

type ListRecordedBillingPeriodsRow struct {
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) ListRecordedBillingPeriods(ctx context.Context, arg ListRecordedBillingPeriodsParams) ([]ListRecordedBillingPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listRecordedBillingPeriods, arg.Environment, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecordedBillingPeriodsRow
	for rows.Next() {
		var i ListRecordedBillingPeriodsRow
		if err := rows.Scan(&i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRevenueEntriesStartingWithin = `-- name: ListRevenueEntriesStartingWithin :many
SELECT period_start, kind, amount_nanos
FROM revenue_entries
WHERE environment = $1
    AND customer_id = $2
    AND period_start >= $3::timestamptz
    AND period_start < $4::timestamptz
`

type ListRevenueEntriesStartingWithinParams struct {
	Environment   Environment
	CustomerID    uuid.UUID
	EarliestStart time.Time
	LatestEnd     time.Time
}

type ListRevenueEntriesStartingWithinRow struct {
	PeriodStart time.Time
	Kind        string
	AmountNanos money.Amount
}

func (q *Queries) ListRevenueEntriesStartingWithin(ctx context.Context, arg ListRevenueEntriesStartingWithinParams) ([]ListRevenueEntriesStartingWithinRow, error) {
	rows, err := q.db.Query(ctx, listRevenueEntriesStartingWithin,
		arg.Environment,
		arg.CustomerID,
		arg.EarliestStart,
		arg.LatestEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevenueEntriesStartingWithinRow
	for rows.Next() {
		var i ListRevenueEntriesStartingWithinRow
		if err := rows.Scan(&i.PeriodStart, &i.Kind, &i.AmountNanos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRollupCustomer = `-- name: LockRollupCustomer :one
SELECT customer_id
FROM customers
WHERE environment = $1
    AND customer_id = $2
FOR NO KEY UPDATE
`

type LockRollupCustomerParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

func (q *Queries) LockRollupCustomer(ctx context.Context, arg LockRollupCustomerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockRollupCustomer, arg.Environment, arg.CustomerID)
	var customer_id uuid.UUID
	err := row.Scan(&customer_id)
	return customer_id, err
}

const sumLedgerEntriesByPeriod = `-- name: SumLedgerEntriesByPeriod :many
WITH period_entries AS (
    SELECT ledger_entry_id, period_start, period_end, cost_nanos, cost_status, correction_of
    FROM ledger_entries
    WHERE environment = $1
        AND customer_id = $2
        AND period_start = ANY ($3::timestamptz[])
),
corrected_entries AS (
    SELECT DISTINCT correction_of
    FROM period_entries
    WHERE correction_of IS NOT NULL
)
SELECT period_entries.period_start,
    max(period_entries.period_end)::timestamptz AS period_end,
    coalesce(sum(period_entries.cost_nanos), 0)::bigint AS cost_nanos,
    (count(*) FILTER (
        WHERE period_entries.cost_status = 'uncosted' AND corrected_entries.correction_of IS NULL
    ))::integer AS uncosted_count
FROM period_entries
LEFT JOIN corrected_entries ON corrected_entries.correction_of = period_entries.ledger_entry_id
GROUP BY period_entries.period_start
`

type SumLedgerEntriesByPeriodParams struct {
	Environment  Environment
	CustomerID   uuid.UUID
	PeriodStarts []time.Time
}

type SumLedgerEntriesByPeriodRow struct {
	PeriodStart   time.Time
	PeriodEnd     time.Time
	CostNanos     int64
	UncostedCount int32
}

func (q *Queries) SumLedgerEntriesByPeriod(ctx context.Context, arg SumLedgerEntriesByPeriodParams) ([]SumLedgerEntriesByPeriodRow, error) {
	rows, err := q.db.Query(ctx, sumLedgerEntriesByPeriod, arg.Environment, arg.CustomerID, arg.PeriodStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SumLedgerEntriesByPeriodRow
	for rows.Next() {
		var i SumLedgerEntriesByPeriodRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.CostNanos,
			&i.UncostedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPeriodRollup = `-- name: UpsertPeriodRollup :exec
INSERT INTO period_rollups (
    environment, customer_id, period_start, period_end, revenue_net_nanos, cost_nanos, uncosted_count, decision_counts, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, now()
)
ON CONFLICT (environment, customer_id, period_start) DO UPDATE
SET period_end = EXCLUDED.period_end,
    revenue_net_nanos = EXCLUDED.revenue_net_nanos,
    cost_nanos = EXCLUDED.cost_nanos,
    uncosted_count = EXCLUDED.uncosted_count,
    decision_counts = EXCLUDED.decision_counts,
    updated_at = EXCLUDED.updated_at
`

type UpsertPeriodRollupParams struct {
	Environment     Environment
	CustomerID      uuid.UUID
	PeriodStart     time.Time
	PeriodEnd       time.Time
	RevenueNetNanos money.Amount
	CostNanos       money.Amount
	UncostedCount   int32
	DecisionCounts  []byte
}

func (q *Queries) UpsertPeriodRollup(ctx context.Context, arg UpsertPeriodRollupParams) error {
	_, err := q.db.Exec(ctx, upsertPeriodRollup,
		arg.Environment,
		arg.CustomerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.RevenueNetNanos,
		arg.CostNanos,
		arg.UncostedCount,
		arg.DecisionCounts,
	)
	return err
}
