// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listFeatureSources = `-- name: ListFeatureSources :many
SELECT usage_estimates.feature, 'usage_estimates'::text AS source
FROM usage_estimates
WHERE usage_estimates.environment = $1
UNION
SELECT policies.feature, 'policies'::text
FROM policies
WHERE policies.environment = $1
    AND policies.status = 'active'
    AND policies.feature IS NOT NULL
UNION
SELECT jsonb_object_keys(plans.hold_times), 'plan_hold_times'::text
FROM plans
WHERE plans.environment = $1
    AND plans.status = 'active'
UNION
SELECT decisions.feature, 'decisions'::text
FROM decisions
WHERE decisions.environment = $1
    AND decisions.created_at >= $2
ORDER BY feature, source
`

type ListFeatureSourcesParams struct {
	Environment Environment
	Since       time.Time
}

type ListFeatureSourcesRow struct {
	Feature string
	Source  string
}

func (q *Queries) ListFeatureSources(ctx context.Context, arg ListFeatureSourcesParams) ([]ListFeatureSourcesRow, error) {
	rows, err := q.db.Query(ctx, listFeatureSources, arg.Environment, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureSourcesRow
	for rows.Next() {
		var i ListFeatureSourcesRow
		if err := rows.Scan(&i.Feature, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntryEvents = `-- name: ListLedgerEntryEvents :many
SELECT entries.ledger_entry_id,
    entries.customer_id,
    customers.external_id,
    customers.display_name,
    entries.decision_id,
    entries.feature,
    entries.provider,
    entries.model,
    entries.cost_nanos,
    entries.occurred_at
FROM ledger_entries AS entries
JOIN customers ON customers.customer_id = entries.customer_id
WHERE entries.environment = $1
    AND (
        $2::timestamptz IS NULL
        OR (entries.occurred_at, entries.ledger_entry_id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY entries.occurred_at DESC, entries.ledger_entry_id DESC
LIMIT $4::bigint
`

type ListLedgerEntryEventsParams struct {
	Environment         Environment
	BeforeOccurredAt    *time.Time
	BeforeLedgerEntryID *uuid.UUID
	RowLimit            int64
}

type ListLedgerEntryEventsRow struct {
	LedgerEntryID uuid.UUID
	CustomerID    uuid.UUID
	ExternalID    string
	DisplayName   *string
	DecisionID    *uuid.UUID
	Feature       string
	Provider      string
	Model         string
	CostNanos     *money.Amount
	OccurredAt    time.Time
}

func (q *Queries) ListLedgerEntryEvents(ctx context.Context, arg ListLedgerEntryEventsParams) ([]ListLedgerEntryEventsRow, error) {
	rows, err := q.db.Query(ctx, listLedgerEntryEvents,
		arg.Environment,
		arg.BeforeOccurredAt,
		arg.BeforeLedgerEntryID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLedgerEntryEventsRow
	for rows.Next() {
		var i ListLedgerEntryEventsRow
		if err := rows.Scan(
			&i.LedgerEntryID,
			&i.CustomerID,
			&i.ExternalID,
			&i.DisplayName,
			&i.DecisionID,
			&i.Feature,
			&i.Provider,
			&i.Model,
			&i.CostNanos,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectFirstDecisionCreatedAt = `-- name: SelectFirstDecisionCreatedAt :one
SELECT created_at
FROM decisions
WHERE environment = $1
ORDER BY created_at
LIMIT 1
`

func (q *Queries) SelectFirstDecisionCreatedAt(ctx context.Context, environment Environment) (time.Time, error) {
	row := q.db.QueryRow(ctx, selectFirstDecisionCreatedAt, environment)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const selectOnboardingFlags = `-- name: SelectOnboardingFlags :one
SELECT EXISTS (
        SELECT 1
        FROM api_keys
        WHERE api_keys.environment = $1
            AND api_keys.status = 'active'
    ) AS has_api_key,
    EXISTS (
        SELECT 1
        FROM plans
        WHERE plans.environment = $1
            AND plans.status = 'active'
    ) AS has_plan,
    EXISTS (
        SELECT 1
        FROM policies
        WHERE policies.environment = $1
            AND policies.status = 'active'
    ) AS has_policy,
    EXISTS (
        SELECT 1
        FROM revenue_entries
        WHERE revenue_entries.environment = $1
    ) AS has_revenue
`

type SelectOnboardingFlagsRow struct {
	HasApiKey  bool
	HasPlan    bool
	HasPolicy  bool
	HasRevenue bool
}

func (q *Queries) SelectOnboardingFlags(ctx context.Context, environment Environment) (SelectOnboardingFlagsRow, error) {
	row := q.db.QueryRow(ctx, selectOnboardingFlags, environment)
	var i SelectOnboardingFlagsRow
	err := row.Scan(
		&i.HasApiKey,
		&i.HasPlan,
		&i.HasPolicy,
		&i.HasRevenue,
	)
	return i, err
}
