// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const countActiveCustomers = `-- name: CountActiveCustomers :one
SELECT count(*)
FROM customers
WHERE environment = $1
    AND status = 'active'
`

func (q *Queries) CountActiveCustomers(ctx context.Context, environment Environment) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCustomers, environment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listActiveCustomers = `-- name: ListActiveCustomers :many
SELECT customer_id, external_id, display_name
FROM customers
WHERE environment = $1
    AND status = 'active'
`

type ListActiveCustomersRow struct {
	CustomerID  uuid.UUID
	ExternalID  string
	DisplayName *string
}

func (q *Queries) ListActiveCustomers(ctx context.Context, environment Environment) ([]ListActiveCustomersRow, error) {
	rows, err := q.db.Query(ctx, listActiveCustomers, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCustomersRow
	for rows.Next() {
		var i ListActiveCustomersRow
		if err := rows.Scan(&i.CustomerID, &i.ExternalID, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerPeriodUsage = `-- name: ListCustomerPeriodUsage :many
SELECT entries.feature,
    entries.provider,
    entries.model,
    (count(*) FILTER (WHERE entries.correction_of IS NULL))::bigint AS request_count,
    coalesce(sum(entries.cost_nanos), 0)::bigint AS cost_nanos,
    (count(*) FILTER (
        WHERE entries.cost_status = 'uncosted'
            AND NOT EXISTS (
                SELECT 1
                FROM ledger_entries AS corrections
                WHERE corrections.environment = entries.environment
                    AND corrections.customer_id = entries.customer_id
                    AND corrections.period_start = entries.period_start
                    AND corrections.correction_of = entries.ledger_entry_id
            )
    ))::bigint AS uncosted_count
FROM ledger_entries AS entries
WHERE entries.environment = $1
    AND entries.customer_id = $2
    AND entries.period_start = $3
GROUP BY entries.feature, entries.provider, entries.model
ORDER BY cost_nanos DESC, entries.feature, entries.provider, entries.model
`

type ListCustomerPeriodUsageParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	PeriodStart time.Time
}

type ListCustomerPeriodUsageRow struct {
	Feature       string
	Provider      string
	Model         string
	RequestCount  int64
	CostNanos     int64
	UncostedCount int64
}

func (q *Queries) ListCustomerPeriodUsage(ctx context.Context, arg ListCustomerPeriodUsageParams) ([]ListCustomerPeriodUsageRow, error) {
	rows, err := q.db.Query(ctx, listCustomerPeriodUsage, arg.Environment, arg.CustomerID, arg.PeriodStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerPeriodUsageRow
	for rows.Next() {
		var i ListCustomerPeriodUsageRow
		if err := rows.Scan(
			&i.Feature,
			&i.Provider,
			&i.Model,
			&i.RequestCount,
			&i.CostNanos,
			&i.UncostedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerRollups = `-- name: ListCustomerRollups :many
SELECT period_start, period_end, revenue_net_nanos, cost_nanos, uncosted_count, decision_counts
FROM period_rollups
WHERE environment = $1
    AND customer_id = $2
ORDER BY period_start DESC
`

type ListCustomerRollupsParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

type ListCustomerRollupsRow struct {
	PeriodStart     time.Time
	PeriodEnd       time.Time
	RevenueNetNanos money.Amount
	CostNanos       money.Amount
	UncostedCount   int32
	DecisionCounts  []byte
}

func (q *Queries) ListCustomerRollups(ctx context.Context, arg ListCustomerRollupsParams) ([]ListCustomerRollupsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerRollups, arg.Environment, arg.CustomerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerRollupsRow
	for rows.Next() {
		var i ListCustomerRollupsRow
		if err := rows.Scan(
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RevenueNetNanos,
			&i.CostNanos,
			&i.UncostedCount,
			&i.DecisionCounts,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentCustomerDecisions = `-- name: ListRecentCustomerDecisions :many
SELECT decision_id,
    feature,
    requested_provider,
    requested_model,
    provider,
    model,
    outcome,
    reason,
    matched_policy_id,
    estimated_cost_nanos,
    status,
    created_at
FROM decisions
WHERE environment = $1
    AND customer_id = $2
ORDER BY created_at DESC, decision_id DESC
LIMIT $3::bigint
`

type ListRecentCustomerDecisionsParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	RowLimit    int64
}

type ListRecentCustomerDecisionsRow struct {
	DecisionID         uuid.UUID
	Feature            string
	RequestedProvider  string
	RequestedModel     string
	Provider           string
	Model              string
	Outcome            string
	Reason             string
	MatchedPolicyID    *uuid.UUID
	EstimatedCostNanos *money.Amount
	Status             string
	CreatedAt          time.Time
}

func (q *Queries) ListRecentCustomerDecisions(ctx context.Context, arg ListRecentCustomerDecisionsParams) ([]ListRecentCustomerDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listRecentCustomerDecisions, arg.Environment, arg.CustomerID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentCustomerDecisionsRow
	for rows.Next() {
		var i ListRecentCustomerDecisionsRow
		if err := rows.Scan(
			&i.DecisionID,
			&i.Feature,
			&i.RequestedProvider,
			&i.RequestedModel,
			&i.Provider,
			&i.Model,
			&i.Outcome,
			&i.Reason,
			&i.MatchedPolicyID,
			&i.EstimatedCostNanos,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectCustomer = `-- name: SelectCustomer :one
SELECT customer_id, external_id, display_name, status, created_at
FROM customers
WHERE environment = $1
    AND customer_id = $2
`

type SelectCustomerParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

type SelectCustomerRow struct {
	CustomerID  uuid.UUID
	ExternalID  string
	DisplayName *string
	Status      RecordStatus
	CreatedAt   time.Time
}

func (q *Queries) SelectCustomer(ctx context.Context, arg SelectCustomerParams) (SelectCustomerRow, error) {
	row := q.db.QueryRow(ctx, selectCustomer, arg.Environment, arg.CustomerID)
	var i SelectCustomerRow
	err := row.Scan(
		&i.CustomerID,
		&i.ExternalID,
		&i.DisplayName,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
