// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listDecisionLedgerEntries = `-- name: ListDecisionLedgerEntries :many
SELECT entries.ledger_entry_id,
    entries.provider,
    entries.model,
    entries.usage,
    entries.cost_nanos,
    entries.cost_status,
    entries.correction_of,
    entries.occurred_at,
    entries.created_at
FROM ledger_entries AS entries
WHERE entries.environment = $1
    AND entries.customer_id = $2
    AND entries.period_start = $3
    AND (
        entries.decision_id = $4::uuid
        OR entries.correction_of IN (
            SELECT reported.ledger_entry_id
            FROM ledger_entries AS reported
            WHERE reported.environment = $1
                AND reported.customer_id = $2
                AND reported.period_start = $3
                AND reported.decision_id = $4::uuid
        )
    )
ORDER BY entries.created_at, entries.ledger_entry_id
`

type ListDecisionLedgerEntriesParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	PeriodStart time.Time
	DecisionID  uuid.UUID
}

type ListDecisionLedgerEntriesRow struct {
	LedgerEntryID uuid.UUID
	Provider      string
	Model         string
	Usage         []byte
	CostNanos     *money.Amount
	CostStatus    string
	CorrectionOf  *uuid.UUID
	OccurredAt    time.Time
	CreatedAt     time.Time
}

func (q *Queries) ListDecisionLedgerEntries(ctx context.Context, arg ListDecisionLedgerEntriesParams) ([]ListDecisionLedgerEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDecisionLedgerEntries,
		arg.Environment,
		arg.CustomerID,
		arg.PeriodStart,
		arg.DecisionID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionLedgerEntriesRow
	for rows.Next() {
		var i ListDecisionLedgerEntriesRow
		if err := rows.Scan(
			&i.LedgerEntryID,
			&i.Provider,
			&i.Model,
			&i.Usage,
			&i.CostNanos,
			&i.CostStatus,
			&i.CorrectionOf,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT decisions.decision_id, decisions.environment, decisions.customer_id, decisions.customer_user_id, decisions.feature, decisions.requested_provider, decisions.requested_model, decisions.provider, decisions.model, decisions.attributes, decisions.overrides, decisions.outcome, decisions.reason, decisions.matched_policy_id, decisions.matched_policy_version, decisions.signals, decisions.requested_estimated_cost_nanos, decisions.estimated_cost_nanos, decisions.reserved_nanos, decisions.estimate_basis, decisions.status, decisions.period_start, decisions.period_end, decisions.expires_at, decisions.settled_at, decisions.import_id, decisions.created_at,
    customers.external_id,
    customers.display_name
FROM decisions
JOIN customers ON customers.customer_id = decisions.customer_id
WHERE decisions.environment = $1
    AND ($2::text IS NULL OR decisions.outcome = $2::text)
    AND ($3::uuid IS NULL OR decisions.customer_id = $3::uuid)
    AND ($4::text IS NULL OR decisions.feature = $4::text)
    AND ($5::uuid IS NULL OR decisions.matched_policy_id = $5::uuid)
    AND (
        $6::timestamptz IS NULL
        OR (decisions.created_at, decisions.decision_id) < ($6::timestamptz, $7::uuid)
    )
ORDER BY decisions.created_at DESC, decisions.decision_id DESC
LIMIT $8::bigint
`

type ListDecisionsParams struct {
	Environment      Environment
	Outcome          *string
	CustomerID       *uuid.UUID
	Feature          *string
	PolicyID         *uuid.UUID
	BeforeCreatedAt  *time.Time
	BeforeDecisionID *uuid.UUID
	RowLimit         int64
}

type ListDecisionsRow struct {
	Decision    Decision
	ExternalID  string
	DisplayName *string
}

func (q *Queries) ListDecisions(ctx context.Context, arg ListDecisionsParams) ([]ListDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listDecisions,
		arg.Environment,
		arg.Outcome,
		arg.CustomerID,
		arg.Feature,
		arg.PolicyID,
		arg.BeforeCreatedAt,
		arg.BeforeDecisionID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDecisionsRow
	for rows.Next() {
		var i ListDecisionsRow
		if err := rows.Scan(
			&i.Decision.DecisionID,
			&i.Decision.Environment,
			&i.Decision.CustomerID,
			&i.Decision.CustomerUserID,
			&i.Decision.Feature,
			&i.Decision.RequestedProvider,
			&i.Decision.RequestedModel,
			&i.Decision.Provider,
			&i.Decision.Model,
			&i.Decision.Attributes,
			&i.Decision.Overrides,
			&i.Decision.Outcome,
			&i.Decision.Reason,
			&i.Decision.MatchedPolicyID,
			&i.Decision.MatchedPolicyVersion,
			&i.Decision.Signals,
			&i.Decision.RequestedEstimatedCostNanos,
			&i.Decision.EstimatedCostNanos,
			&i.Decision.ReservedNanos,
			&i.Decision.EstimateBasis,
			&i.Decision.Status,
			&i.Decision.PeriodStart,
			&i.Decision.PeriodEnd,
			&i.Decision.ExpiresAt,
			&i.Decision.SettledAt,
			&i.Decision.ImportID,
			&i.Decision.CreatedAt,
			&i.ExternalID,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDecision = `-- name: SelectDecision :one
SELECT decisions.decision_id, decisions.environment, decisions.customer_id, decisions.customer_user_id, decisions.feature, decisions.requested_provider, decisions.requested_model, decisions.provider, decisions.model, decisions.attributes, decisions.overrides, decisions.outcome, decisions.reason, decisions.matched_policy_id, decisions.matched_policy_version, decisions.signals, decisions.requested_estimated_cost_nanos, decisions.estimated_cost_nanos, decisions.reserved_nanos, decisions.estimate_basis, decisions.status, decisions.period_start, decisions.period_end, decisions.expires_at, decisions.settled_at, decisions.import_id, decisions.created_at,
    customers.external_id,
    customers.display_name,
    customer_users.external_id AS customer_user_external_id
FROM decisions
JOIN customers ON customers.customer_id = decisions.customer_id
LEFT JOIN customer_users ON customer_users.customer_user_id = decisions.customer_user_id
WHERE decisions.environment = $1
    AND decisions.decision_id = $2
`

type SelectDecisionParams struct {
	Environment Environment
	DecisionID  uuid.UUID
}

type SelectDecisionRow struct {
	Decision               Decision
	ExternalID             string
	DisplayName            *string
	CustomerUserExternalID *string
}

func (q *Queries) SelectDecision(ctx context.Context, arg SelectDecisionParams) (SelectDecisionRow, error) {
	row := q.db.QueryRow(ctx, selectDecision, arg.Environment, arg.DecisionID)
	var i SelectDecisionRow
	err := row.Scan(
		&i.Decision.DecisionID,
		&i.Decision.Environment,
		&i.Decision.CustomerID,
		&i.Decision.CustomerUserID,
		&i.Decision.Feature,
		&i.Decision.RequestedProvider,
		&i.Decision.RequestedModel,
		&i.Decision.Provider,
		&i.Decision.Model,
		&i.Decision.Attributes,
		&i.Decision.Overrides,
		&i.Decision.Outcome,
		&i.Decision.Reason,
		&i.Decision.MatchedPolicyID,
		&i.Decision.MatchedPolicyVersion,
		&i.Decision.Signals,
		&i.Decision.RequestedEstimatedCostNanos,
		&i.Decision.EstimatedCostNanos,
		&i.Decision.ReservedNanos,
		&i.Decision.EstimateBasis,
		&i.Decision.Status,
		&i.Decision.PeriodStart,
		&i.Decision.PeriodEnd,
		&i.Decision.ExpiresAt,
		&i.Decision.SettledAt,
		&i.Decision.ImportID,
		&i.Decision.CreatedAt,
		&i.ExternalID,
		&i.DisplayName,
		&i.CustomerUserExternalID,
	)
	return i, err
}
