// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overview.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listCurrentPeriodTotals = `-- name: ListCurrentPeriodTotals :many
SELECT DISTINCT ON (period_rollups.customer_id) period_rollups.customer_id,
    customers.external_id,
    customers.display_name,
    plans.plan_id,
    period_rollups.period_start,
    period_rollups.period_end,
    period_rollups.revenue_net_nanos,
    period_rollups.cost_nanos,
    period_rollups.uncosted_count
FROM period_rollups
JOIN customers ON customers.customer_id = period_rollups.customer_id
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
WHERE period_rollups.environment = $1
    AND period_rollups.period_start <= $2
    AND period_rollups.period_end > $2
ORDER BY period_rollups.customer_id, period_rollups.period_start DESC
`

type ListCurrentPeriodTotalsParams struct {
	Environment Environment
	Now         time.Time
}

type ListCurrentPeriodTotalsRow struct {
	CustomerID      uuid.UUID
	ExternalID      string
	DisplayName     *string
	PlanID          *uuid.UUID
	PeriodStart     time.Time
	PeriodEnd       time.Time
	RevenueNetNanos money.Amount
	CostNanos       money.Amount
	UncostedCount   int32
}

func (q *Queries) ListCurrentPeriodTotals(ctx context.Context, arg ListCurrentPeriodTotalsParams) ([]ListCurrentPeriodTotalsRow, error) {
	rows, err := q.db.Query(ctx, listCurrentPeriodTotals, arg.Environment, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentPeriodTotalsRow
	for rows.Next() {
		var i ListCurrentPeriodTotalsRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.ExternalID,
			&i.DisplayName,
			&i.PlanID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RevenueNetNanos,
			&i.CostNanos,
			&i.UncostedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerTotalsBetween = `-- name: ListCustomerTotalsBetween :many
WITH revenue_totals AS (
    SELECT revenue_entries.customer_id,
        sum(
            CASE WHEN revenue_entries.kind IN ('subscription', 'adjustment') THEN revenue_entries.amount_nanos
            ELSE -revenue_entries.amount_nanos END
        ) AS revenue_net_nanos
    FROM revenue_entries
    WHERE revenue_entries.environment = $1
        AND revenue_entries.occurred_at >= $2
        AND revenue_entries.occurred_at < $3
    GROUP BY revenue_entries.customer_id
),
ledger_totals AS (
    SELECT entries.customer_id,
        sum(entries.cost_nanos) AS cost_nanos,
        count(*) FILTER (
            WHERE entries.cost_status = 'uncosted'
                AND NOT EXISTS (
                    SELECT 1
                    FROM ledger_entries AS corrections
                    WHERE corrections.environment = entries.environment
                        AND corrections.customer_id = entries.customer_id
                        AND corrections.period_start = entries.period_start
                        AND corrections.correction_of = entries.ledger_entry_id
                )
        ) AS uncosted_count
    FROM ledger_entries AS entries
    WHERE entries.environment = $1
        AND entries.occurred_at >= $2
        AND entries.occurred_at < $3
    GROUP BY entries.customer_id
),
window_customers AS (
    SELECT revenue_totals.customer_id FROM revenue_totals
    UNION
    SELECT ledger_totals.customer_id FROM ledger_totals
)
SELECT customers.customer_id,
    customers.external_id,
    customers.display_name,
    plans.plan_id,
    coalesce(revenue_totals.revenue_net_nanos, 0)::bigint AS revenue_net_nanos,
    coalesce(ledger_totals.cost_nanos, 0)::bigint AS cost_nanos,
    coalesce(ledger_totals.uncosted_count, 0)::integer AS uncosted_count
FROM window_customers
JOIN customers ON customers.customer_id = window_customers.customer_id
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
LEFT JOIN revenue_totals ON revenue_totals.customer_id = window_customers.customer_id
LEFT JOIN ledger_totals ON ledger_totals.customer_id = window_customers.customer_id
ORDER BY customers.customer_id
`

type ListCustomerTotalsBetweenParams struct {
	Environment Environment
	WindowStart time.Time
	WindowEnd   time.Time
}

type ListCustomerTotalsBetweenRow struct {
	CustomerID      uuid.UUID
	ExternalID      string
	DisplayName     *string
	PlanID          *uuid.UUID
	RevenueNetNanos int64
	CostNanos       int64
	UncostedCount   int32
}

func (q *Queries) ListCustomerTotalsBetween(ctx context.Context, arg ListCustomerTotalsBetweenParams) ([]ListCustomerTotalsBetweenRow, error) {
	rows, err := q.db.Query(ctx, listCustomerTotalsBetween, arg.Environment, arg.WindowStart, arg.WindowEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCustomerTotalsBetweenRow
	for rows.Next() {
		var i ListCustomerTotalsBetweenRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.ExternalID,
			&i.DisplayName,
			&i.PlanID,
			&i.RevenueNetNanos,
			&i.CostNanos,
			&i.UncostedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyTotals = `-- name: ListDailyTotals :many
SELECT daily_rows.day::timestamptz AS day,
    sum(daily_rows.revenue_net_nanos)::bigint AS revenue_net_nanos,
    sum(daily_rows.cost_nanos)::bigint AS cost_nanos
FROM (
    SELECT date_trunc('day', revenue_entries.occurred_at, 'UTC') AS day,
        CASE WHEN revenue_entries.kind IN ('subscription', 'adjustment') THEN revenue_entries.amount_nanos
        ELSE -revenue_entries.amount_nanos END AS revenue_net_nanos,
        0::bigint AS cost_nanos
    FROM revenue_entries
    WHERE revenue_entries.environment = $1
        AND revenue_entries.occurred_at >= $2
        AND revenue_entries.occurred_at < $3
    UNION ALL
    SELECT date_trunc('day', ledger_entries.occurred_at, 'UTC') AS day,
        0::bigint AS revenue_net_nanos,
        coalesce(ledger_entries.cost_nanos, 0) AS cost_nanos
    FROM ledger_entries
    WHERE ledger_entries.environment = $1
        AND ledger_entries.occurred_at >= $2
        AND ledger_entries.occurred_at < $3
) AS daily_rows
GROUP BY daily_rows.day
ORDER BY daily_rows.day
`

type ListDailyTotalsParams struct {
	Environment Environment
	RangeStart  time.Time
	RangeEnd    time.Time
}

type ListDailyTotalsRow struct {
	Day             time.Time
	RevenueNetNanos int64
	CostNanos       int64
}

func (q *Queries) ListDailyTotals(ctx context.Context, arg ListDailyTotalsParams) ([]ListDailyTotalsRow, error) {
	rows, err := q.db.Query(ctx, listDailyTotals, arg.Environment, arg.RangeStart, arg.RangeEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDailyTotalsRow
	for rows.Next() {
		var i ListDailyTotalsRow
		if err := rows.Scan(&i.Day, &i.RevenueNetNanos, &i.CostNanos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestPolicyOutcomes = `-- name: ListLatestPolicyOutcomes :many
SELECT latest.customer_id, latest.outcome, latest.matched_policy_id, latest.created_at
FROM unnest($1::uuid[]) AS watched_customers (customer_id)
CROSS JOIN LATERAL (
    SELECT decisions.customer_id, decisions.outcome, decisions.matched_policy_id, decisions.created_at
    FROM decisions
    WHERE decisions.environment = $2
        AND decisions.customer_id = watched_customers.customer_id
        AND decisions.matched_policy_id IS NOT NULL
    ORDER BY decisions.created_at DESC, decisions.decision_id DESC
    LIMIT 1
) AS latest
`

type ListLatestPolicyOutcomesParams struct {
	CustomerIds []uuid.UUID
	Environment Environment
}

type ListLatestPolicyOutcomesRow struct {
	CustomerID      uuid.UUID
	Outcome         string
	MatchedPolicyID *uuid.UUID
	CreatedAt       time.Time
}

func (q *Queries) ListLatestPolicyOutcomes(ctx context.Context, arg ListLatestPolicyOutcomesParams) ([]ListLatestPolicyOutcomesRow, error) {
	rows, err := q.db.Query(ctx, listLatestPolicyOutcomes, arg.CustomerIds, arg.Environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLatestPolicyOutcomesRow
	for rows.Next() {
		var i ListLatestPolicyOutcomesRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.Outcome,
			&i.MatchedPolicyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT plan_id, name, target_margin_basis_points, allowance_nanos, status
FROM plans
WHERE environment = $1
ORDER BY name
`

type ListPlansRow struct {
	PlanID                  uuid.UUID
	Name                    string
	TargetMarginBasisPoints money.BasisPoints
	AllowanceNanos          *money.Amount
	Status                  RecordStatus
}

func (q *Queries) ListPlans(ctx context.Context, environment Environment) ([]ListPlansRow, error) {
	rows, err := q.db.Query(ctx, listPlans, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.PlanID,
			&i.Name,
			&i.TargetMarginBasisPoints,
			&i.AllowanceNanos,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreviousPeriodTotals = `-- name: ListPreviousPeriodTotals :many
WITH current_periods AS (
    SELECT DISTINCT ON (current_rollups.customer_id) current_rollups.customer_id, current_rollups.period_start
    FROM period_rollups AS current_rollups
    WHERE current_rollups.environment = $1
        AND current_rollups.period_start <= $3
        AND current_rollups.period_end > $3
    ORDER BY current_rollups.customer_id, current_rollups.period_start DESC
)
SELECT DISTINCT ON (period_rollups.customer_id) period_rollups.customer_id,
    customers.external_id,
    customers.display_name,
    plans.plan_id,
    period_rollups.period_start,
    period_rollups.period_end,
    period_rollups.revenue_net_nanos,
    period_rollups.cost_nanos,
    period_rollups.uncosted_count
FROM period_rollups
JOIN customers ON customers.customer_id = period_rollups.customer_id
JOIN environment_settings ON environment_settings.environment = customers.environment
LEFT JOIN plans ON plans.plan_id = coalesce(customers.plan_id, environment_settings.default_plan_id)
LEFT JOIN current_periods ON current_periods.customer_id = period_rollups.customer_id
WHERE period_rollups.environment = $1
    AND period_rollups.period_start < coalesce(current_periods.period_start, $2::timestamptz)
    AND period_rollups.period_end >= coalesce(current_periods.period_start, $2::timestamptz)
ORDER BY period_rollups.customer_id, period_rollups.period_start DESC
`

type ListPreviousPeriodTotalsParams struct {
	Environment        Environment
	CalendarMonthStart time.Time
	Now                time.Time
}

type ListPreviousPeriodTotalsRow struct {
	CustomerID      uuid.UUID
	ExternalID      string
	DisplayName     *string
	PlanID          *uuid.UUID
	PeriodStart     time.Time
	PeriodEnd       time.Time
	RevenueNetNanos money.Amount
	CostNanos       money.Amount
	UncostedCount   int32
}

func (q *Queries) ListPreviousPeriodTotals(ctx context.Context, arg ListPreviousPeriodTotalsParams) ([]ListPreviousPeriodTotalsRow, error) {
	rows, err := q.db.Query(ctx, listPreviousPeriodTotals, arg.Environment, arg.CalendarMonthStart, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreviousPeriodTotalsRow
	for rows.Next() {
		var i ListPreviousPeriodTotalsRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.ExternalID,
			&i.DisplayName,
			&i.PlanID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.RevenueNetNanos,
			&i.CostNanos,
			&i.UncostedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPolicyChanges = `-- name: ListRecentPolicyChanges :many
SELECT policy_id, name, status, version, created_at, updated_at
FROM policies
WHERE environment = $1
ORDER BY updated_at DESC, policy_id DESC
LIMIT $2::bigint
`

type ListRecentPolicyChangesParams struct {
	Environment Environment
	RowLimit    int64
}

type ListRecentPolicyChangesRow struct {
	PolicyID  uuid.UUID
	Name      string
	Status    RecordStatus
	Version   int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) ListRecentPolicyChanges(ctx context.Context, arg ListRecentPolicyChangesParams) ([]ListRecentPolicyChangesRow, error) {
	rows, err := q.db.Query(ctx, listRecentPolicyChanges, arg.Environment, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPolicyChangesRow
	for rows.Next() {
		var i ListRecentPolicyChangesRow
		if err := rows.Scan(
			&i.PolicyID,
			&i.Name,
			&i.Status,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumDecisionsBetween = `-- name: SumDecisionsBetween :one
SELECT count(*) FILTER (WHERE outcome = 'allow') AS allow_count,
    count(*) FILTER (WHERE outcome = 'route') AS route_count,
    count(*) FILTER (WHERE outcome = 'cap') AS cap_count,
    count(*) FILTER (WHERE outcome = 'deny') AS deny_count,
    coalesce(sum(requested_estimated_cost_nanos) FILTER (WHERE outcome = 'deny'), 0)::bigint AS denied_nanos,
    coalesce(sum(greatest(requested_estimated_cost_nanos - estimated_cost_nanos, 0)) FILTER (WHERE outcome = 'route'), 0)::bigint AS routed_nanos,
    coalesce(sum(greatest(requested_estimated_cost_nanos - estimated_cost_nanos, 0)) FILTER (WHERE outcome = 'cap'), 0)::bigint AS capped_nanos
FROM decisions
WHERE environment = $1
    AND created_at >= $2
    AND created_at < $3
`

type SumDecisionsBetweenParams struct {
	Environment Environment
	WindowStart time.Time
	WindowEnd   time.Time
}

type SumDecisionsBetweenRow struct {
	AllowCount  int64
	RouteCount  int64
	CapCount    int64
	DenyCount   int64
	DeniedNanos int64
	RoutedNanos int64
	CappedNanos int64
}

func (q *Queries) SumDecisionsBetween(ctx context.Context, arg SumDecisionsBetweenParams) (SumDecisionsBetweenRow, error) {
	row := q.db.QueryRow(ctx, sumDecisionsBetween, arg.Environment, arg.WindowStart, arg.WindowEnd)
	var i SumDecisionsBetweenRow
	err := row.Scan(
		&i.AllowCount,
		&i.RouteCount,
		&i.CapCount,
		&i.DenyCount,
		&i.DeniedNanos,
		&i.RoutedNanos,
		&i.CappedNanos,
	)
	return i, err
}

const sumDecisionsInPeriods = `-- name: SumDecisionsInPeriods :one
SELECT count(*) FILTER (WHERE outcome = 'allow') AS allow_count,
    count(*) FILTER (WHERE outcome = 'route') AS route_count,
    count(*) FILTER (WHERE outcome = 'cap') AS cap_count,
    count(*) FILTER (WHERE outcome = 'deny') AS deny_count,
    coalesce(sum(requested_estimated_cost_nanos) FILTER (WHERE outcome = 'deny'), 0)::bigint AS denied_nanos,
    coalesce(sum(greatest(requested_estimated_cost_nanos - estimated_cost_nanos, 0)) FILTER (WHERE outcome = 'route'), 0)::bigint AS routed_nanos,
    coalesce(sum(greatest(requested_estimated_cost_nanos - estimated_cost_nanos, 0)) FILTER (WHERE outcome = 'cap'), 0)::bigint AS capped_nanos
FROM decisions
WHERE environment = $1
    AND (customer_id, period_start) IN (
        SELECT unnest($2::uuid[]), unnest($3::timestamptz[])
    )
`

type SumDecisionsInPeriodsParams struct {
	Environment  Environment
	CustomerIds  []uuid.UUID
	PeriodStarts []time.Time
}

type SumDecisionsInPeriodsRow struct {
	AllowCount  int64
	RouteCount  int64
	CapCount    int64
	DenyCount   int64
	DeniedNanos int64
	RoutedNanos int64
	CappedNanos int64
}

func (q *Queries) SumDecisionsInPeriods(ctx context.Context, arg SumDecisionsInPeriodsParams) (SumDecisionsInPeriodsRow, error) {
	row := q.db.QueryRow(ctx, sumDecisionsInPeriods, arg.Environment, arg.CustomerIds, arg.PeriodStarts)
	var i SumDecisionsInPeriodsRow
	err := row.Scan(
		&i.AllowCount,
		&i.RouteCount,
		&i.CapCount,
		&i.DenyCount,
		&i.DeniedNanos,
		&i.RoutedNanos,
		&i.CappedNanos,
	)
	return i, err
}
