// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bootstrap.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const listLiveReservations = `-- name: ListLiveReservations :many
SELECT decision_id, customer_id, feature, reserved_nanos, period_start, period_end, expires_at
FROM decisions
WHERE environment = $1
    AND status = 'reserved'
    AND expires_at > $2
ORDER BY expires_at, decision_id
`

type ListLiveReservationsParams struct {
	Environment   Environment
	ReservedAfter time.Time
}

type ListLiveReservationsRow struct {
	DecisionID    uuid.UUID
	CustomerID    uuid.UUID
	Feature       string
	ReservedNanos money.Amount
	PeriodStart   time.Time
	PeriodEnd     time.Time
	ExpiresAt     time.Time
}

func (q *Queries) ListLiveReservations(ctx context.Context, arg ListLiveReservationsParams) ([]ListLiveReservationsRow, error) {
	rows, err := q.db.Query(ctx, listLiveReservations, arg.Environment, arg.ReservedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveReservationsRow
	for rows.Next() {
		var i ListLiveReservationsRow
		if err := rows.Scan(
			&i.DecisionID,
			&i.CustomerID,
			&i.Feature,
			&i.ReservedNanos,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLapsedReservationsExpired = `-- name: MarkLapsedReservationsExpired :many
WITH expired_decisions AS (
    UPDATE decisions
    SET status = 'expired'
    WHERE decisions.environment = $1
        AND decisions.status = 'reserved'
        AND decisions.expires_at <= $2
    RETURNING decisions.environment, decisions.customer_id, decisions.period_start
)
SELECT DISTINCT expired_decisions.environment, expired_decisions.customer_id, expired_decisions.period_start
FROM expired_decisions
`

type MarkLapsedReservationsExpiredParams struct {
	Environment   Environment
	ReservedAfter time.Time
}

type MarkLapsedReservationsExpiredRow struct {
	Environment Environment
	CustomerID  uuid.UUID
	PeriodStart time.Time
}

func (q *Queries) MarkLapsedReservationsExpired(ctx context.Context, arg MarkLapsedReservationsExpiredParams) ([]MarkLapsedReservationsExpiredRow, error) {
	rows, err := q.db.Query(ctx, markLapsedReservationsExpired, arg.Environment, arg.ReservedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkLapsedReservationsExpiredRow
	for rows.Next() {
		var i MarkLapsedReservationsExpiredRow
		if err := rows.Scan(&i.Environment, &i.CustomerID, &i.PeriodStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
