// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const insertDecision = `-- name: InsertDecision :exec
INSERT INTO decisions (
    decision_id,
    environment,
    customer_id,
    customer_user_id,
    feature,
    requested_provider,
    requested_model,
    provider,
    model,
    attributes,
    overrides,
    outcome,
    reason,
    matched_policy_id,
    matched_policy_version,
    signals,
    requested_estimated_cost_nanos,
    estimated_cost_nanos,
    reserved_nanos,
    estimate_basis,
    status,
    period_start,
    period_end,
    expires_at,
    created_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20,
    $21,
    $22,
    $23,
    $24,
    $25
)
`

type InsertDecisionParams struct {
	DecisionID                  uuid.UUID
	Environment                 Environment
	CustomerID                  uuid.UUID
	CustomerUserID              *uuid.UUID
	Feature                     string
	RequestedProvider           string
	RequestedModel              string
	Provider                    string
	Model                       string
	Attributes                  []byte
	Overrides                   []byte
	Outcome                     string
	Reason                      string
	MatchedPolicyID             *uuid.UUID
	MatchedPolicyVersion        *int32
	Signals                     []byte
	RequestedEstimatedCostNanos *money.Amount
	EstimatedCostNanos          *money.Amount
	ReservedNanos               money.Amount
	EstimateBasis               string
	Status                      string
	PeriodStart                 time.Time
	PeriodEnd                   time.Time
	ExpiresAt                   time.Time
	CreatedAt                   time.Time
}

func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) error {
	_, err := q.db.Exec(ctx, insertDecision,
		arg.DecisionID,
		arg.Environment,
		arg.CustomerID,
		arg.CustomerUserID,
		arg.Feature,
		arg.RequestedProvider,
		arg.RequestedModel,
		arg.Provider,
		arg.Model,
		arg.Attributes,
		arg.Overrides,
		arg.Outcome,
		arg.Reason,
		arg.MatchedPolicyID,
		arg.MatchedPolicyVersion,
		arg.Signals,
		arg.RequestedEstimatedCostNanos,
		arg.EstimatedCostNanos,
		arg.ReservedNanos,
		arg.EstimateBasis,
		arg.Status,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const listFeatureUsageEstimates = `-- name: ListFeatureUsageEstimates :many
SELECT provider, model, meter, p95_quantity_micros, sample_count
FROM usage_estimates
WHERE environment = $1
    AND feature = $2
`

type ListFeatureUsageEstimatesParams struct {
	Environment Environment
	Feature     string
}

type ListFeatureUsageEstimatesRow struct {
	Provider          string
	Model             string
	Meter             string
	P95QuantityMicros int64
	SampleCount       int32
}

func (q *Queries) ListFeatureUsageEstimates(ctx context.Context, arg ListFeatureUsageEstimatesParams) ([]ListFeatureUsageEstimatesRow, error) {
	rows, err := q.db.Query(ctx, listFeatureUsageEstimates, arg.Environment, arg.Feature)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeatureUsageEstimatesRow
	for rows.Next() {
		var i ListFeatureUsageEstimatesRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.Meter,
			&i.P95QuantityMicros,
			&i.SampleCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
