// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expiry.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const markDecisionsExpired = `-- name: MarkDecisionsExpired :many
WITH expired_decisions AS (
    UPDATE decisions
    SET status = 'expired'
    WHERE decision_id = ANY ($1::uuid[])
        AND status = 'reserved'
    RETURNING decisions.environment, decisions.customer_id, decisions.period_start
)
SELECT DISTINCT expired_decisions.environment, expired_decisions.customer_id, expired_decisions.period_start
FROM expired_decisions
`

type MarkDecisionsExpiredRow struct {
	Environment Environment
	CustomerID  uuid.UUID
	PeriodStart time.Time
}

func (q *Queries) MarkDecisionsExpired(ctx context.Context, decisionIds []uuid.UUID) ([]MarkDecisionsExpiredRow, error) {
	rows, err := q.db.Query(ctx, markDecisionsExpired, decisionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkDecisionsExpiredRow
	for rows.Next() {
		var i MarkDecisionsExpiredRow
		if err := rows.Scan(&i.Environment, &i.CustomerID, &i.PeriodStart); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
