// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reconcile.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listActiveCustomerLiveCounters = `-- name: ListActiveCustomerLiveCounters :many
WITH active_customers AS (
    SELECT decisions.customer_id
    FROM decisions
    WHERE decisions.environment = $1
        AND decisions.created_at >= $4
    UNION
    SELECT decisions.customer_id
    FROM decisions
    WHERE decisions.environment = $1
        AND decisions.status IN ('released', 'expired')
        AND decisions.expires_at >= $4
    UNION
    SELECT ledger_entries.customer_id
    FROM ledger_entries
    WHERE ledger_entries.environment = $1
        AND ledger_entries.created_at >= $4
)
SELECT counter_periods.customer_id,
    counter_periods.period_start,
    max(counter_periods.period_end)::timestamptz AS period_end
FROM (
    SELECT decisions.customer_id, decisions.period_start, decisions.period_end
    FROM decisions
    JOIN active_customers ON active_customers.customer_id = decisions.customer_id
    WHERE decisions.environment = $1
        AND (
            (decisions.period_start <= $2 AND decisions.period_end > $2)
            OR (decisions.status = 'reserved' AND decisions.expires_at > $3)
        )
    UNION ALL
    SELECT ledger_entries.customer_id, ledger_entries.period_start, ledger_entries.period_end
    FROM ledger_entries
    JOIN active_customers ON active_customers.customer_id = ledger_entries.customer_id
    WHERE ledger_entries.environment = $1
        AND ledger_entries.period_start <= $2
        AND ledger_entries.period_end > $2
) AS counter_periods
GROUP BY counter_periods.customer_id, counter_periods.period_start
ORDER BY counter_periods.customer_id, counter_periods.period_start
`

type ListActiveCustomerLiveCountersParams struct {
	Environment   Environment
	Now           time.Time
	ReservedAfter time.Time
	ActiveSince   time.Time
}

type ListActiveCustomerLiveCountersRow struct {
	CustomerID  uuid.UUID
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) ListActiveCustomerLiveCounters(ctx context.Context, arg ListActiveCustomerLiveCountersParams) ([]ListActiveCustomerLiveCountersRow, error) {
	rows, err := q.db.Query(ctx, listActiveCustomerLiveCounters,
		arg.Environment,
		arg.Now,
		arg.ReservedAfter,
		arg.ActiveSince,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveCustomerLiveCountersRow
	for rows.Next() {
		var i ListActiveCustomerLiveCountersRow
		if err := rows.Scan(&i.CustomerID, &i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCounterFeatureTotals = `-- name: ListCounterFeatureTotals :many
SELECT counter_rows.customer_id,
    counter_rows.period_start,
    counter_rows.feature,
    sum(counter_rows.settled_nanos)::bigint AS settled_nanos,
    sum(counter_rows.reserved_nanos)::bigint AS reserved_nanos,
    sum(counter_rows.request_count)::bigint AS request_count
FROM (
    SELECT decisions.customer_id,
        decisions.period_start,
        decisions.feature,
        0::bigint AS settled_nanos,
        CASE
            WHEN decisions.status = 'reserved' AND decisions.expires_at > $1 THEN decisions.reserved_nanos
            ELSE 0
        END AS reserved_nanos,
        CASE WHEN decisions.reason = 'hard_limit_reached' THEN 0 ELSE 1 END AS request_count
    FROM decisions
    WHERE decisions.environment = $2
        AND (decisions.customer_id, decisions.period_start) IN (
            SELECT unnest($3::uuid[]), unnest($4::timestamptz[])
        )
    UNION ALL
    SELECT ledger_entries.customer_id,
        ledger_entries.period_start,
        ledger_entries.feature,
        coalesce(ledger_entries.cost_nanos, 0),
        0,
        CASE WHEN ledger_entries.decision_id IS NULL AND ledger_entries.correction_of IS NULL THEN 1 ELSE 0 END
    FROM ledger_entries
    WHERE ledger_entries.environment = $2
        AND (ledger_entries.customer_id, ledger_entries.period_start) IN (
            SELECT unnest($3::uuid[]), unnest($4::timestamptz[])
        )
) AS counter_rows
GROUP BY counter_rows.customer_id, counter_rows.period_start, counter_rows.feature
`

type ListCounterFeatureTotalsParams struct {
	ReservedAfter time.Time
	Environment   Environment
	CustomerIds   []uuid.UUID
	PeriodStarts  []time.Time
}

type ListCounterFeatureTotalsRow struct {
	CustomerID    uuid.UUID
	PeriodStart   time.Time
	Feature       string
	SettledNanos  int64
	ReservedNanos int64
	RequestCount  int64
}

func (q *Queries) ListCounterFeatureTotals(ctx context.Context, arg ListCounterFeatureTotalsParams) ([]ListCounterFeatureTotalsRow, error) {
	rows, err := q.db.Query(ctx, listCounterFeatureTotals,
		arg.ReservedAfter,
		arg.Environment,
		arg.CustomerIds,
		arg.PeriodStarts,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCounterFeatureTotalsRow
	for rows.Next() {
		var i ListCounterFeatureTotalsRow
		if err := rows.Scan(
			&i.CustomerID,
			&i.PeriodStart,
			&i.Feature,
			&i.SettledNanos,
			&i.ReservedNanos,
			&i.RequestCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedDecisions = `-- name: ListFinishedDecisions :many
SELECT decision_id, status
FROM decisions
WHERE environment = $1
    AND decision_id = ANY ($2::uuid[])
    AND status IN ('settled', 'released', 'expired')
`

type ListFinishedDecisionsParams struct {
	Environment Environment
	DecisionIds []uuid.UUID
}

type ListFinishedDecisionsRow struct {
	DecisionID uuid.UUID
	Status     string
}

func (q *Queries) ListFinishedDecisions(ctx context.Context, arg ListFinishedDecisionsParams) ([]ListFinishedDecisionsRow, error) {
	rows, err := q.db.Query(ctx, listFinishedDecisions, arg.Environment, arg.DecisionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinishedDecisionsRow
	for rows.Next() {
		var i ListFinishedDecisionsRow
		if err := rows.Scan(&i.DecisionID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveCounters = `-- name: ListLiveCounters :many
SELECT counter_periods.customer_id,
    counter_periods.period_start,
    max(counter_periods.period_end)::timestamptz AS period_end
FROM (
    SELECT decisions.customer_id, decisions.period_start, decisions.period_end
    FROM decisions
    WHERE decisions.environment = $1
        AND (
            (decisions.period_start <= $2 AND decisions.period_end > $2)
            OR (decisions.status = 'reserved' AND decisions.expires_at > $3)
        )
    UNION ALL
    SELECT ledger_entries.customer_id, ledger_entries.period_start, ledger_entries.period_end
    FROM ledger_entries
    WHERE ledger_entries.environment = $1
        AND ledger_entries.period_start <= $2
        AND ledger_entries.period_end > $2
) AS counter_periods
GROUP BY counter_periods.customer_id, counter_periods.period_start
ORDER BY counter_periods.customer_id, counter_periods.period_start
`

type ListLiveCountersParams struct {
	Environment   Environment
	Now           time.Time
	ReservedAfter time.Time
}

type ListLiveCountersRow struct {
	CustomerID  uuid.UUID
	PeriodStart time.Time
	PeriodEnd   time.Time
}

func (q *Queries) ListLiveCounters(ctx context.Context, arg ListLiveCountersParams) ([]ListLiveCountersRow, error) {
	rows, err := q.db.Query(ctx, listLiveCounters, arg.Environment, arg.Now, arg.ReservedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLiveCountersRow
	for rows.Next() {
		var i ListLiveCountersRow
		if err := rows.Scan(&i.CustomerID, &i.PeriodStart, &i.PeriodEnd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
