// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: report.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const lockDecision = `-- name: LockDecision :one
SELECT decision_id, customer_id, customer_user_id, feature, provider, model, attributes, overrides, status, period_start, period_end
FROM decisions
WHERE environment = $1
    AND decision_id = $2
FOR UPDATE
`

type LockDecisionParams struct {
	Environment Environment
	DecisionID  uuid.UUID
}

type LockDecisionRow struct {
	DecisionID     uuid.UUID
	CustomerID     uuid.UUID
	CustomerUserID *uuid.UUID
	Feature        string
	Provider       string
	Model          string
	Attributes     []byte
	Overrides      []byte
	Status         string
	PeriodStart    time.Time
	PeriodEnd      time.Time
}

func (q *Queries) LockDecision(ctx context.Context, arg LockDecisionParams) (LockDecisionRow, error) {
	row := q.db.QueryRow(ctx, lockDecision, arg.Environment, arg.DecisionID)
	var i LockDecisionRow
	err := row.Scan(
		&i.DecisionID,
		&i.CustomerID,
		&i.CustomerUserID,
		&i.Feature,
		&i.Provider,
		&i.Model,
		&i.Attributes,
		&i.Overrides,
		&i.Status,
		&i.PeriodStart,
		&i.PeriodEnd,
	)
	return i, err
}

const markDecisionReleased = `-- name: MarkDecisionReleased :exec
UPDATE decisions
SET status = 'released'
WHERE decision_id = $1
`

func (q *Queries) MarkDecisionReleased(ctx context.Context, decisionID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDecisionReleased, decisionID)
	return err
}

const markDecisionSettled = `-- name: MarkDecisionSettled :exec
UPDATE decisions
SET status = 'settled',
    settled_at = $1::timestamptz
WHERE decision_id = $2
`

type MarkDecisionSettledParams struct {
	SettledAt  time.Time
	DecisionID uuid.UUID
}

func (q *Queries) MarkDecisionSettled(ctx context.Context, arg MarkDecisionSettledParams) error {
	_, err := q.db.Exec(ctx, markDecisionSettled, arg.SettledAt, arg.DecisionID)
	return err
}
