// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredDecisions = `-- name: DeleteExpiredDecisions :many
WITH expired_decisions AS (
    SELECT decisions.decision_id
    FROM decisions
    WHERE decisions.environment = $1
        AND decisions.created_at < $2::timestamptz
        AND decisions.decision_id > $3::uuid
    ORDER BY decisions.decision_id
    LIMIT $4::bigint
),
deleted_decisions AS (
    DELETE FROM decisions
    WHERE decisions.decision_id IN (SELECT expired_decisions.decision_id FROM expired_decisions)
    RETURNING decisions.decision_id
)
SELECT deleted_decisions.decision_id
FROM deleted_decisions
ORDER BY deleted_decisions.decision_id
`

type DeleteExpiredDecisionsParams struct {
	Environment     Environment
	CreatedBefore   time.Time
	AfterDecisionID uuid.UUID
	BatchSize       int64
}

func (q *Queries) DeleteExpiredDecisions(ctx context.Context, arg DeleteExpiredDecisionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteExpiredDecisions,
		arg.Environment,
		arg.CreatedBefore,
		arg.AfterDecisionID,
		arg.BatchSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var decision_id uuid.UUID
		if err := rows.Scan(&decision_id); err != nil {
			return nil, err
		}
		items = append(items, decision_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
