// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: policies.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const customerExists = `-- name: CustomerExists :one
SELECT EXISTS (
    SELECT 1
    FROM customers
    WHERE environment = $1
        AND customer_id = $2
)
`

type CustomerExistsParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

func (q *Queries) CustomerExists(ctx context.Context, arg CustomerExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, customerExists, arg.Environment, arg.CustomerID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertPolicy = `-- name: InsertPolicy :one
INSERT INTO policies (
    policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, 1, $14, $14
)
RETURNING policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
`

type InsertPolicyParams struct {
	PolicyID       uuid.UUID
	Environment    Environment
	Name           string
	Level          string
	PlanID         *uuid.UUID
	CustomerID     *uuid.UUID
	Feature        *string
	ConditionGroup []byte
	Action         []byte
	Enforcement    string
	OnUnreachable  string
	OnUncosted     string
	Status         RecordStatus
	CreatedAt      time.Time
}

func (q *Queries) InsertPolicy(ctx context.Context, arg InsertPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, insertPolicy,
		arg.PolicyID,
		arg.Environment,
		arg.Name,
		arg.Level,
		arg.PlanID,
		arg.CustomerID,
		arg.Feature,
		arg.ConditionGroup,
		arg.Action,
		arg.Enforcement,
		arg.OnUnreachable,
		arg.OnUncosted,
		arg.Status,
		arg.CreatedAt,
	)
	var i Policy
	err := row.Scan(
		&i.PolicyID,
		&i.Environment,
		&i.Name,
		&i.Level,
		&i.PlanID,
		&i.CustomerID,
		&i.Feature,
		&i.ConditionGroup,
		&i.Action,
		&i.Enforcement,
		&i.OnUnreachable,
		&i.OnUncosted,
		&i.Status,
		&i.Version,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivePolicies = `-- name: ListActivePolicies :many
SELECT policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
FROM policies
WHERE environment = $1
    AND status = 'active'
ORDER BY policy_id
`

func (q *Queries) ListActivePolicies(ctx context.Context, environment Environment) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listActivePolicies, environment)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.PolicyID,
			&i.Environment,
			&i.Name,
			&i.Level,
			&i.PlanID,
			&i.CustomerID,
			&i.Feature,
			&i.ConditionGroup,
			&i.Action,
			&i.Enforcement,
			&i.OnUnreachable,
			&i.OnUncosted,
			&i.Status,
			&i.Version,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPolicies = `-- name: ListPolicies :many
SELECT policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
FROM policies
WHERE environment = $1
    AND ($2::text IS NULL OR status::text = $2::text)
    AND ($3::uuid IS NULL OR plan_id = $3::uuid)
    AND (
        $4::timestamptz IS NULL
        OR (created_at, policy_id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY created_at DESC, policy_id DESC
LIMIT $6::bigint
`

type ListPoliciesParams struct {
	Environment    Environment
	Status         *string
	PlanID         *uuid.UUID
	AfterCreatedAt *time.Time
	AfterPolicyID  *uuid.UUID
	RowLimit       int64
}

func (q *Queries) ListPolicies(ctx context.Context, arg ListPoliciesParams) ([]Policy, error) {
	rows, err := q.db.Query(ctx, listPolicies,
		arg.Environment,
		arg.Status,
		arg.PlanID,
		arg.AfterCreatedAt,
		arg.AfterPolicyID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Policy
	for rows.Next() {
		var i Policy
		if err := rows.Scan(
			&i.PolicyID,
			&i.Environment,
			&i.Name,
			&i.Level,
			&i.PlanID,
			&i.CustomerID,
			&i.Feature,
			&i.ConditionGroup,
			&i.Action,
			&i.Enforcement,
			&i.OnUnreachable,
			&i.OnUncosted,
			&i.Status,
			&i.Version,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectAliasedModel = `-- name: SelectAliasedModel :one
SELECT model
FROM provider_model_aliases
WHERE provider = $1
    AND alias = $2
`

type SelectAliasedModelParams struct {
	Provider string
	Alias    string
}

func (q *Queries) SelectAliasedModel(ctx context.Context, arg SelectAliasedModelParams) (string, error) {
	row := q.db.QueryRow(ctx, selectAliasedModel, arg.Provider, arg.Alias)
	var model string
	err := row.Scan(&model)
	return model, err
}

const selectPlanStatus = `-- name: SelectPlanStatus :one
SELECT status
FROM plans
WHERE environment = $1
    AND plan_id = $2
`

type SelectPlanStatusParams struct {
	Environment Environment
	PlanID      uuid.UUID
}

func (q *Queries) SelectPlanStatus(ctx context.Context, arg SelectPlanStatusParams) (RecordStatus, error) {
	row := q.db.QueryRow(ctx, selectPlanStatus, arg.Environment, arg.PlanID)
	var status RecordStatus
	err := row.Scan(&status)
	return status, err
}

const selectPolicy = `-- name: SelectPolicy :one
SELECT policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
FROM policies
WHERE environment = $1
    AND policy_id = $2
`

type SelectPolicyParams struct {
	Environment Environment
	PolicyID    uuid.UUID
}

func (q *Queries) SelectPolicy(ctx context.Context, arg SelectPolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, selectPolicy, arg.Environment, arg.PolicyID)
	var i Policy
	err := row.Scan(
		&i.PolicyID,
		&i.Environment,
		&i.Name,
		&i.Level,
		&i.PlanID,
		&i.CustomerID,
		&i.Feature,
		&i.ConditionGroup,
		&i.Action,
		&i.Enforcement,
		&i.OnUnreachable,
		&i.OnUncosted,
		&i.Status,
		&i.Version,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectPolicyForUpdate = `-- name: SelectPolicyForUpdate :one
SELECT policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
FROM policies
WHERE environment = $1
    AND policy_id = $2
FOR UPDATE
`

type SelectPolicyForUpdateParams struct {
	Environment Environment
	PolicyID    uuid.UUID
}

func (q *Queries) SelectPolicyForUpdate(ctx context.Context, arg SelectPolicyForUpdateParams) (Policy, error) {
	row := q.db.QueryRow(ctx, selectPolicyForUpdate, arg.Environment, arg.PolicyID)
	var i Policy
	err := row.Scan(
		&i.PolicyID,
		&i.Environment,
		&i.Name,
		&i.Level,
		&i.PlanID,
		&i.CustomerID,
		&i.Feature,
		&i.ConditionGroup,
		&i.Action,
		&i.Enforcement,
		&i.OnUnreachable,
		&i.OnUncosted,
		&i.Status,
		&i.Version,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePolicy = `-- name: UpdatePolicy :one
UPDATE policies
SET name = $1,
    level = $2,
    plan_id = $3,
    customer_id = $4,
    feature = $5,
    condition_group = $6,
    action = $7,
    enforcement = $8,
    on_unreachable = $9,
    on_uncosted = $10,
    status = $11,
    version = version + 1,
    updated_at = $12
WHERE policy_id = $13
RETURNING policy_id, environment, name, level, plan_id, customer_id, feature, condition_group, action,
    enforcement, on_unreachable, on_uncosted, status, version, import_id, created_at, updated_at
`

type UpdatePolicyParams struct {
	Name           string
	Level          string
	PlanID         *uuid.UUID
	CustomerID     *uuid.UUID
	Feature        *string
	ConditionGroup []byte
	Action         []byte
	Enforcement    string
	OnUnreachable  string
	OnUncosted     string
	Status         RecordStatus
	UpdatedAt      time.Time
	PolicyID       uuid.UUID
}

func (q *Queries) UpdatePolicy(ctx context.Context, arg UpdatePolicyParams) (Policy, error) {
	row := q.db.QueryRow(ctx, updatePolicy,
		arg.Name,
		arg.Level,
		arg.PlanID,
		arg.CustomerID,
		arg.Feature,
		arg.ConditionGroup,
		arg.Action,
		arg.Enforcement,
		arg.OnUnreachable,
		arg.OnUncosted,
		arg.Status,
		arg.UpdatedAt,
		arg.PolicyID,
	)
	var i Policy
	err := row.Scan(
		&i.PolicyID,
		&i.Environment,
		&i.Name,
		&i.Level,
		&i.PlanID,
		&i.CustomerID,
		&i.Feature,
		&i.ConditionGroup,
		&i.Action,
		&i.Enforcement,
		&i.OnUnreachable,
		&i.OnUncosted,
		&i.Status,
		&i.Version,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
