// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: preview.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countActiveCustomers = `-- name: CountActiveCustomers :one
SELECT count(*)
FROM customers
WHERE environment = $1
    AND status = 'active'
`

func (q *Queries) CountActiveCustomers(ctx context.Context, environment Environment) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCustomers, environment)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listPeriodCounters = `-- name: ListPeriodCounters :many
SELECT counter_rows.customer_id,
    sum(counter_rows.settled_nanos)::bigint AS settled_nanos,
    sum(counter_rows.decision_count)::bigint AS decision_count
FROM (
    SELECT decisions.customer_id,
        0::bigint AS settled_nanos,
        CASE WHEN decisions.reason = 'hard_limit_reached' THEN 0 ELSE 1 END AS decision_count
    FROM decisions
    WHERE decisions.environment = $1
        AND (decisions.customer_id, decisions.period_start) IN (
            SELECT unnest($2::uuid[]), unnest($3::timestamptz[])
        )
    UNION ALL
    SELECT ledger_entries.customer_id,
        coalesce(ledger_entries.cost_nanos, 0),
        CASE WHEN ledger_entries.decision_id IS NULL AND ledger_entries.correction_of IS NULL THEN 1 ELSE 0 END
    FROM ledger_entries
    WHERE ledger_entries.environment = $1
        AND (ledger_entries.customer_id, ledger_entries.period_start) IN (
            SELECT unnest($2::uuid[]), unnest($3::timestamptz[])
        )
) AS counter_rows
GROUP BY counter_rows.customer_id
`

type ListPeriodCountersParams struct {
	Environment  Environment
	CustomerIds  []uuid.UUID
	PeriodStarts []time.Time
}

type ListPeriodCountersRow struct {
	CustomerID    uuid.UUID
	SettledNanos  int64
	DecisionCount int64
}

func (q *Queries) ListPeriodCounters(ctx context.Context, arg ListPeriodCountersParams) ([]ListPeriodCountersRow, error) {
	rows, err := q.db.Query(ctx, listPeriodCounters, arg.Environment, arg.CustomerIds, arg.PeriodStarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPeriodCountersRow
	for rows.Next() {
		var i ListPeriodCountersRow
		if err := rows.Scan(&i.CustomerID, &i.SettledNanos, &i.DecisionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
