// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installation.sql

package queries

import (
	"context"
	"time"
)

const completeSetup = `-- name: CompleteSetup :exec
UPDATE installation
SET updated_at = $1, setup_completed_at = $1, setup_token_hash = NULL
WHERE installation_id = 1
`

func (q *Queries) CompleteSetup(ctx context.Context, completedAt time.Time) error {
	_, err := q.db.Exec(ctx, completeSetup, completedAt)
	return err
}

const selectInstallation = `-- name: SelectInstallation :one
SELECT installation_id, name, setup_token_hash, setup_completed_at, created_at, updated_at
FROM installation
WHERE installation_id = 1
`

func (q *Queries) SelectInstallation(ctx context.Context) (Installation, error) {
	row := q.db.QueryRow(ctx, selectInstallation)
	var i Installation
	err := row.Scan(
		&i.InstallationID,
		&i.Name,
		&i.SetupTokenHash,
		&i.SetupCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectInstallationForUpdate = `-- name: SelectInstallationForUpdate :one
SELECT installation_id, name, setup_token_hash, setup_completed_at, created_at, updated_at
FROM installation
WHERE installation_id = 1
FOR UPDATE
`

func (q *Queries) SelectInstallationForUpdate(ctx context.Context) (Installation, error) {
	row := q.db.QueryRow(ctx, selectInstallationForUpdate)
	var i Installation
	err := row.Scan(
		&i.InstallationID,
		&i.Name,
		&i.SetupTokenHash,
		&i.SetupCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setSetupTokenHash = `-- name: SetSetupTokenHash :execrows
UPDATE installation
SET setup_token_hash = $1, updated_at = $2
WHERE installation_id = 1
    AND setup_completed_at IS NULL
`

type SetSetupTokenHashParams struct {
	SetupTokenHash []byte
	UpdatedAt      time.Time
}

func (q *Queries) SetSetupTokenHash(ctx context.Context, arg SetSetupTokenHashParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSetupTokenHash, arg.SetupTokenHash, arg.UpdatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
