// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const selectActivePlanForShare = `-- name: SelectActivePlanForShare :one
SELECT plan_id
FROM plans
WHERE environment = $1
    AND plan_id = $2
    AND status = 'active'
FOR SHARE
`

type SelectActivePlanForShareParams struct {
	Environment Environment
	PlanID      uuid.UUID
}

func (q *Queries) SelectActivePlanForShare(ctx context.Context, arg SelectActivePlanForShareParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, selectActivePlanForShare, arg.Environment, arg.PlanID)
	var plan_id uuid.UUID
	err := row.Scan(&plan_id)
	return plan_id, err
}

const selectSettings = `-- name: SelectSettings :one
SELECT installation.name AS installation_name, environment_settings.default_plan_id, environment_settings.stripe_customer_metadata_key
FROM installation
CROSS JOIN environment_settings
WHERE installation.installation_id = 1
    AND environment_settings.environment = $1
`

type SelectSettingsRow struct {
	InstallationName          string
	DefaultPlanID             *uuid.UUID
	StripeCustomerMetadataKey string
}

func (q *Queries) SelectSettings(ctx context.Context, environment Environment) (SelectSettingsRow, error) {
	row := q.db.QueryRow(ctx, selectSettings, environment)
	var i SelectSettingsRow
	err := row.Scan(&i.InstallationName, &i.DefaultPlanID, &i.StripeCustomerMetadataKey)
	return i, err
}

const selectSettingsForUpdate = `-- name: SelectSettingsForUpdate :one
SELECT installation.name AS installation_name, environment_settings.default_plan_id, environment_settings.stripe_customer_metadata_key
FROM installation
CROSS JOIN environment_settings
WHERE installation.installation_id = 1
    AND environment_settings.environment = $1
FOR UPDATE
`

type SelectSettingsForUpdateRow struct {
	InstallationName          string
	DefaultPlanID             *uuid.UUID
	StripeCustomerMetadataKey string
}

func (q *Queries) SelectSettingsForUpdate(ctx context.Context, environment Environment) (SelectSettingsForUpdateRow, error) {
	row := q.db.QueryRow(ctx, selectSettingsForUpdate, environment)
	var i SelectSettingsForUpdateRow
	err := row.Scan(&i.InstallationName, &i.DefaultPlanID, &i.StripeCustomerMetadataKey)
	return i, err
}

const updateEnvironmentSettings = `-- name: UpdateEnvironmentSettings :exec
UPDATE environment_settings
SET default_plan_id = $1,
    stripe_customer_metadata_key = $2,
    updated_at = $3
WHERE environment = $4
`

type UpdateEnvironmentSettingsParams struct {
	DefaultPlanID             *uuid.UUID
	StripeCustomerMetadataKey string
	UpdatedAt                 time.Time
	Environment               Environment
}

func (q *Queries) UpdateEnvironmentSettings(ctx context.Context, arg UpdateEnvironmentSettingsParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentSettings,
		arg.DefaultPlanID,
		arg.StripeCustomerMetadataKey,
		arg.UpdatedAt,
		arg.Environment,
	)
	return err
}

const updateInstallationName = `-- name: UpdateInstallationName :exec
UPDATE installation
SET name = $1, updated_at = $2
WHERE installation_id = 1
`

type UpdateInstallationNameParams struct {
	Name      string
	UpdatedAt time.Time
}

func (q *Queries) UpdateInstallationName(ctx context.Context, arg UpdateInstallationNameParams) error {
	_, err := q.db.Exec(ctx, updateInstallationName, arg.Name, arg.UpdatedAt)
	return err
}
