// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

type Environment string

const (
	EnvironmentTest Environment = "test"
	EnvironmentLive Environment = "live"
)

func (e *Environment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Environment(s)
	case string:
		*e = Environment(s)
	default:
		return fmt.Errorf("unsupported scan type for Environment: %T", src)
	}
	return nil
}

type NullEnvironment struct {
	Environment Environment
	Valid       bool // Valid is true if Environment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvironment) Scan(value interface{}) error {
	if value == nil {
		ns.Environment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Environment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvironment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Environment), nil
}

type RecordStatus string

const (
	RecordStatusActive   RecordStatus = "active"
	RecordStatusDisabled RecordStatus = "disabled"
	RecordStatusArchived RecordStatus = "archived"
)

func (e *RecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordStatus(s)
	case string:
		*e = RecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordStatus: %T", src)
	}
	return nil
}

type NullRecordStatus struct {
	RecordStatus RecordStatus
	Valid        bool // Valid is true if RecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordStatus), nil
}

type Plan struct {
	PlanID                  uuid.UUID
	Environment             Environment
	Name                    string
	TargetMarginBasisPoints money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
	Status                  RecordStatus
	ImportID                *uuid.UUID
	CreatedAt               time.Time
	UpdatedAt               time.Time
}
