// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const countCustomersPerPlan = `-- name: CountCustomersPerPlan :many
SELECT coalesce(customers.plan_id, environment_settings.default_plan_id)::uuid AS plan_id, count(*) AS customer_count
FROM customers
JOIN environment_settings ON environment_settings.environment = customers.environment
WHERE customers.environment = $1
    AND coalesce(customers.plan_id, environment_settings.default_plan_id) = ANY ($2::uuid[])
GROUP BY coalesce(customers.plan_id, environment_settings.default_plan_id)
`

type CountCustomersPerPlanParams struct {
	Environment Environment
	PlanIds     []uuid.UUID
}

type CountCustomersPerPlanRow struct {
	PlanID        uuid.UUID
	CustomerCount int64
}

func (q *Queries) CountCustomersPerPlan(ctx context.Context, arg CountCustomersPerPlanParams) ([]CountCustomersPerPlanRow, error) {
	rows, err := q.db.Query(ctx, countCustomersPerPlan, arg.Environment, arg.PlanIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountCustomersPerPlanRow
	for rows.Next() {
		var i CountCustomersPerPlanRow
		if err := rows.Scan(&i.PlanID, &i.CustomerCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlan = `-- name: InsertPlan :one
INSERT INTO plans (
    plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $7, $7
)
RETURNING plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, import_id, created_at, updated_at
`

type InsertPlanParams struct {
	PlanID                  uuid.UUID
	Environment             Environment
	Name                    string
	TargetMarginBasisPoints money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
	CreatedAt               time.Time
}

func (q *Queries) InsertPlan(ctx context.Context, arg InsertPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, insertPlan,
		arg.PlanID,
		arg.Environment,
		arg.Name,
		arg.TargetMarginBasisPoints,
		arg.AllowanceNanos,
		arg.HoldTimes,
		arg.CreatedAt,
	)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.Environment,
		&i.Name,
		&i.TargetMarginBasisPoints,
		&i.AllowanceNanos,
		&i.HoldTimes,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlans = `-- name: ListPlans :many
SELECT plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, import_id, created_at, updated_at
FROM plans
WHERE environment = $1
    AND (
        $2::timestamptz IS NULL
        OR (created_at, plan_id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, plan_id DESC
LIMIT $4::bigint
`

type ListPlansParams struct {
	Environment    Environment
	AfterCreatedAt *time.Time
	AfterPlanID    *uuid.UUID
	RowLimit       int64
}

func (q *Queries) ListPlans(ctx context.Context, arg ListPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, listPlans,
		arg.Environment,
		arg.AfterCreatedAt,
		arg.AfterPlanID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Plan
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.PlanID,
			&i.Environment,
			&i.Name,
			&i.TargetMarginBasisPoints,
			&i.AllowanceNanos,
			&i.HoldTimes,
			&i.Status,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectDefaultPlanID = `-- name: SelectDefaultPlanID :one
SELECT default_plan_id
FROM environment_settings
WHERE environment = $1
`

func (q *Queries) SelectDefaultPlanID(ctx context.Context, environment Environment) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, selectDefaultPlanID, environment)
	var default_plan_id *uuid.UUID
	err := row.Scan(&default_plan_id)
	return default_plan_id, err
}

const selectPlan = `-- name: SelectPlan :one
SELECT plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, import_id, created_at, updated_at
FROM plans
WHERE environment = $1
    AND plan_id = $2
`

type SelectPlanParams struct {
	Environment Environment
	PlanID      uuid.UUID
}

func (q *Queries) SelectPlan(ctx context.Context, arg SelectPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, selectPlan, arg.Environment, arg.PlanID)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.Environment,
		&i.Name,
		&i.TargetMarginBasisPoints,
		&i.AllowanceNanos,
		&i.HoldTimes,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectPlanForUpdate = `-- name: SelectPlanForUpdate :one
SELECT plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, import_id, created_at, updated_at
FROM plans
WHERE environment = $1
    AND plan_id = $2
FOR UPDATE
`

type SelectPlanForUpdateParams struct {
	Environment Environment
	PlanID      uuid.UUID
}

func (q *Queries) SelectPlanForUpdate(ctx context.Context, arg SelectPlanForUpdateParams) (Plan, error) {
	row := q.db.QueryRow(ctx, selectPlanForUpdate, arg.Environment, arg.PlanID)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.Environment,
		&i.Name,
		&i.TargetMarginBasisPoints,
		&i.AllowanceNanos,
		&i.HoldTimes,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePlan = `-- name: UpdatePlan :one
UPDATE plans
SET name = $1,
    target_margin_basis_points = $2,
    allowance_nanos = $3,
    hold_times = $4,
    status = $5,
    updated_at = $6
WHERE plan_id = $7
RETURNING plan_id, environment, name, target_margin_basis_points, allowance_nanos, hold_times, status, import_id, created_at, updated_at
`

type UpdatePlanParams struct {
	Name                    string
	TargetMarginBasisPoints money.BasisPoints
	AllowanceNanos          *money.Amount
	HoldTimes               []byte
	Status                  RecordStatus
	UpdatedAt               time.Time
	PlanID                  uuid.UUID
}

func (q *Queries) UpdatePlan(ctx context.Context, arg UpdatePlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, updatePlan,
		arg.Name,
		arg.TargetMarginBasisPoints,
		arg.AllowanceNanos,
		arg.HoldTimes,
		arg.Status,
		arg.UpdatedAt,
		arg.PlanID,
	)
	var i Plan
	err := row.Scan(
		&i.PlanID,
		&i.Environment,
		&i.Name,
		&i.TargetMarginBasisPoints,
		&i.AllowanceNanos,
		&i.HoldTimes,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
