// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const disableAPIKey = `-- name: DisableAPIKey :execrows
UPDATE api_keys
SET status = 'disabled', updated_at = $1
WHERE api_key_id = $2
    AND environment = $3
`

type DisableAPIKeyParams struct {
	UpdatedAt   time.Time
	APIKeyID    uuid.UUID
	Environment Environment
}

func (q *Queries) DisableAPIKey(ctx context.Context, arg DisableAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableAPIKey, arg.UpdatedAt, arg.APIKeyID, arg.Environment)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (
    api_key_id, environment, name, scope, secret_hash, secret_last_four, status, created_by_member_id, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $7, $8, $8
)
RETURNING api_key_id, environment, name, scope, secret_hash, secret_last_four, status, last_used_at, created_by_member_id, created_at, updated_at
`

type InsertAPIKeyParams struct {
	APIKeyID          uuid.UUID
	Environment       Environment
	Name              string
	Scope             string
	SecretHash        []byte
	SecretLastFour    string
	CreatedByMemberID *uuid.UUID
	CreatedAt         time.Time
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (APIKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.APIKeyID,
		arg.Environment,
		arg.Name,
		arg.Scope,
		arg.SecretHash,
		arg.SecretLastFour,
		arg.CreatedByMemberID,
		arg.CreatedAt,
	)
	var i APIKey
	err := row.Scan(
		&i.APIKeyID,
		&i.Environment,
		&i.Name,
		&i.Scope,
		&i.SecretHash,
		&i.SecretLastFour,
		&i.Status,
		&i.LastUsedAt,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT api_key_id, environment, name, scope, secret_hash, secret_last_four, status, last_used_at, created_by_member_id, created_at, updated_at
FROM api_keys
WHERE environment = $1
    AND (
        $2::timestamptz IS NULL
        OR (created_at, api_key_id) < ($2::timestamptz, $3::uuid)
    )
ORDER BY created_at DESC, api_key_id DESC
LIMIT $4::bigint
`

type ListAPIKeysParams struct {
	Environment    Environment
	AfterCreatedAt *time.Time
	AfterAPIKeyID  *uuid.UUID
	RowLimit       int64
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]APIKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.Environment,
		arg.AfterCreatedAt,
		arg.AfterAPIKeyID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []APIKey
	for rows.Next() {
		var i APIKey
		if err := rows.Scan(
			&i.APIKeyID,
			&i.Environment,
			&i.Name,
			&i.Scope,
			&i.SecretHash,
			&i.SecretLastFour,
			&i.Status,
			&i.LastUsedAt,
			&i.CreatedByMemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectActiveAPIKeyBySecretHash = `-- name: SelectActiveAPIKeyBySecretHash :one
SELECT api_key_id, environment, scope
FROM api_keys
WHERE secret_hash = $1
    AND status = 'active'
`

type SelectActiveAPIKeyBySecretHashRow struct {
	APIKeyID    uuid.UUID
	Environment Environment
	Scope       string
}

func (q *Queries) SelectActiveAPIKeyBySecretHash(ctx context.Context, secretHash []byte) (SelectActiveAPIKeyBySecretHashRow, error) {
	row := q.db.QueryRow(ctx, selectActiveAPIKeyBySecretHash, secretHash)
	var i SelectActiveAPIKeyBySecretHashRow
	err := row.Scan(&i.APIKeyID, &i.Environment, &i.Scope)
	return i, err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = $1::timestamptz
WHERE api_key_id = $2
`

type UpdateAPIKeyLastUsedParams struct {
	LastUsedAt time.Time
	APIKeyID   uuid.UUID
}

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, arg UpdateAPIKeyLastUsedParams) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, arg.LastUsedAt, arg.APIKeyID)
	return err
}
