// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revenue_entries.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/preburn/preburn/internal/money"
)

const insertRevenueEntry = `-- name: InsertRevenueEntry :one
INSERT INTO revenue_entries (
    revenue_entry_id, environment, customer_id, period_start, period_end, kind, amount_nanos, source, source_reference, occurred_at, created_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (environment, source, kind, source_reference) DO NOTHING
RETURNING revenue_entry_id, environment, customer_id, period_start, period_end, kind, amount_nanos, source, source_reference, occurred_at, import_id, created_at
`

type InsertRevenueEntryParams struct {
	RevenueEntryID  uuid.UUID
	Environment     Environment
	CustomerID      uuid.UUID
	PeriodStart     time.Time
	PeriodEnd       time.Time
	Kind            string
	AmountNanos     money.Amount
	Source          string
	SourceReference string
	OccurredAt      time.Time
	CreatedAt       time.Time
}

func (q *Queries) InsertRevenueEntry(ctx context.Context, arg InsertRevenueEntryParams) (RevenueEntry, error) {
	row := q.db.QueryRow(ctx, insertRevenueEntry,
		arg.RevenueEntryID,
		arg.Environment,
		arg.CustomerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Kind,
		arg.AmountNanos,
		arg.Source,
		arg.SourceReference,
		arg.OccurredAt,
		arg.CreatedAt,
	)
	var i RevenueEntry
	err := row.Scan(
		&i.RevenueEntryID,
		&i.Environment,
		&i.CustomerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Kind,
		&i.AmountNanos,
		&i.Source,
		&i.SourceReference,
		&i.OccurredAt,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}

const listRevenueEntries = `-- name: ListRevenueEntries :many
SELECT revenue_entries.revenue_entry_id, revenue_entries.environment, revenue_entries.customer_id, revenue_entries.period_start, revenue_entries.period_end, revenue_entries.kind, revenue_entries.amount_nanos, revenue_entries.source, revenue_entries.source_reference, revenue_entries.occurred_at, revenue_entries.import_id, revenue_entries.created_at, customers.external_id
FROM revenue_entries
JOIN customers ON customers.customer_id = revenue_entries.customer_id
    AND customers.environment = revenue_entries.environment
WHERE revenue_entries.environment = $1
    AND (
        $2::text IS NULL
        OR customers.external_id = $2::text
    )
    AND (
        $3::text IS NULL
        OR revenue_entries.kind = $3::text
    )
    AND (
        $4::timestamptz IS NULL
        OR (revenue_entries.created_at, revenue_entries.revenue_entry_id) < ($4::timestamptz, $5::uuid)
    )
ORDER BY revenue_entries.created_at DESC, revenue_entries.revenue_entry_id DESC
LIMIT $6::bigint
`

type ListRevenueEntriesParams struct {
	Environment         Environment
	CustomerExternalID  *string
	Kind                *string
	AfterCreatedAt      *time.Time
	AfterRevenueEntryID *uuid.UUID
	RowLimit            int64
}

type ListRevenueEntriesRow struct {
	RevenueEntry RevenueEntry
	ExternalID   string
}

func (q *Queries) ListRevenueEntries(ctx context.Context, arg ListRevenueEntriesParams) ([]ListRevenueEntriesRow, error) {
	rows, err := q.db.Query(ctx, listRevenueEntries,
		arg.Environment,
		arg.CustomerExternalID,
		arg.Kind,
		arg.AfterCreatedAt,
		arg.AfterRevenueEntryID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRevenueEntriesRow
	for rows.Next() {
		var i ListRevenueEntriesRow
		if err := rows.Scan(
			&i.RevenueEntry.RevenueEntryID,
			&i.RevenueEntry.Environment,
			&i.RevenueEntry.CustomerID,
			&i.RevenueEntry.PeriodStart,
			&i.RevenueEntry.PeriodEnd,
			&i.RevenueEntry.Kind,
			&i.RevenueEntry.AmountNanos,
			&i.RevenueEntry.Source,
			&i.RevenueEntry.SourceReference,
			&i.RevenueEntry.OccurredAt,
			&i.RevenueEntry.ImportID,
			&i.RevenueEntry.CreatedAt,
			&i.ExternalID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectRevenueEntryBySourceReference = `-- name: SelectRevenueEntryBySourceReference :one
SELECT revenue_entries.revenue_entry_id, revenue_entries.environment, revenue_entries.customer_id, revenue_entries.period_start, revenue_entries.period_end, revenue_entries.kind, revenue_entries.amount_nanos, revenue_entries.source, revenue_entries.source_reference, revenue_entries.occurred_at, revenue_entries.import_id, revenue_entries.created_at, customers.external_id
FROM revenue_entries
JOIN customers ON customers.customer_id = revenue_entries.customer_id
    AND customers.environment = revenue_entries.environment
WHERE revenue_entries.environment = $1
    AND revenue_entries.source = $2
    AND revenue_entries.kind = $3
    AND revenue_entries.source_reference = $4
`

type SelectRevenueEntryBySourceReferenceParams struct {
	Environment     Environment
	Source          string
	Kind            string
	SourceReference string
}

type SelectRevenueEntryBySourceReferenceRow struct {
	RevenueEntry RevenueEntry
	ExternalID   string
}

func (q *Queries) SelectRevenueEntryBySourceReference(ctx context.Context, arg SelectRevenueEntryBySourceReferenceParams) (SelectRevenueEntryBySourceReferenceRow, error) {
	row := q.db.QueryRow(ctx, selectRevenueEntryBySourceReference,
		arg.Environment,
		arg.Source,
		arg.Kind,
		arg.SourceReference,
	)
	var i SelectRevenueEntryBySourceReferenceRow
	err := row.Scan(
		&i.RevenueEntry.RevenueEntryID,
		&i.RevenueEntry.Environment,
		&i.RevenueEntry.CustomerID,
		&i.RevenueEntry.PeriodStart,
		&i.RevenueEntry.PeriodEnd,
		&i.RevenueEntry.Kind,
		&i.RevenueEntry.AmountNanos,
		&i.RevenueEntry.Source,
		&i.RevenueEntry.SourceReference,
		&i.RevenueEntry.OccurredAt,
		&i.RevenueEntry.ImportID,
		&i.RevenueEntry.CreatedAt,
		&i.ExternalID,
	)
	return i, err
}
