// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zApiKeyResponse = z.object({
    created_at: z.iso.datetime(),
    id: z.string(),
    last_used_at: z.iso.datetime().nullable(),
    name: z.string(),
    scope: z.enum(['runtime', 'admin']),
    secret_last_four: z.string(),
    status: z.enum(['active', 'disabled'])
});

export const zActivityEventResponse = z.object({
    cost: z.string().nullable(),
    customer_display_name: z.string().nullable(),
    customer_external_id: z.string(),
    customer_id: z.string(),
    decision_id: z.string().nullable(),
    feature: z.string(),
    id: z.string(),
    kind: z.enum(['decision', 'ledger_entry']),
    model: z.string(),
    occurred_at: z.iso.datetime(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]).nullable(),
    provider: z.string()
});

export const zAddMemberRequest = z.object({
    display_name: z.string(),
    email: z.string()
});

export const zAttentionResponse = z.object({
    customers_above_pace: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    dropped_reports: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    plans_below_target: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    uncosted_requests: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCheckRequest = z.object({
    attributes: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])).optional(),
    customer_id: z.string(),
    customer_user_id: z.string().optional(),
    feature: z.string(),
    model: z.string(),
    provider: z.string(),
    usage_ceiling: z.record(z.string(), z.string()).optional(),
    usage_estimate: z.record(z.string(), z.string()).optional()
});

export const zCompleteSetupRequest = z.object({
    display_name: z.string(),
    email: z.string(),
    password: z.string(),
    token: z.string()
});

export const zConsumeLinkRequest = z.object({
    password: z.string(),
    token: z.string()
});

export const zCostAvoidedResponse = z.object({
    capped: z.string(),
    changed_decision_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    denied: z.string(),
    routed: z.string(),
    total: z.string()
});

export const zCreateApiKeyRequest = z.object({
    name: z.string(),
    scope: z.enum(['runtime', 'admin'])
});

export const zCreateOverrideRequest = z.object({
    billing_increment: z.string().optional(),
    conditions: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])).optional(),
    meter: z.string(),
    minimum_charge: z.string().optional(),
    model: z.string(),
    native_unit: z.string().optional(),
    native_unit_price: z.string().optional(),
    provider: z.string(),
    type: z.enum(['adjustment', 'standalone']).optional(),
    unit_price: z.string(),
    unit_quantity: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCreatePlanRequest = z.object({
    allowance: z.string().optional(),
    hold_times: z.record(z.string(), z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })).optional(),
    mode: z.enum(['margin_target', 'fixed_allowance']),
    name: z.string(),
    target_margin: z.string().optional()
});

export const zCreatedApiKeyResponse = z.object({
    created_at: z.iso.datetime(),
    id: z.string(),
    last_used_at: z.iso.datetime().nullable(),
    name: z.string(),
    scope: z.enum(['runtime', 'admin']),
    secret: z.string(),
    secret_last_four: z.string(),
    status: z.enum(['active', 'disabled'])
});

export const zCustomerDecisionResponse = z.object({
    created_at: z.iso.datetime(),
    estimated_cost: z.string().nullable(),
    feature: z.string(),
    id: z.string(),
    matched_policy_id: z.string().nullable(),
    model: z.string(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    provider: z.string(),
    reason: z.enum([
        'no_policy_matched',
        'policy_matched',
        'hard_limit_reached',
        'route_chain_exhausted',
        'uncosted_allowed',
        'uncosted_denied',
        'cap_not_applicable'
    ]),
    requested_model: z.string(),
    requested_provider: z.string(),
    status: z.enum([
        'reserved',
        'settled',
        'released',
        'expired',
        'unreserved'
    ])
});

export const zCustomerMarginResponse = z.object({
    cost: z.string(),
    display_name: z.string().nullable(),
    external_id: z.string(),
    id: z.string(),
    margin: z.string().nullable(),
    pace: z.string(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    plan_id: z.string().nullable(),
    plan_name: z.string().nullable(),
    revenue: z.string(),
    target_margin: z.string().nullable()
});

export const zCustomerResponse = z.object({
    created_at: z.iso.datetime(),
    display_name: z.string().nullable(),
    external_id: z.string(),
    id: z.string(),
    metadata: z.record(z.string(), z.unknown()),
    plan_id: z.string().nullable(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]),
    updated_at: z.iso.datetime()
});

export const zCustomerUsageResponse = z.object({
    cost: z.string(),
    feature: z.string(),
    model: z.string(),
    provider: z.string(),
    request_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    uncosted_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDailyTotalsResponse = z.object({
    cost: z.string(),
    date: z.iso.date(),
    revenue: z.string()
});

export const zDecisionCountsResponse = z.object({
    allow: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    cap: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    deny: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    route: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zCustomerPeriodResponse = z.object({
    cost: z.string(),
    decision_counts: zDecisionCountsResponse,
    margin: z.string().nullable(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    revenue: z.string(),
    uncosted_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDecisionLedgerEntryResponse = z.object({
    correction_of: z.string().nullable(),
    cost: z.string().nullable(),
    cost_status: z.enum(['costed', 'uncosted']),
    created_at: z.iso.datetime(),
    id: z.string(),
    model: z.string(),
    occurred_at: z.iso.datetime(),
    provider: z.string(),
    usage: z.record(z.string(), z.string())
});

export const zDecisionResponse = z.object({
    created_at: z.iso.datetime(),
    customer_display_name: z.string().nullable(),
    customer_external_id: z.string(),
    customer_id: z.string(),
    estimated_cost: z.string().nullable(),
    feature: z.string(),
    id: z.string(),
    matched_policy_id: z.string().nullable(),
    model: z.string(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    provider: z.string(),
    reason: z.enum([
        'no_policy_matched',
        'policy_matched',
        'hard_limit_reached',
        'route_chain_exhausted',
        'uncosted_allowed',
        'uncosted_denied',
        'cap_not_applicable'
    ]),
    requested_model: z.string(),
    requested_provider: z.string(),
    status: z.enum([
        'reserved',
        'settled',
        'released',
        'expired',
        'unreserved'
    ])
});

export const zFeatureSignalsResponse = z.object({
    cost_to_date: z.string(),
    period_decision_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    reserved: z.string()
});

export const zInspectLinkRequest = z.object({
    token: z.string()
});

export const zKeyPriceResponse = z.object({
    meter: z.enum([
        'input_tokens',
        'cached_input_tokens',
        'cache_write_input_tokens',
        'output_tokens',
        'reasoning_tokens',
        'input_audio_tokens',
        'output_audio_tokens',
        'input_seconds',
        'output_seconds',
        'gpu_seconds',
        'characters',
        'images',
        'megapixels',
        'audio_minutes',
        'requests',
        'search_requests'
    ]),
    unit_price: z.string(),
    unit_quantity: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zKnownFeatureResponse = z.object({
    feature: z.string(),
    sources: z.array(z.enum([
        'decisions',
        'plan_hold_times',
        'policies',
        'usage_estimates'
    ]))
});

export const zLinkDetailsResponse = z.object({
    display_name: z.string(),
    email: z.string(),
    purpose: z.enum(['invite', 'password_reset'])
});

export const zLoginRequest = z.object({
    email: z.string(),
    password: z.string()
});

export const zMemberResponse = z.object({
    created_at: z.iso.datetime(),
    display_name: z.string(),
    email: z.string(),
    has_password: z.boolean(),
    id: z.string(),
    last_login_at: z.iso.datetime().nullable(),
    status: z.enum(['active', 'disabled'])
});

export const zAddedMemberResponse = z.object({
    link_url: z.string(),
    member: zMemberResponse
});

export const zMeterDescription = z.object({
    description: z.string(),
    meter: z.enum([
        'input_tokens',
        'cached_input_tokens',
        'cache_write_input_tokens',
        'output_tokens',
        'reasoning_tokens',
        'input_audio_tokens',
        'output_audio_tokens',
        'input_seconds',
        'output_seconds',
        'gpu_seconds',
        'characters',
        'images',
        'megapixels',
        'audio_minutes',
        'requests',
        'search_requests'
    ]),
    unit: z.string()
});

export const zModelAttributeValue = z.object({
    sources: z.array(z.enum([
        'vocabulary',
        'parameter_mappings',
        'rules',
        'overrides'
    ])),
    value: z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])
});

export const zModelAttribute = z.object({
    key: z.string(),
    sources: z.array(z.enum([
        'vocabulary',
        'parameter_mappings',
        'rules',
        'overrides'
    ])),
    values: z.array(zModelAttributeValue)
});

export const zModelAttributes = z.object({
    attributes: z.array(zModelAttribute),
    model: z.string(),
    provider: z.string()
});

export const zModelResponse = z.object({
    display_name: z.string().nullable(),
    key_prices: z.array(zKeyPriceResponse),
    model: z.string(),
    provider: z.string(),
    status: z.enum(['active', 'deprecated'])
});

export const zOnboardingResponse = z.object({
    first_check_at: z.iso.datetime().nullable(),
    has_api_key: z.boolean(),
    has_plan: z.boolean(),
    has_policy: z.boolean(),
    has_revenue: z.boolean()
});

export const zOverrideResponse = z.object({
    billing_increment: z.string().nullable(),
    conditions: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])),
    created_at: z.iso.datetime(),
    effective_from: z.iso.datetime(),
    effective_to: z.iso.datetime().nullable(),
    effective_unit_price: z.string(),
    id: z.string(),
    meter: z.enum([
        'input_tokens',
        'cached_input_tokens',
        'cache_write_input_tokens',
        'output_tokens',
        'reasoning_tokens',
        'input_audio_tokens',
        'output_audio_tokens',
        'input_seconds',
        'output_seconds',
        'gpu_seconds',
        'characters',
        'images',
        'megapixels',
        'audio_minutes',
        'requests',
        'search_requests'
    ]),
    minimum_charge: z.string().nullable(),
    model: z.string(),
    native_unit: z.string().nullable(),
    native_unit_price: z.string().nullable(),
    provider: z.string(),
    type: z.enum(['adjustment', 'standalone']),
    unit_price: z.string(),
    unit_quantity: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    updated_at: z.iso.datetime()
});

export const zPageBodyApiKeyResponse = z.object({
    items: z.array(zApiKeyResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyActivityEventResponse = z.object({
    items: z.array(zActivityEventResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyCustomerMarginResponse = z.object({
    items: z.array(zCustomerMarginResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyDecisionResponse = z.object({
    items: z.array(zDecisionResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyKnownFeatureResponse = z.object({
    items: z.array(zKnownFeatureResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyMemberResponse = z.object({
    items: z.array(zMemberResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyMeterDescription = z.object({
    items: z.array(zMeterDescription),
    next_cursor: z.string().nullable()
});

export const zPageBodyModelResponse = z.object({
    items: z.array(zModelResponse),
    next_cursor: z.string().nullable()
});

export const zPageBodyOverrideResponse = z.object({
    items: z.array(zOverrideResponse),
    next_cursor: z.string().nullable()
});

export const zParameterResponse = z.object({
    allowed_values: z.array(z.union([
        z.string(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
        z.boolean()
    ])),
    effect: z.enum([
        'sets',
        'bounds',
        'prices'
    ]),
    maximum: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullable(),
    meter: z.string(),
    minimum: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullable(),
    provider_parameter: z.string(),
    quantities: z.record(z.string(), z.string()),
    value_type: z.enum([
        'string',
        'integer',
        'boolean'
    ])
});

export const zModelParametersResponse = z.object({
    model: z.string(),
    parameters: z.record(z.string(), zParameterResponse),
    provider: z.string()
});

export const zParameterMappingsResponse = z.object({
    models: z.array(zModelParametersResponse)
});

export const zPasswordChangeRequest = z.object({
    current: z.string(),
    new: z.string()
});

export const zPlanMarginResponse = z.object({
    below_target: z.boolean(),
    cost: z.string(),
    customer_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    margin: z.string().nullable(),
    mode: z.enum(['margin_target', 'fixed_allowance']).nullable(),
    name: z.string().nullable(),
    plan_id: z.string().nullable(),
    revenue: z.string(),
    target_margin: z.string().nullable()
});

export const zPlanResponse = z.object({
    allowance: z.string().nullable(),
    created_at: z.iso.datetime(),
    customer_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    hold_times: z.record(z.string(), z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })),
    id: z.string(),
    mode: z.enum(['margin_target', 'fixed_allowance']),
    name: z.string(),
    status: z.enum(['active', 'archived']),
    target_margin: z.string()
});

export const zPageBodyPlanResponse = z.object({
    items: z.array(zPlanResponse),
    next_cursor: z.string().nullable()
});

/**
 * What the policy decides when it matches.
 */
export const zPolicyAction = z.object({
    limit: z.object({
        kind: z.enum(['count', 'amount']),
        value: z.string()
    }).nullish(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    overrides: z.record(z.string(), z.union([
        z.string(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
        z.boolean()
    ])).nullish(),
    route_chain: z.array(z.object({
        model: z.string().min(1).max(200),
        provider: z.string().min(1).max(200)
    })).min(1).max(5).nullish()
});

export const zPolicyChangeResponse = z.object({
    change: z.enum(['created', 'updated']),
    created_at: z.iso.datetime(),
    id: z.string(),
    name: z.string(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]),
    updated_at: z.iso.datetime(),
    version: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

/**
 * Compares one signal of the customer's period with a value, signal first.
 */
export const zPolicyCondition = z.object({
    operator: z.enum([
        'lt',
        'lte',
        'gt',
        'gte',
        'eq',
        'ne'
    ]),
    signal: z.enum([
        'period_revenue_net',
        'cost_to_date',
        'elapsed_fraction',
        'allowance_remaining',
        'pace',
        'projected_margin',
        'request_estimated_cost',
        'period_decision_count'
    ]),
    value: z.string()
});

/**
 * Condition group holding exactly one of all and any. Members are conditions or nested groups, at most 3 groups deep counting this one.
 */
export const zPolicyConditionGroup = z.object({
    all: z.array(z.union([zPolicyCondition, z.lazy((): any => zPolicyConditionGroup)])).optional(),
    any: z.array(z.union([zPolicyCondition, z.lazy((): any => zPolicyConditionGroup)])).min(1).optional()
});

export const zPolicyOutcomeResponse = z.object({
    decided_at: z.iso.datetime(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    policy_id: z.string()
});

export const zLossCustomerResponse = z.object({
    cost: z.string(),
    display_name: z.string().nullable(),
    external_id: z.string(),
    id: z.string(),
    latest_policy_outcome: zPolicyOutcomeResponse.nullable(),
    margin: z.string(),
    plan_id: z.string().nullable(),
    revenue: z.string()
});

export const zOverviewResponse = z.object({
    attention: zAttentionResponse,
    cost: z.string(),
    cost_avoided: zCostAvoidedResponse,
    daily: z.array(zDailyTotalsResponse),
    decision_counts: zDecisionCountsResponse,
    loss_customers: z.array(zLossCustomerResponse),
    margin: z.string().nullable(),
    period: z.enum([
        'current',
        'previous',
        'last_30_days'
    ]),
    plan_margins: z.array(zPlanMarginResponse),
    policy_changes: z.array(zPolicyChangeResponse),
    revenue: z.string(),
    target_margin: z.string().nullable(),
    uncosted_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zPolicyPreviewResult = z.object({
    evaluated_customer_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    matched_customer_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    request_dependent: z.boolean()
});

export const zPolicyResponse = z.object({
    action: zPolicyAction,
    created_at: z.iso.datetime(),
    customer_id: z.string().nullable(),
    enforcement: z.enum(['soft', 'hard']),
    feature: z.string().nullable(),
    id: z.string(),
    level: z.enum([
        'everyone',
        'plan',
        'customer'
    ]),
    name: z.string(),
    on_uncosted: z.enum(['allow', 'deny']),
    on_unreachable: z.enum(['allow', 'deny']),
    plan_id: z.string().nullable(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]),
    updated_at: z.iso.datetime(),
    version: z.int().min(-2147483648, { error: 'Invalid value: Expected int32 to be >= -2147483648' }).max(2147483647, { error: 'Invalid value: Expected int32 to be <= 2147483647' }),
    when: zPolicyConditionGroup
});

export const zPageBodyPolicyResponse = z.object({
    items: z.array(zPolicyResponse),
    next_cursor: z.string().nullable()
});

export const zProblemError = z.object({
    location: z.string(),
    message: z.string()
});

export const zProblem = z.object({
    code: z.string(),
    detail: z.string(),
    errors: z.array(zProblemError).optional(),
    status: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    title: z.string(),
    type: z.string()
});

export const zQuoteRequest = z.object({
    attributes: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])).optional(),
    model: z.string(),
    provider: z.string(),
    usage: z.record(z.string(), z.string())
});

export const zRatedLineResponse = z.object({
    cost: z.string().nullable(),
    meter: z.enum([
        'input_tokens',
        'cached_input_tokens',
        'cache_write_input_tokens',
        'output_tokens',
        'reasoning_tokens',
        'input_audio_tokens',
        'output_audio_tokens',
        'input_seconds',
        'output_seconds',
        'gpu_seconds',
        'characters',
        'images',
        'megapixels',
        'audio_minutes',
        'requests',
        'search_requests'
    ]),
    missing: z.boolean(),
    pricing_override_id: z.string().nullable(),
    pricing_rule_id: z.string().nullable(),
    quantity: z.string(),
    unit_price: z.string().nullable(),
    unit_quantity: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullable()
});

export const zRatedRequestResponse = z.object({
    cost: z.string().nullable(),
    cost_status: z.enum(['costed', 'uncosted']),
    lines: z.array(zRatedLineResponse)
});

export const zRecordRevenueRequest = z.object({
    amount: z.string(),
    customer_id: z.string(),
    kind: z.enum([
        'subscription',
        'adjustment',
        'stripe_fee',
        'refund',
        'credit_note'
    ]),
    occurred_at: z.iso.datetime().optional(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    source_reference: z.string()
});

export const zRecordedRevenueEntryResponse = z.object({
    amount: z.string(),
    created_at: z.iso.datetime(),
    customer_id: z.string(),
    duplicate: z.boolean(),
    id: z.string(),
    kind: z.enum([
        'subscription',
        'adjustment',
        'stripe_fee',
        'refund',
        'credit_note'
    ]),
    occurred_at: z.iso.datetime(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    source: z.enum([
        'api',
        'stripe',
        'import'
    ]),
    source_reference: z.string()
});

export const zReleaseRequest = z.object({
    decision_id: z.string()
});

export const zReleaseResult = z.object({
    decision_id: z.string(),
    status: z.enum([
        'released',
        'settled',
        'expired',
        'unreserved'
    ])
});

export const zReportFailure = z.object({
    code: z.string(),
    detail: z.string(),
    errors: z.array(zProblemError).optional()
});

export const zReportRequest = z.object({
    attributes: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])).optional(),
    customer_id: z.string().optional(),
    decision_id: z.string().optional(),
    decision_source: z.string().optional(),
    feature: z.string().optional(),
    idempotency_key: z.string().optional(),
    model: z.string().optional(),
    occurred_at: z.iso.datetime().optional(),
    provider: z.string().optional(),
    usage: z.record(z.string(), z.string()).optional()
});

export const zReportBatchRequest = z.object({
    reports: z.array(zReportRequest)
});

export const zReportResult = z.object({
    cost: z.string().nullable(),
    cost_status: z.enum(['costed', 'uncosted']),
    duplicate: z.boolean(),
    ledger_entry_id: z.string()
});

export const zReportBatchResult = z.object({
    error: zReportFailure.optional(),
    result: zReportResult.optional(),
    status: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zReportBatchResponse = z.object({
    results: z.array(zReportBatchResult)
});

export const zResetLinkResponse = z.object({
    link_url: z.string()
});

export const zRevenueEntryResponse = z.object({
    amount: z.string(),
    created_at: z.iso.datetime(),
    customer_id: z.string(),
    id: z.string(),
    kind: z.enum([
        'subscription',
        'adjustment',
        'stripe_fee',
        'refund',
        'credit_note'
    ]),
    occurred_at: z.iso.datetime(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    source: z.enum([
        'api',
        'stripe',
        'import'
    ]),
    source_reference: z.string()
});

export const zPageBodyRevenueEntryResponse = z.object({
    items: z.array(zRevenueEntryResponse),
    next_cursor: z.string().nullable()
});

export const zSettingsResponse = z.object({
    default_plan_id: z.string().nullable(),
    installation_name: z.string(),
    stripe_customer_metadata_key: z.string()
});

export const zSetupStatusResponse = z.object({
    setup_required: z.boolean()
});

export const zSignalsResponse = z.object({
    allowance_remaining: z.string(),
    cost_allowance: z.string(),
    cost_to_date: z.string(),
    elapsed_fraction: z.string(),
    features: z.record(z.string(), zFeatureSignalsResponse),
    pace: z.string(),
    period_decision_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    period_revenue_net: z.string(),
    projected_margin: z.string(),
    request_estimated_cost: z.string().nullable(),
    reserved: z.string()
});

export const zCheckResponse = z.object({
    cost_status: z.enum(['costed', 'uncosted']),
    decision_id: z.string(),
    estimate_basis: z.enum([
        'p95',
        'ceiling',
        'request_estimate',
        'none'
    ]),
    estimated_cost: z.string().nullable(),
    expires_at: z.iso.datetime(),
    fallback_outcome: z.enum(['allow', 'deny']),
    matched_policy_id: z.string().nullable(),
    model: z.string(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    overrides: z.record(z.string(), z.union([
        z.string(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
        z.boolean()
    ])),
    provider: z.string(),
    reason: z.enum([
        'no_policy_matched',
        'policy_matched',
        'hard_limit_reached',
        'route_chain_exhausted',
        'uncosted_allowed',
        'uncosted_denied',
        'cap_not_applicable'
    ]),
    reserved_amount: z.string(),
    signals: zSignalsResponse
});

export const zCustomerDetailResponse = z.object({
    display_name: z.string().nullable(),
    external_id: z.string(),
    history: z.array(zCustomerPeriodResponse),
    id: z.string(),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    plan_id: z.string().nullable(),
    plan_name: z.string().nullable(),
    recent_decisions: z.array(zCustomerDecisionResponse),
    signals: zSignalsResponse,
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]),
    target_margin: z.string().nullable(),
    usage: z.array(zCustomerUsageResponse)
});

export const zCustomerSignalsResponse = z.object({
    created_at: z.iso.datetime(),
    display_name: z.string().nullable(),
    effective_plan_id: z.string().nullable(),
    external_id: z.string(),
    id: z.string(),
    metadata: z.record(z.string(), z.unknown()),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    plan_id: z.string().nullable(),
    signals: zSignalsResponse,
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]),
    updated_at: z.iso.datetime()
});

export const zDecisionDetailResponse = z.object({
    attributes: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])),
    created_at: z.iso.datetime(),
    customer_display_name: z.string().nullable(),
    customer_external_id: z.string(),
    customer_id: z.string(),
    customer_user_external_id: z.string().nullable(),
    estimate_basis: z.enum([
        'p95',
        'ceiling',
        'request_estimate',
        'none'
    ]),
    estimated_cost: z.string().nullable(),
    expires_at: z.iso.datetime(),
    feature: z.string(),
    id: z.string(),
    ledger_entries: z.array(zDecisionLedgerEntryResponse),
    matched_policy_id: z.string().nullable(),
    matched_policy_version: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullable(),
    model: z.string(),
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]),
    overrides: z.record(z.string(), z.union([
        z.string(),
        z.boolean(),
        z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
    ])),
    period_end: z.iso.datetime(),
    period_start: z.iso.datetime(),
    provider: z.string(),
    reason: z.enum([
        'no_policy_matched',
        'policy_matched',
        'hard_limit_reached',
        'route_chain_exhausted',
        'uncosted_allowed',
        'uncosted_denied',
        'cap_not_applicable'
    ]),
    requested_estimated_cost: z.string().nullable(),
    requested_model: z.string(),
    requested_provider: z.string(),
    reserved_amount: z.string(),
    settled_at: z.iso.datetime().nullable(),
    signals: zSignalsResponse,
    status: z.enum([
        'reserved',
        'settled',
        'released',
        'expired',
        'unreserved'
    ])
});

export const zPageBodyCustomerSignalsResponse = z.object({
    items: z.array(zCustomerSignalsResponse),
    next_cursor: z.string().nullable()
});

export const zUncostedUsage = z.object({
    last_seen_at: z.iso.datetime(),
    meter: z.enum([
        'input_tokens',
        'cached_input_tokens',
        'cache_write_input_tokens',
        'output_tokens',
        'reasoning_tokens',
        'input_audio_tokens',
        'output_audio_tokens',
        'input_seconds',
        'output_seconds',
        'gpu_seconds',
        'characters',
        'images',
        'megapixels',
        'audio_minutes',
        'requests',
        'search_requests'
    ]),
    model: z.string(),
    provider: z.string(),
    request_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zPageBodyUncostedUsage = z.object({
    items: z.array(zUncostedUsage),
    next_cursor: z.string().nullable()
});

export const zUpdateCurrentMemberRequest = z.object({
    display_name: z.string().optional(),
    password: zPasswordChangeRequest.optional()
});

export const zUpdateOverrideRequest = z.object({
    billing_increment: z.string().nullish(),
    effective_to: z.iso.datetime().nullish(),
    minimum_charge: z.string().nullish(),
    native_unit: z.string().nullish(),
    native_unit_price: z.string().nullish(),
    unit_price: z.string().optional(),
    unit_quantity: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

export const zUpdatePlanRequest = z.object({
    allowance: z.string().optional(),
    hold_times: z.record(z.string(), z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })).optional(),
    mode: z.enum(['margin_target', 'fixed_allowance']).optional(),
    name: z.string().optional(),
    status: z.enum(['active', 'archived']).optional(),
    target_margin: z.string().optional()
});

export const zUpdateSettingsRequest = z.object({
    default_plan_id: z.string().nullish(),
    installation_name: z.string().optional(),
    stripe_customer_metadata_key: z.string().optional()
});

export const zUpsertCustomerRequest = z.object({
    display_name: z.string().nullish(),
    metadata: z.record(z.string(), z.unknown()).optional(),
    plan_id: z.string().nullish()
});

export const zListApiKeysQuery = z.object({
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListApiKeysResponse = zPageBodyApiKeyResponse;

export const zCreateApiKeyBody = zCreateApiKeyRequest;

/**
 * Created
 */
export const zCreateApiKeyResponse = zCreatedApiKeyResponse;

export const zRevokeApiKeyPath = z.object({
    api_key_id: z.string()
});

/**
 * No Content
 */
export const zRevokeApiKeyResponse = z.void();

export const zConsumeLinkBody = zConsumeLinkRequest;

/**
 * OK
 */
export const zConsumeLinkResponse = zMemberResponse;

export const zInspectLinkBody = zInspectLinkRequest;

/**
 * OK
 */
export const zInspectLinkResponse = zLinkDetailsResponse;

export const zLoginBody = zLoginRequest;

/**
 * OK
 */
export const zLoginResponse = zMemberResponse;

/**
 * No Content
 */
export const zLogoutResponse = z.void();

/**
 * OK
 */
export const zGetCurrentMemberResponse = zMemberResponse;

export const zUpdateCurrentMemberBody = zUpdateCurrentMemberRequest;

/**
 * OK
 */
export const zUpdateCurrentMemberResponse = zMemberResponse;

export const zCheckBody = zCheckRequest;

/**
 * OK
 */
export const zCheckResponse2 = zCheckResponse;

export const zListCustomersQuery = z.object({
    search: z.string().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListCustomersResponse = zPageBodyCustomerSignalsResponse;

export const zGetCustomerPath = z.object({
    external_id: z.string()
});

/**
 * OK
 */
export const zGetCustomerResponse = zCustomerSignalsResponse;

export const zUpsertCustomerBody = zUpsertCustomerRequest;

export const zUpsertCustomerPath = z.object({
    external_id: z.string()
});

/**
 * OK
 */
export const zUpsertCustomerResponse = zCustomerResponse;

export const zListDashboardCustomersQuery = z.object({
    sort: z.enum([
        'margin',
        'pace',
        'cost',
        'revenue'
    ]).optional().default('margin'),
    direction: z.enum(['ascending', 'descending']).optional().default('ascending'),
    revenue_filter: z.enum([
        'all',
        'paying',
        'free'
    ]).optional().default('all'),
    plan_id: z.string().optional(),
    search: z.string().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListDashboardCustomersResponse = zPageBodyCustomerMarginResponse;

export const zGetDashboardCustomerPath = z.object({
    customer_id: z.string()
});

/**
 * OK
 */
export const zGetDashboardCustomerResponse = zCustomerDetailResponse;

export const zListDashboardDecisionsQuery = z.object({
    outcome: z.enum([
        'allow',
        'route',
        'cap',
        'deny'
    ]).optional(),
    customer_id: z.string().optional(),
    feature: z.string().optional(),
    policy_id: z.string().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListDashboardDecisionsResponse = zPageBodyDecisionResponse;

export const zStreamDashboardDecisionsHeaders = z.object({
    'Last-Event-ID': z.string().optional()
});

export const zStreamDashboardDecisionsQuery = z.object({
    environment: z.enum(['test', 'live']),
    last_event_id: z.string().optional()
});

/**
 * One server-sent event. Comment lines are heartbeats.
 */
export const zStreamDashboardDecisionsResponse = z.object({
    data: z.object({
        created_at: z.iso.datetime(),
        customer_display_name: z.string().nullable(),
        customer_external_id: z.string(),
        customer_id: z.string(),
        estimated_cost: z.string().nullable(),
        feature: z.string(),
        id: z.string(),
        matched_policy_id: z.string().nullable(),
        model: z.string(),
        outcome: z.enum([
            'allow',
            'route',
            'cap',
            'deny'
        ]),
        reason: z.enum([
            'no_policy_matched',
            'policy_matched',
            'hard_limit_reached',
            'route_chain_exhausted',
            'uncosted_allowed',
            'uncosted_denied',
            'cap_not_applicable'
        ]),
        requested_model: z.string()
    }),
    event: z.enum(['decision']),
    id: z.string()
});

export const zGetDashboardDecisionPath = z.object({
    decision_id: z.string()
});

/**
 * OK
 */
export const zGetDashboardDecisionResponse = zDecisionDetailResponse;

export const zListDashboardEventsQuery = z.object({
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListDashboardEventsResponse = zPageBodyActivityEventResponse;

/**
 * OK
 */
export const zListDashboardFeaturesResponse = zPageBodyKnownFeatureResponse;

/**
 * OK
 */
export const zGetDashboardOnboardingResponse = zOnboardingResponse;

export const zGetDashboardOverviewQuery = z.object({
    period: z.enum([
        'current',
        'previous',
        'last_30_days'
    ]).optional().default('current')
});

/**
 * OK
 */
export const zGetDashboardOverviewResponse = zOverviewResponse;

export const zListMembersQuery = z.object({
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListMembersResponse = zPageBodyMemberResponse;

export const zAddMemberBody = zAddMemberRequest;

/**
 * Created
 */
export const zAddMemberResponse = zAddedMemberResponse;

export const zRemoveMemberPath = z.object({
    member_id: z.string()
});

/**
 * No Content
 */
export const zRemoveMemberResponse = z.void();

export const zCreateResetLinkPath = z.object({
    member_id: z.string()
});

/**
 * Created
 */
export const zCreateResetLinkResponse = zResetLinkResponse;

export const zListPlansQuery = z.object({
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListPlansResponse = zPageBodyPlanResponse;

export const zCreatePlanBody = zCreatePlanRequest;

/**
 * Created
 */
export const zCreatePlanResponse = zPlanResponse;

export const zGetPlanPath = z.object({
    plan_id: z.string()
});

/**
 * OK
 */
export const zGetPlanResponse = zPlanResponse;

export const zUpdatePlanBody = zUpdatePlanRequest;

export const zUpdatePlanPath = z.object({
    plan_id: z.string()
});

/**
 * OK
 */
export const zUpdatePlanResponse = zPlanResponse;

export const zListPoliciesQuery = z.object({
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]).optional(),
    plan_id: z.string().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListPoliciesResponse = zPageBodyPolicyResponse;

/**
 * Policy document. The server checks every field and answers 422 policy_invalid with one error per failing field.
 */
export const zCreatePolicyBody = z.object({
    action: zPolicyAction,
    customer_id: z.string().nullish(),
    enforcement: z.enum(['soft', 'hard']),
    feature: z.string().nullish(),
    level: z.enum([
        'everyone',
        'plan',
        'customer'
    ]),
    name: z.string(),
    on_uncosted: z.enum(['allow', 'deny']),
    on_unreachable: z.enum(['allow', 'deny']),
    plan_id: z.string().nullish(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]).optional(),
    when: zPolicyConditionGroup
});

/**
 * Created
 */
export const zCreatePolicyResponse = zPolicyResponse;

/**
 * OK
 */
export const zGetParameterMappingsResponse = zParameterMappingsResponse;

/**
 * Policy document. The server checks every field and answers 422 policy_invalid with one error per failing field.
 */
export const zPreviewPolicyBody = z.object({
    action: zPolicyAction,
    customer_id: z.string().nullish(),
    enforcement: z.enum(['soft', 'hard']),
    feature: z.string().nullish(),
    level: z.enum([
        'everyone',
        'plan',
        'customer'
    ]),
    name: z.string(),
    on_uncosted: z.enum(['allow', 'deny']),
    on_unreachable: z.enum(['allow', 'deny']),
    plan_id: z.string().nullish(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]).optional(),
    when: zPolicyConditionGroup
});

/**
 * OK
 */
export const zPreviewPolicyResponse = zPolicyPreviewResult;

export const zGetPolicyPath = z.object({
    policy_id: z.string()
});

/**
 * OK
 */
export const zGetPolicyResponse = zPolicyResponse;

/**
 * Policy document fields to replace. Omitted fields keep their stored values.
 */
export const zUpdatePolicyBody = z.object({
    action: zPolicyAction.optional(),
    customer_id: z.string().nullish(),
    enforcement: z.enum(['soft', 'hard']).optional(),
    feature: z.string().nullish(),
    level: z.enum([
        'everyone',
        'plan',
        'customer'
    ]).optional(),
    name: z.string().optional(),
    on_uncosted: z.enum(['allow', 'deny']).optional(),
    on_unreachable: z.enum(['allow', 'deny']).optional(),
    plan_id: z.string().nullish(),
    status: z.enum([
        'active',
        'disabled',
        'archived'
    ]).optional(),
    when: zPolicyConditionGroup.optional()
});

export const zUpdatePolicyPath = z.object({
    policy_id: z.string()
});

/**
 * OK
 */
export const zUpdatePolicyResponse = zPolicyResponse;

/**
 * OK
 */
export const zListPricingMetersResponse = zPageBodyMeterDescription;

export const zGetPricingModelAttributesQuery = z.object({
    provider: z.string().min(1),
    model: z.string().min(1)
});

/**
 * OK
 */
export const zGetPricingModelAttributesResponse = zModelAttributes;

export const zListPricingModelsQuery = z.object({
    search: z.string().optional(),
    provider: z.string().optional(),
    meter: z.string().optional(),
    include_deprecated: z.boolean().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListPricingModelsResponse = zPageBodyModelResponse;

export const zListPricingOverridesQuery = z.object({
    include_ended: z.boolean().optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListPricingOverridesResponse = zPageBodyOverrideResponse;

export const zCreatePricingOverrideBody = zCreateOverrideRequest;

/**
 * Created
 */
export const zCreatePricingOverrideResponse = zOverrideResponse;

export const zEndPricingOverridePath = z.object({
    pricing_override_id: z.string()
});

/**
 * No Content
 */
export const zEndPricingOverrideResponse = z.void();

export const zGetPricingOverridePath = z.object({
    pricing_override_id: z.string()
});

/**
 * OK
 */
export const zGetPricingOverrideResponse = zOverrideResponse;

export const zUpdatePricingOverrideBody = zUpdateOverrideRequest;

export const zUpdatePricingOverridePath = z.object({
    pricing_override_id: z.string()
});

/**
 * OK
 */
export const zUpdatePricingOverrideResponse = zOverrideResponse;

export const zCreatePricingQuoteBody = zQuoteRequest;

/**
 * OK
 */
export const zCreatePricingQuoteResponse = zRatedRequestResponse;

export const zListPricingUncostedQuery = z.object({
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListPricingUncostedResponse = zPageBodyUncostedUsage;

export const zReleaseDecisionBody = zReleaseRequest;

/**
 * OK
 */
export const zReleaseDecisionResponse = zReleaseResult;

export const zReportUsageBody = zReportRequest;

export const zReportUsageHeaders = z.object({
    'Preburn-Dropped-Reports': z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * Accepted
 */
export const zReportUsageResponse = zReportResult;

export const zReportUsageBatchBody = zReportBatchRequest;

export const zReportUsageBatchHeaders = z.object({
    'Preburn-Dropped-Reports': z.coerce.bigint().gte(BigInt(0)).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * Accepted
 */
export const zReportUsageBatchResponse = zReportBatchResponse;

export const zListRevenueQuery = z.object({
    customer_id: z.string().optional(),
    kind: z.enum([
        'subscription',
        'adjustment',
        'stripe_fee',
        'refund',
        'credit_note'
    ]).optional(),
    cursor: z.string().optional(),
    limit: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional()
});

/**
 * OK
 */
export const zListRevenueResponse = zPageBodyRevenueEntryResponse;

export const zRecordRevenueBody = zRecordRevenueRequest;

/**
 * The environment already had an entry of this kind and source reference from the revenue API. The body is that entry with duplicate true.
 */
export const zRecordRevenueResponse = zRecordedRevenueEntryResponse;

/**
 * OK
 */
export const zGetSettingsResponse = zSettingsResponse;

export const zUpdateSettingsBody = zUpdateSettingsRequest;

/**
 * OK
 */
export const zUpdateSettingsResponse = zSettingsResponse;

export const zCompleteSetupBody = zCompleteSetupRequest;

/**
 * OK
 */
export const zCompleteSetupResponse = zMemberResponse;

/**
 * OK
 */
export const zGetSetupStatusResponse = zSetupStatusResponse;
