/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppCustomersRouteRouteImport } from './routes/_app/customers/route'
import { Route as AppDecisionsRouteRouteImport } from './routes/_app/decisions/route'
import { Route as AppGalleryRouteImport } from './routes/_app/gallery'
import { Route as AppPlansRouteRouteImport } from './routes/_app/plans/route'
import { Route as AppPoliciesRouteRouteImport } from './routes/_app/policies/route'
import { Route as AuthLinkRouteImport } from './routes/_auth/link'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthSetupRouteImport } from './routes/_auth/setup'
import { Route as AppCustomersIndexRouteImport } from './routes/_app/customers/index'
import { Route as AppCustomersCustomerIdRouteImport } from './routes/_app/customers/$customerId'
import { Route as AppDecisionsIndexRouteImport } from './routes/_app/decisions/index'
import { Route as AppDecisionsDecisionIdRouteImport } from './routes/_app/decisions/$decisionId'
import { Route as AppDevelopersApiKeysRouteImport } from './routes/_app/developers/api-keys'
import { Route as AppDevelopersGetStartedRouteImport } from './routes/_app/developers/get-started'
import { Route as AppDevelopersSdkRouteImport } from './routes/_app/developers/sdk'
import { Route as AppPlansIndexRouteImport } from './routes/_app/plans/index'
import { Route as AppPlansPlanIdRouteImport } from './routes/_app/plans/$planId'
import { Route as AppPlansNewRouteImport } from './routes/_app/plans/new'
import { Route as AppPoliciesIndexRouteImport } from './routes/_app/policies/index'
import { Route as AppPoliciesPolicyIdRouteImport } from './routes/_app/policies/$policyId'
import { Route as AppPoliciesNewRouteImport } from './routes/_app/policies/new'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppSettingsInstallationRouteImport } from './routes/_app/settings/installation'
import { Route as AppSettingsMembersRouteImport } from './routes/_app/settings/members'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRouteRoute = AppCustomersRouteRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppDecisionsRouteRoute = AppDecisionsRouteRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => AppRoute,
} as any)
const AppGalleryRoute = AppGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRouteRoute = AppPlansRouteRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRouteRoute = AppPoliciesRouteRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AuthLinkRoute = AuthLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSetupRoute = AuthSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthRoute,
} as any)
const AppCustomersIndexRoute = AppCustomersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppCustomersCustomerIdRoute = AppCustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => AppCustomersRouteRoute,
} as any)
const AppDecisionsIndexRoute = AppDecisionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDecisionsRouteRoute,
} as any)
const AppDecisionsDecisionIdRoute = AppDecisionsDecisionIdRouteImport.update({
  id: '/$decisionId',
  path: '/$decisionId',
  getParentRoute: () => AppDecisionsRouteRoute,
} as any)
const AppDevelopersApiKeysRoute = AppDevelopersApiKeysRouteImport.update({
  id: '/developers/api-keys',
  path: '/developers/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersGetStartedRoute = AppDevelopersGetStartedRouteImport.update({
  id: '/developers/get-started',
  path: '/developers/get-started',
  getParentRoute: () => AppRoute,
} as any)
const AppDevelopersSdkRoute = AppDevelopersSdkRouteImport.update({
  id: '/developers/sdk',
  path: '/developers/sdk',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansIndexRoute = AppPlansIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPlansPlanIdRoute = AppPlansPlanIdRouteImport.update({
  id: '/$planId',
  path: '/$planId',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPlansNewRoute = AppPlansNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPlansRouteRoute,
} as any)
const AppPoliciesIndexRoute = AppPoliciesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPoliciesRouteRoute,
} as any)
const AppPoliciesPolicyIdRoute = AppPoliciesPolicyIdRouteImport.update({
  id: '/$policyId',
  path: '/$policyId',
  getParentRoute: () => AppPoliciesRouteRoute,
} as any)
const AppPoliciesNewRoute = AppPoliciesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppPoliciesRouteRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsInstallationRoute = AppSettingsInstallationRouteImport.update({
  id: '/settings/installation',
  path: '/settings/installation',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/customers': typeof AppCustomersRouteRouteWithChildren
  '/decisions': typeof AppDecisionsRouteRouteWithChildren
  '/plans': typeof AppPlansRouteRouteWithChildren
  '/policies': typeof AppPoliciesRouteRouteWithChildren
  '/account': typeof AppAccountRoute
  '/gallery': typeof AppGalleryRoute
  '/link': typeof AuthLinkRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/developers/get-started': typeof AppDevelopersGetStartedRoute
  '/developers/sdk': typeof AppDevelopersSdkRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/plans/new': typeof AppPlansNewRoute
  '/policies/$policyId': typeof AppPoliciesPolicyIdRoute
  '/policies/new': typeof AppPoliciesNewRoute
  '/settings/installation': typeof AppSettingsInstallationRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/customers/': typeof AppCustomersIndexRoute
  '/decisions/': typeof AppDecisionsIndexRoute
  '/plans/': typeof AppPlansIndexRoute
  '/policies/': typeof AppPoliciesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/account': typeof AppAccountRoute
  '/gallery': typeof AppGalleryRoute
  '/link': typeof AuthLinkRoute
  '/login': typeof AuthLoginRoute
  '/setup': typeof AuthSetupRoute
  '/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/developers/get-started': typeof AppDevelopersGetStartedRoute
  '/developers/sdk': typeof AppDevelopersSdkRoute
  '/plans/$planId': typeof AppPlansPlanIdRoute
  '/plans/new': typeof AppPlansNewRoute
  '/policies/$policyId': typeof AppPoliciesPolicyIdRoute
  '/policies/new': typeof AppPoliciesNewRoute
  '/settings/installation': typeof AppSettingsInstallationRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/customers': typeof AppCustomersIndexRoute
  '/decisions': typeof AppDecisionsIndexRoute
  '/plans': typeof AppPlansIndexRoute
  '/policies': typeof AppPoliciesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/customers': typeof AppCustomersRouteRouteWithChildren
  '/_app/decisions': typeof AppDecisionsRouteRouteWithChildren
  '/_app/plans': typeof AppPlansRouteRouteWithChildren
  '/_app/policies': typeof AppPoliciesRouteRouteWithChildren
  '/_app/account': typeof AppAccountRoute
  '/_app/gallery': typeof AppGalleryRoute
  '/_auth/link': typeof AuthLinkRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/setup': typeof AuthSetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/customers/$customerId': typeof AppCustomersCustomerIdRoute
  '/_app/decisions/$decisionId': typeof AppDecisionsDecisionIdRoute
  '/_app/developers/api-keys': typeof AppDevelopersApiKeysRoute
  '/_app/developers/get-started': typeof AppDevelopersGetStartedRoute
  '/_app/developers/sdk': typeof AppDevelopersSdkRoute
  '/_app/plans/$planId': typeof AppPlansPlanIdRoute
  '/_app/plans/new': typeof AppPlansNewRoute
  '/_app/policies/$policyId': typeof AppPoliciesPolicyIdRoute
  '/_app/policies/new': typeof AppPoliciesNewRoute
  '/_app/settings/installation': typeof AppSettingsInstallationRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/customers/': typeof AppCustomersIndexRoute
  '/_app/decisions/': typeof AppDecisionsIndexRoute
  '/_app/plans/': typeof AppPlansIndexRoute
  '/_app/policies/': typeof AppPoliciesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/decisions'
    | '/plans'
    | '/policies'
    | '/account'
    | '/gallery'
    | '/link'
    | '/login'
    | '/setup'
    | '/customers/$customerId'
    | '/decisions/$decisionId'
    | '/developers/api-keys'
    | '/developers/get-started'
    | '/developers/sdk'
    | '/plans/$planId'
    | '/plans/new'
    | '/policies/$policyId'
    | '/policies/new'
    | '/settings/installation'
    | '/settings/members'
    | '/customers/'
    | '/decisions/'
    | '/plans/'
    | '/policies/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/gallery'
    | '/link'
    | '/login'
    | '/setup'
    | '/customers/$customerId'
    | '/decisions/$decisionId'
    | '/developers/api-keys'
    | '/developers/get-started'
    | '/developers/sdk'
    | '/plans/$planId'
    | '/plans/new'
    | '/policies/$policyId'
    | '/policies/new'
    | '/settings/installation'
    | '/settings/members'
    | '/customers'
    | '/decisions'
    | '/plans'
    | '/policies'
    | '/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/customers'
    | '/_app/decisions'
    | '/_app/plans'
    | '/_app/policies'
    | '/_app/account'
    | '/_app/gallery'
    | '/_auth/link'
    | '/_auth/login'
    | '/_auth/setup'
    | '/_app/'
    | '/_app/customers/$customerId'
    | '/_app/decisions/$decisionId'
    | '/_app/developers/api-keys'
    | '/_app/developers/get-started'
    | '/_app/developers/sdk'
    | '/_app/plans/$planId'
    | '/_app/plans/new'
    | '/_app/policies/$policyId'
    | '/_app/policies/new'
    | '/_app/settings/installation'
    | '/_app/settings/members'
    | '/_app/customers/'
    | '/_app/decisions/'
    | '/_app/plans/'
    | '/_app/policies/'
    | '/_app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/decisions': {
      id: '/_app/decisions'
      path: '/decisions'
      fullPath: '/decisions'
      preLoaderRoute: typeof AppDecisionsRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gallery': {
      id: '/_app/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof AppGalleryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans': {
      id: '/_app/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof AppPlansRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/link': {
      id: '/_auth/link'
      path: '/link'
      fullPath: '/link'
      preLoaderRoute: typeof AuthLinkRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/setup': {
      id: '/_auth/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthSetupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/customers/': {
      id: '/_app/customers/'
      path: '/'
      fullPath: '/customers/'
      preLoaderRoute: typeof AppCustomersIndexRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/_app/customers/$customerId': {
      id: '/_app/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AppCustomersCustomerIdRouteImport
      parentRoute: typeof AppCustomersRouteRoute
    }
    '/_app/decisions/': {
      id: '/_app/decisions/'
      path: '/'
      fullPath: '/decisions/'
      preLoaderRoute: typeof AppDecisionsIndexRouteImport
      parentRoute: typeof AppDecisionsRouteRoute
    }
    '/_app/decisions/$decisionId': {
      id: '/_app/decisions/$decisionId'
      path: '/$decisionId'
      fullPath: '/decisions/$decisionId'
      preLoaderRoute: typeof AppDecisionsDecisionIdRouteImport
      parentRoute: typeof AppDecisionsRouteRoute
    }
    '/_app/developers/api-keys': {
      id: '/_app/developers/api-keys'
      path: '/developers/api-keys'
      fullPath: '/developers/api-keys'
      preLoaderRoute: typeof AppDevelopersApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/get-started': {
      id: '/_app/developers/get-started'
      path: '/developers/get-started'
      fullPath: '/developers/get-started'
      preLoaderRoute: typeof AppDevelopersGetStartedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/developers/sdk': {
      id: '/_app/developers/sdk'
      path: '/developers/sdk'
      fullPath: '/developers/sdk'
      preLoaderRoute: typeof AppDevelopersSdkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/plans/': {
      id: '/_app/plans/'
      path: '/'
      fullPath: '/plans/'
      preLoaderRoute: typeof AppPlansIndexRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/_app/plans/$planId': {
      id: '/_app/plans/$planId'
      path: '/$planId'
      fullPath: '/plans/$planId'
      preLoaderRoute: typeof AppPlansPlanIdRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/_app/plans/new': {
      id: '/_app/plans/new'
      path: '/new'
      fullPath: '/plans/new'
      preLoaderRoute: typeof AppPlansNewRouteImport
      parentRoute: typeof AppPlansRouteRoute
    }
    '/_app/policies/': {
      id: '/_app/policies/'
      path: '/'
      fullPath: '/policies/'
      preLoaderRoute: typeof AppPoliciesIndexRouteImport
      parentRoute: typeof AppPoliciesRouteRoute
    }
    '/_app/policies/$policyId': {
      id: '/_app/policies/$policyId'
      path: '/$policyId'
      fullPath: '/policies/$policyId'
      preLoaderRoute: typeof AppPoliciesPolicyIdRouteImport
      parentRoute: typeof AppPoliciesRouteRoute
    }
    '/_app/policies/new': {
      id: '/_app/policies/new'
      path: '/new'
      fullPath: '/policies/new'
      preLoaderRoute: typeof AppPoliciesNewRouteImport
      parentRoute: typeof AppPoliciesRouteRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/installation': {
      id: '/_app/settings/installation'
      path: '/settings/installation'
      fullPath: '/settings/installation'
      preLoaderRoute: typeof AppSettingsInstallationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCustomersRouteRouteChildren {
  AppCustomersCustomerIdRoute: typeof AppCustomersCustomerIdRoute
  AppCustomersIndexRoute: typeof AppCustomersIndexRoute
}

const AppCustomersRouteRouteChildren: AppCustomersRouteRouteChildren = {
  AppCustomersCustomerIdRoute: AppCustomersCustomerIdRoute,
  AppCustomersIndexRoute: AppCustomersIndexRoute,
}

const AppCustomersRouteRouteWithChildren =
  AppCustomersRouteRoute._addFileChildren(AppCustomersRouteRouteChildren)

interface AppDecisionsRouteRouteChildren {
  AppDecisionsDecisionIdRoute: typeof AppDecisionsDecisionIdRoute
  AppDecisionsIndexRoute: typeof AppDecisionsIndexRoute
}

const AppDecisionsRouteRouteChildren: AppDecisionsRouteRouteChildren = {
  AppDecisionsDecisionIdRoute: AppDecisionsDecisionIdRoute,
  AppDecisionsIndexRoute: AppDecisionsIndexRoute,
}

const AppDecisionsRouteRouteWithChildren =
  AppDecisionsRouteRoute._addFileChildren(AppDecisionsRouteRouteChildren)

interface AppPlansRouteRouteChildren {
  AppPlansPlanIdRoute: typeof AppPlansPlanIdRoute
  AppPlansNewRoute: typeof AppPlansNewRoute
  AppPlansIndexRoute: typeof AppPlansIndexRoute
}

const AppPlansRouteRouteChildren: AppPlansRouteRouteChildren = {
  AppPlansPlanIdRoute: AppPlansPlanIdRoute,
  AppPlansNewRoute: AppPlansNewRoute,
  AppPlansIndexRoute: AppPlansIndexRoute,
}

const AppPlansRouteRouteWithChildren = AppPlansRouteRoute._addFileChildren(
  AppPlansRouteRouteChildren,
)

interface AppPoliciesRouteRouteChildren {
  AppPoliciesPolicyIdRoute: typeof AppPoliciesPolicyIdRoute
  AppPoliciesNewRoute: typeof AppPoliciesNewRoute
  AppPoliciesIndexRoute: typeof AppPoliciesIndexRoute
}

const AppPoliciesRouteRouteChildren: AppPoliciesRouteRouteChildren = {
  AppPoliciesPolicyIdRoute: AppPoliciesPolicyIdRoute,
  AppPoliciesNewRoute: AppPoliciesNewRoute,
  AppPoliciesIndexRoute: AppPoliciesIndexRoute,
}

const AppPoliciesRouteRouteWithChildren =
  AppPoliciesRouteRoute._addFileChildren(AppPoliciesRouteRouteChildren)

interface AppRouteChildren {
  AppCustomersRouteRoute: typeof AppCustomersRouteRouteWithChildren
  AppDecisionsRouteRoute: typeof AppDecisionsRouteRouteWithChildren
  AppPlansRouteRoute: typeof AppPlansRouteRouteWithChildren
  AppPoliciesRouteRoute: typeof AppPoliciesRouteRouteWithChildren
  AppAccountRoute: typeof AppAccountRoute
  AppGalleryRoute: typeof AppGalleryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppDevelopersApiKeysRoute: typeof AppDevelopersApiKeysRoute
  AppDevelopersGetStartedRoute: typeof AppDevelopersGetStartedRoute
  AppDevelopersSdkRoute: typeof AppDevelopersSdkRoute
  AppSettingsInstallationRoute: typeof AppSettingsInstallationRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCustomersRouteRoute: AppCustomersRouteRouteWithChildren,
  AppDecisionsRouteRoute: AppDecisionsRouteRouteWithChildren,
  AppPlansRouteRoute: AppPlansRouteRouteWithChildren,
  AppPoliciesRouteRoute: AppPoliciesRouteRouteWithChildren,
  AppAccountRoute: AppAccountRoute,
  AppGalleryRoute: AppGalleryRoute,
  AppIndexRoute: AppIndexRoute,
  AppDevelopersApiKeysRoute: AppDevelopersApiKeysRoute,
  AppDevelopersGetStartedRoute: AppDevelopersGetStartedRoute,
  AppDevelopersSdkRoute: AppDevelopersSdkRoute,
  AppSettingsInstallationRoute: AppSettingsInstallationRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLinkRoute: typeof AuthLinkRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetupRoute: typeof AuthSetupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLinkRoute: AuthLinkRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSetupRoute: AuthSetupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
