// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customer_users.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertCustomerUserIfMissing = `-- name: InsertCustomerUserIfMissing :one
INSERT INTO customer_users (customer_user_id, environment, customer_id, external_id, created_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (environment, customer_id, external_id) DO NOTHING
RETURNING customer_user_id, environment, customer_id, external_id, import_id, created_at
`

type InsertCustomerUserIfMissingParams struct {
	CustomerUserID uuid.UUID
	Environment    Environment
	CustomerID     uuid.UUID
	ExternalID     string
	CreatedAt      time.Time
}

func (q *Queries) InsertCustomerUserIfMissing(ctx context.Context, arg InsertCustomerUserIfMissingParams) (CustomerUser, error) {
	row := q.db.QueryRow(ctx, insertCustomerUserIfMissing,
		arg.CustomerUserID,
		arg.Environment,
		arg.CustomerID,
		arg.ExternalID,
		arg.CreatedAt,
	)
	var i CustomerUser
	err := row.Scan(
		&i.CustomerUserID,
		&i.Environment,
		&i.CustomerID,
		&i.ExternalID,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}

const selectCustomerUser = `-- name: SelectCustomerUser :one
SELECT customer_user_id, environment, customer_id, external_id, import_id, created_at
FROM customer_users
WHERE environment = $1
    AND customer_id = $2
    AND external_id = $3
`

type SelectCustomerUserParams struct {
	Environment Environment
	CustomerID  uuid.UUID
	ExternalID  string
}

func (q *Queries) SelectCustomerUser(ctx context.Context, arg SelectCustomerUserParams) (CustomerUser, error) {
	row := q.db.QueryRow(ctx, selectCustomerUser, arg.Environment, arg.CustomerID, arg.ExternalID)
	var i CustomerUser
	err := row.Scan(
		&i.CustomerUserID,
		&i.Environment,
		&i.CustomerID,
		&i.ExternalID,
		&i.ImportID,
		&i.CreatedAt,
	)
	return i, err
}
