// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertCustomerIfMissing = `-- name: InsertCustomerIfMissing :one
INSERT INTO customers (customer_id, environment, external_id, status, created_at, updated_at)
VALUES ($1, $2, $3, 'active', $4, $4)
ON CONFLICT (environment, external_id) DO NOTHING
RETURNING customer_id, environment, external_id, display_name, plan_id, stripe_customer_id, metadata, status, import_id, created_at, updated_at
`

type InsertCustomerIfMissingParams struct {
	CustomerID  uuid.UUID
	Environment Environment
	ExternalID  string
	CreatedAt   time.Time
}

func (q *Queries) InsertCustomerIfMissing(ctx context.Context, arg InsertCustomerIfMissingParams) (Customer, error) {
	row := q.db.QueryRow(ctx, insertCustomerIfMissing,
		arg.CustomerID,
		arg.Environment,
		arg.ExternalID,
		arg.CreatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Environment,
		&i.ExternalID,
		&i.DisplayName,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.Metadata,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT customer_id, environment, external_id, display_name, plan_id, stripe_customer_id, metadata, status, import_id, created_at, updated_at
FROM customers
WHERE environment = $1
    AND (
        $2::text IS NULL
        OR lower(external_id) LIKE $2::text
    )
    AND (
        $3::timestamptz IS NULL
        OR (created_at, customer_id) < ($3::timestamptz, $4::uuid)
    )
ORDER BY created_at DESC, customer_id DESC
LIMIT $5::bigint
`

type ListCustomersParams struct {
	Environment       Environment
	ExternalIDPattern *string
	AfterCreatedAt    *time.Time
	AfterCustomerID   *uuid.UUID
	RowLimit          int64
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers,
		arg.Environment,
		arg.ExternalIDPattern,
		arg.AfterCreatedAt,
		arg.AfterCustomerID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.CustomerID,
			&i.Environment,
			&i.ExternalID,
			&i.DisplayName,
			&i.PlanID,
			&i.StripeCustomerID,
			&i.Metadata,
			&i.Status,
			&i.ImportID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectActivePlanExists = `-- name: SelectActivePlanExists :one
SELECT EXISTS (
    SELECT 1
    FROM plans
    WHERE environment = $1
        AND plan_id = $2
        AND status = 'active'
)
`

type SelectActivePlanExistsParams struct {
	Environment Environment
	PlanID      uuid.UUID
}

func (q *Queries) SelectActivePlanExists(ctx context.Context, arg SelectActivePlanExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, selectActivePlanExists, arg.Environment, arg.PlanID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const selectCustomerByExternalID = `-- name: SelectCustomerByExternalID :one
SELECT customer_id, environment, external_id, display_name, plan_id, stripe_customer_id, metadata, status, import_id, created_at, updated_at
FROM customers
WHERE environment = $1
    AND external_id = $2
`

type SelectCustomerByExternalIDParams struct {
	Environment Environment
	ExternalID  string
}

func (q *Queries) SelectCustomerByExternalID(ctx context.Context, arg SelectCustomerByExternalIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, selectCustomerByExternalID, arg.Environment, arg.ExternalID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Environment,
		&i.ExternalID,
		&i.DisplayName,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.Metadata,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectCustomerByID = `-- name: SelectCustomerByID :one
SELECT customer_id, environment, external_id, display_name, plan_id, stripe_customer_id, metadata, status, import_id, created_at, updated_at
FROM customers
WHERE environment = $1
    AND customer_id = $2
`

type SelectCustomerByIDParams struct {
	Environment Environment
	CustomerID  uuid.UUID
}

func (q *Queries) SelectCustomerByID(ctx context.Context, arg SelectCustomerByIDParams) (Customer, error) {
	row := q.db.QueryRow(ctx, selectCustomerByID, arg.Environment, arg.CustomerID)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Environment,
		&i.ExternalID,
		&i.DisplayName,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.Metadata,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCustomer = `-- name: UpsertCustomer :one
INSERT INTO customers (
    customer_id, environment, external_id, display_name, plan_id, metadata, status, created_at, updated_at
)
VALUES (
    $1, $2, $3, $4, $5, $6, 'active', $7, $7
)
ON CONFLICT (environment, external_id) DO UPDATE
SET display_name = EXCLUDED.display_name,
    plan_id = EXCLUDED.plan_id,
    metadata = EXCLUDED.metadata,
    updated_at = EXCLUDED.updated_at
RETURNING customer_id, environment, external_id, display_name, plan_id, stripe_customer_id, metadata, status, import_id, created_at, updated_at
`

type UpsertCustomerParams struct {
	CustomerID  uuid.UUID
	Environment Environment
	ExternalID  string
	DisplayName *string
	PlanID      *uuid.UUID
	Metadata    []byte
	WrittenAt   time.Time
}

func (q *Queries) UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, upsertCustomer,
		arg.CustomerID,
		arg.Environment,
		arg.ExternalID,
		arg.DisplayName,
		arg.PlanID,
		arg.Metadata,
		arg.WrittenAt,
	)
	var i Customer
	err := row.Scan(
		&i.CustomerID,
		&i.Environment,
		&i.ExternalID,
		&i.DisplayName,
		&i.PlanID,
		&i.StripeCustomerID,
		&i.Metadata,
		&i.Status,
		&i.ImportID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
